"""Generate db/sql/45-section-menus.sql (W8N.3, NAV-IA-01..04).

Five of the six sections had no second-level navigation and twelve published
pages were reachable from no menu at all. This writes:

  * a menu per section, whose item labels are READ FROM THE PAGES THEMSELVES
    (page_translations) at import time, in all three languages — no label is
    typed here, so a page renamed in the admin renames its own menu entry the
    next time this file is imported, and nothing invents Bangla or Chinese;
  * the `travel` hub page, which never existed: /travel was a 308 to
    /travel/status, so the first item in the primary navigation was the only
    one without an address of its own;
  * a `section-subnav` block at the top of each hub page.

Idempotent: every statement is guarded on what it is about to create. Plain
statements only — no DELIMITER, no stored procedure — because the fresh-import
rehearsal (tests/db/fresh-import.test.js) runs the file through mysql2.
"""
import io
import os

OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'db', 'sql', '45-section-menus.sql')

# menu slug -> page slugs, in the order a reader should meet them.
MENUS = {
    'travel': [
        'travel/status', 'travel/toll', 'travel/payment', 'travel/route', 'travel/map',
        'travel/vehicle-classes', 'travel/rules', 'travel/advisories', 'travel/cameras',
        'travel/breakdown', 'travel/lost-found', 'travel/toll-dispute', 'travel/facilities',
        'travel/freight',
    ],
    'about': [
        'about/concession', 'about/governance', 'about/organisation', 'about/integrity',
        'about/recognition', 'about/careers',
    ],
    'project': ['project/standards', 'project/structures', 'project/virtual-tour'],
    'disclosures': [
        'disclosures/citizen-charter', 'disclosures/right-to-information', 'disclosures/tariff',
        'disclosures/policies', 'disclosures/reports', 'disclosures/land-acquisition',
        'disclosures/environment', 'disclosures/consultations', 'procurement',
    ],
    'safety': ['safety/education', 'travel/rules', 'travel/advisories', 'travel/breakdown'],
    'media': ['press-releases', 'news', 'gallery', 'gallery/videos', 'downloads', 'contact'],
}

# hub page slug -> the menu its sub-navigation renders.
HUBS = {
    'travel': 'travel',
    'about': 'about',
    'project': 'project',
    'disclosures': 'disclosures',
    'safety': 'safety',
    'media': 'media',
}

# The travel hub, which has to be created before it can carry anything. The
# titles are the ui strings the header already uses for this section in each
# language (lib/i18n/ui.js navTravel), so nothing new is written in Bangla or
# Chinese here either.
TRAVEL_TITLES = {
    'en': 'Travel information',
    'bn': 'ভ্রমণ তথ্য',
    'zh': '出行信息',
}

out = io.StringIO()
w = out.write

w("""-- 45: second-level navigation (W8N.3; navigation audit NAV-IA-01..04).
--
-- GENERATED by scripts/content/gen_section_menus.py. Edit that, not this.
--
-- Three things, all of them navigation and none of them new prose:
--
--   1. The `travel` hub page. /travel was a 308 to /travel/status, so the first
--      item in the primary navigation had no address of its own: a reader who
--      clicked "Travel Info" landed on a page called "What's open" and a shared
--      link recorded the leaf rather than the section. The redirect rows are
--      removed and a real page takes the address.
--
--   2. A menu for each section — travel, about, project, disclosures, safety,
--      media. EVERY LABEL IS READ FROM THE PAGE ITSELF, in each language, so a
--      title changed in the admin changes its menu entry, and no Bangla or
--      Chinese is written here.
--
--   3. A `section-subnav` block at the top of each hub, which is what turns the
--      menus into second-level navigation a reader can see. Twelve pages were
--      reachable from no navigation at all before this.
--
-- Safe to import twice: every statement is guarded on what it creates.

SET NAMES utf8mb4;

-- ---- 1. the travel hub -----------------------------------------------------
-- The redirects that stood where the page should be. They were written when
-- the old `travel` page became `travel/status`; a page now takes that address,
-- and a redirect would shadow it.
DELETE FROM `redirects` WHERE `source` IN ('/en/travel', '/bn/travel', '/zh/travel')
  AND `destination` IN ('/en/travel/status', '/bn/travel/status', '/zh/travel/status');

INSERT INTO `pages` (`slug`, `status`, `nav_order`)
  SELECT 'travel', 'published', 5 FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM (SELECT `id` FROM `pages` WHERE `slug` = 'travel') AS x);
SET @travel = (SELECT `id` FROM `pages` WHERE `slug` = 'travel');
""")

for locale, title in TRAVEL_TITLES.items():
    w(f"""
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `status`)
  SELECT @travel, '{locale}', '{title}', 'published' FROM DUAL
   WHERE @travel IS NOT NULL AND NOT EXISTS (
     SELECT 1 FROM (SELECT `page_id` FROM `page_translations`
                     WHERE `page_id` = @travel AND `locale` = '{locale}') AS x);""")

w("""

-- The hub's own page header, titled from the rows just written.
SET @ok = (@travel IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @travel AND `type` IN ('page-header', 'hero')) = 0);
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @travel, 'page-header', 0, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('eyebrow', '', 'heading', pt.`title`, 'lede', '', 'showUpdated', 'no'), 'published'
    FROM `page_translations` pt WHERE @b IS NOT NULL AND pt.`page_id` = @travel AND pt.`title` <> '';

-- ---- 2. the menus ----------------------------------------------------------
""")

for menu, slugs in MENUS.items():
    w(f"\nINSERT IGNORE INTO `menus` (`slug`) VALUES ('{menu}');\n")
    w(f"SET @m = (SELECT `id` FROM `menus` WHERE `slug` = '{menu}');\n")
    for i, slug in enumerate(slugs):
        # No leading slash: that is the authoring rule lib/blocks/href.js
        # enforces, and it is what makes one stored link resolve to /en/…,
        # /bn/… and /zh/… for the three readers. A leading slash would be used
        # literally and send every reader to the English page.
        href = slug
        w(f"""DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/{slug}';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = '{href}');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, '{href}', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), {(i + 1) * 10}
    FROM `pages` p
   WHERE p.`slug` = '{slug}' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
""")

w("""
-- ---- 3. the sub-navigation blocks -----------------------------------------
-- At the top of each hub, above whatever the page already says. Existing blocks
-- move down one place; the guard means that happens only on the first import.
""")

for page_slug, menu in HUBS.items():
    w(f"""
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = '{page_slug}');
SET @ok = (@p IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @p AND `type` = 'section-subnav') = 0);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `page_id` = @p AND @ok AND `type` <> 'page-header' AND `type` <> 'hero';
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @p, 'section-subnav', 1, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('menu', '{menu}', 'label', pt.`title`), 'published'
    FROM `page_translations` pt
   WHERE @b IS NOT NULL AND pt.`page_id` = @p AND pt.`title` <> '';
""")

w("""
-- A sub-navigation announced as "Travel Info" on the About page is the block's
-- default label showing through. Name each one after its own section, in each
-- language, from the page's title — and only where the operator has not set a
-- label of their own.
UPDATE `block_translations` bt
  JOIN `blocks` b ON b.`id` = bt.`block_id` AND b.`type` = 'section-subnav'
  JOIN `page_translations` pt ON pt.`page_id` = b.`page_id` AND pt.`locale` = bt.`locale`
   SET bt.`data` = JSON_SET(bt.`data`, '$.label', pt.`title`)
 WHERE COALESCE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.label')), '') = ''
   AND pt.`title` <> '';

INSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('45-section-menus');
""")

with open(os.path.abspath(OUT), 'w', encoding='utf-8', newline='\n') as f:
    f.write(out.getvalue())
print('wrote', os.path.abspath(OUT))
