"""Generate db/sql/52-audit-trust-fixes.sql and db/sql/53-everyday-bangla.sql.

From the human-quality audit (docs/audit/2026-09-17-human-quality-audit.md).
Every replacement names the exact text it replaces, taken from production, and
only touches a row that still contains it — so an editor's later change is
never overwritten and a second import changes nothing.

Two kinds of statement:
  body(slug, locale, old, new)   top-level `body` of a block, JSON-aware
  text(where, old, new)          anywhere in a translation's JSON text
                                 (nested fields; words without quotes)
"""
import os

ROOT = os.path.join(os.path.dirname(__file__), '..', '..')


def q(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def body(slug, locale, old, new):
    return (
        "UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`\n"
        f"   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), {q(old)}, {q(new)}))\n"
        f" WHERE p.`slug` = {q(slug)} AND bt.`locale` = {q(locale)}\n"
        f"   AND LOCATE({q(old)}, JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;\n"
    )


def text(old, new, locale=None, slugs=None, exclude=None):
    where = []
    if locale:
        where.append(f"bt.`locale` = {q(locale)}")
    if slugs:
        where.append("p.`slug` IN (" + ", ".join(q(s) for s in slugs) + ")")
    if exclude:
        where.append("p.`slug` NOT IN (" + ", ".join(q(s) for s in exclude) + ")")
    where.append(f"LOCATE({q(old)}, CAST(bt.`data` AS CHAR)) > 0")
    return (
        "UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`\n"
        f"   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), {q(old)}, {q(new)})\n"
        " WHERE " + "\n   AND ".join(where) + ";\n"
    )


def page_title(old, new, locale='bn', slugs=None):
    cond = f"pt.`locale` = {q(locale)}"
    if slugs:
        cond += " AND p.`slug` IN (" + ", ".join(q(s) for s in slugs) + ")"
    out = []
    for col in ('title', 'seo_title', 'seo_description'):
        out.append(
            f"UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`{col}` = REPLACE(pt.`{col}`, {q(old)}, {q(new)})"
            f" WHERE {cond} AND LOCATE({q(old)}, pt.`{col}`) > 0;\n"
        )
    return ''.join(out)


def menu(old, new):
    return (
        f"UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), {q(old)}, {q(new)})"
        f" WHERE LOCATE({q(old)}, CAST(`labels` AS CHAR)) > 0;\n"
    )


# --------------------------------------------------------------------------
# 52: trust fixes (audit C1, C3, C7, C9, C10, C11, T3, T4)
# --------------------------------------------------------------------------
s = ["""-- 52: trust fixes from the human-quality audit (2026-09-17).
--
-- GENERATED by scripts/content/gen_audit_fixes.py. Edit that, not this.
--
--   C7  the sample control-room number (+880 2 5555 0199) is no longer
--       published: the setting is cleared, the sample directory entry loses
--       the number, and the safety and rules pages say "call 999".
--   C1  the home page no longer says the project figures are withheld while
--       About shows them.
--   C11 the rules page no longer sends three-wheelers to service roads that
--       its own table closes to them.
--   C3  one following distance: three seconds, as the education page says.
--   C9  the privacy notice names the traffic provider the code uses, and
--       lists road-alert sign-ups.
--   C10 the accessibility statement stops saying Chinese has no font.
--   T3  the Bangla home page loses a "two hours" claim the English never made.
--   T4  "US$৪১২ মি." (read as metres) becomes "৪১২ মিলিয়ন ডলার".
--
-- Every statement matches the exact text it replaces, so it is safe to
-- import twice and never overwrites an editor's later wording.

SET NAMES utf8mb4;

-- C7 --------------------------------------------------------------------
UPDATE `site_settings` SET `value` = '""'
 WHERE `setting_key` = 'contact.emergency_phone' AND LOCATE('5555 0199', CAST(`value` AS CHAR)) > 0;
"""]
s.append(text('"phone":"+880 2 5555 0199"', '"phone":""'))
s.append(text('"phone": "+880 2 5555 0199"', '"phone": ""'))

s.append(body('safety', 'en',
    'In an emergency, call the DBEDC emergency line or the national emergency service — both numbers are at the foot of every page — and follow the instructions of the roadside staff. Ambulance, towing and recovery are arranged through the DBEDC emergency line.',
    'In an emergency, call 999 and follow the instructions of the roadside staff.'))
s.append(body('safety', 'bn',
    'জরুরি অবস্থায় DBEDC জরুরি নম্বরে অথবা জাতীয় জরুরি সেবায় কল করুন — দুটি নম্বরই প্রতিটি পাতার নিচে দেওয়া আছে — এবং সড়ক কর্মীদের নির্দেশনা মেনে চলুন। অ্যাম্বুলেন্স, টোয়িং ও উদ্ধার সেবা DBEDC জরুরি নম্বরের মাধ্যমে ব্যবস্থা করা হয়।',
    'জরুরি অবস্থায় ৯৯৯-এ কল করুন এবং সড়ক কর্মীদের নির্দেশনা মেনে চলুন।'))
s.append(body('safety', 'zh',
    '遇到紧急情况，请拨打 DBEDC 紧急电话或国家紧急服务电话（两个号码均列于每页底部），并听从路侧工作人员的指示。救护车、拖车与救援服务通过 DBEDC 紧急电话安排。',
    '遇到紧急情况，请拨打 999，并听从路侧工作人员的指示。'))

s.append(body('travel/rules', 'en',
    'Call the DBEDC emergency line shown at the foot of every page, or use the nearest emergency call point. In a medical emergency call 999.',
    'Call 999, or use the nearest emergency call point.'))
s.append(body('travel/rules', 'bn',
    'প্রতিটি পাতার নিচে দেওয়া DBEDC জরুরি নম্বরে কল করুন অথবা নিকটতম জরুরি কল পয়েন্ট (প্রতি ২ কিমি) ব্যবহার করুন। চিকিৎসা জরুরি অবস্থায় ৯৯৯-এ কল করুন।',
    '৯৯৯-এ কল করুন অথবা নিকটতম জরুরি কল পয়েন্ট (প্রতি ২ কিমি) ব্যবহার করুন।'))
s.append(body('travel/rules', 'zh',
    '拨打每页底部所示的 DBEDC 紧急电话，或使用最近的紧急呼叫点（每 2 公里一处）。医疗紧急情况请拨 999。',
    '拨打 999，或使用最近的紧急呼叫点（每 2 公里一处）。'))

# C1 --------------------------------------------------------------------
s.append("\n-- C1: the withheld-figures paragraph on the home page, in every language.\n")
for loc in ('en', 'bn', 'zh'):
    s.append(
        "UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`\n"
        "   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REGEXP_REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<p class=\"db-provisional-inline\">[^<]*</p>', ''))\n"
        f" WHERE p.`slug` = 'home' AND b.`type` = 'media-prose' AND bt.`locale` = '{loc}'\n"
        "   AND LOCATE('db-provisional-inline', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;\n")

# C11 -------------------------------------------------------------------
s.append("\n-- C11: service roads are for motorcycles, not three-wheelers.\n")
s.append(body('travel/rules', 'en',
    'The service roads running beside the tolled carriageways carry this traffic and connect to the same places. They are the correct route, not a diversion — the corridor was built with them for exactly this purpose.',
    'Motorcycles may use the service roads beside the toll carriageways, which connect to the same places. Three-wheelers, rickshaws and non-motorised vehicles may not use the service roads either, and should use the local road network.'))
s.append(body('travel/rules', 'bn',
    'টোল ক্যারেজওয়ের পাশ দিয়ে চলা সার্ভিস রোডগুলি এই যান চলাচল বহন করে এবং একই গন্তব্যে পৌঁছায়। এগুলি বিকল্প বা ঘুরপথ নয়, এগুলিই সঠিক পথ — করিডোরটি ঠিক এই উদ্দেশ্যেই সার্ভিস রোডসহ নির্মিত।',
    'টোল রোডের পাশের সার্ভিস রোড দিয়ে মোটরসাইকেল চলতে পারবে; এই রোড একই জায়গাগুলোতে যায়। থ্রি-হুইলার, রিকশা ও অযান্ত্রিক যান সার্ভিস রোডেও চলতে পারবে না — এগুলোকে স্থানীয় রাস্তা ব্যবহার করতে হবে।'))
s.append(body('travel/rules', 'zh',
    '收费行车道两侧的辅路承载此类交通，并通往相同目的地。它们不是绕行路线，而是正确路线——本走廊正是为此而配建辅路。',
    '摩托车可以走收费车道两侧的辅路，辅路通往相同的地点。三轮车、人力车和非机动车同样不得使用辅路，应走当地道路。'))

# C3 --------------------------------------------------------------------
s.append("\n-- C3: one following distance across the site.\n")
s.append(body('travel/rules', 'en', 'keep a gap of at least two seconds', 'keep a gap of at least three seconds'))
s.append(body('travel/rules', 'bn', 'অন্তত দুই সেকেন্ডের দূরত্ব', 'অন্তত তিন সেকেন্ডের দূরত্ব'))
s.append(body('travel/rules', 'zh', '保持至少两秒的车距', '保持至少三秒的车距'))

# C9 --------------------------------------------------------------------
s.append("\n-- C9: the traffic provider is Google's Routes API; road-alert sign-ups are listed.\n")
s.append(body('privacy', 'en',
    'road-condition data on the map is fetched by our server from TomTom; nothing about you is sent to TomTom.',
    'our server asks Google (Routes API) for journey times on each section of the corridor; nothing about you is sent with those requests.'))
s.append(body('privacy', 'bn',
    'মানচিত্রের সড়ক অবস্থার তথ্য আমাদের সার্ভার TomTom থেকে আনে; আপনার সম্পর্কে কিছুই TomTom-কে পাঠানো হয় না।',
    'আমাদের সার্ভার করিডোরের প্রতিটি অংশের যাত্রার সময় Google (Routes API) থেকে জেনে নেয়; এসব অনুরোধের সঙ্গে আপনার সম্পর্কে কিছুই পাঠানো হয় না।'))
s.append(body('privacy', 'zh',
    '地图上的路况数据由我们的服务器从 TomTom 获取；不会向 TomTom 发送任何关于您的信息。',
    '我们的服务器向 Google（Routes API）查询走廊各路段的行程时间；这些请求不包含任何关于您的信息。'))
s.append(body('privacy', 'en',
    '<li>Email sign-ups — the address only: until you unsubscribe or ask for removal.</li>',
    '<li>Email sign-ups — the address only: until you unsubscribe or ask for removal.</li><li>Road-alert sign-ups — your mobile number and the channel you chose (SMS or WhatsApp): until you unsubscribe.</li>'))
s.append(body('privacy', 'bn',
    '<li>ইমেইল সাবস্ক্রিপশন — শুধু ঠিকানা: আপনি বাদ দিতে না বলা পর্যন্ত।</li>',
    '<li>ইমেইল সাবস্ক্রিপশন — শুধু ঠিকানা: আপনি বাদ দিতে না বলা পর্যন্ত।</li><li>রোড অ্যালার্ট সাবস্ক্রিপশন — আপনার মোবাইল নম্বর ও বেছে নেওয়া মাধ্যম (SMS বা WhatsApp): আনসাবস্ক্রাইব না করা পর্যন্ত।</li>'))
s.append(body('privacy', 'zh',
    '<li>邮件订阅——仅邮箱地址：直至您退订或要求删除。</li>',
    '<li>邮件订阅——仅邮箱地址：直至您退订或要求删除。</li><li>道路提醒订阅——您的手机号码及所选渠道（短信或 WhatsApp）：直至您退订。</li>'))

# C10 -------------------------------------------------------------------
s.append("\n-- C10: Chinese pages do load a font (self-hosted Noto Sans SC).\n")
s.append(body('accessibility', 'en',
    '<p><strong>Chinese pages have no supplied font.</strong> The site ships Latin and Bengali web fonts but no Chinese one, so a reader on a device without a Chinese font installed may see empty boxes instead of characters.</p>',
    '<p><strong>Chinese text loads in parts.</strong> Chinese pages use a self-hosted Noto Sans SC font that downloads in pieces, so on a slow connection some characters may first appear in your device’s own font.</p>'))
s.append(body('accessibility', 'bn',
    '<p><strong>চীনা পৃষ্ঠার জন্য কোনও ফন্ট সরবরাহ করা হয় না।</strong> সাইটটি ল্যাটিন ও বাংলা ওয়েব ফন্ট সরবরাহ করে, চীনা নয় — তাই যে ডিভাইসে চীনা ফন্ট ইনস্টল করা নেই সেখানে অক্ষরের বদলে খালি বাক্স দেখা যেতে পারে।</p>',
    '<p><strong>চীনা লেখা ধাপে ধাপে লোড হয়।</strong> চীনা পেজে সাইটের নিজস্ব Noto Sans SC ফন্ট টুকরো টুকরো ডাউনলোড হয়, তাই ধীর ইন্টারনেটে কিছু অক্ষর প্রথমে আপনার ডিভাইসের নিজের ফন্টে দেখা যেতে পারে।</p>'))
s.append(body('accessibility', 'zh',
    '<p><strong>中文页面未附带字体。</strong>本站提供拉丁文与孟加拉文网页字体，但未提供中文字体，因此未安装中文字体的设备可能显示空白方框而非文字。</p>',
    '<p><strong>中文字体分段加载。</strong>中文页面使用本站自托管的 Noto Sans SC 字体，按需分段下载；网络较慢时，部分文字可能先以设备自带字体显示。</p>'))

# T3 / T4 ---------------------------------------------------------------
s.append("\n-- T3: the Bangla home page says what the English says.\n")
s.append(body('home', 'bn',
    'এবং এ কারণেই শহরের ভেতর দিয়ে যে যাত্রায় দুই ঘণ্টা লাগে, সম্পূর্ণ করিডোর খুলে গেলে তা তার সামান্য সময়েই শেষ হওয়ার কথা।',
    'এবং সে কারণেই পুরো করিডোর খুলে গেলে যে যাত্রা এখন শহরের ভেতর দিয়ে যায়, তা শহরকে পুরোপুরি এড়িয়ে যাবে।'))
s.append("\n-- T4: \"মি.\" reads as metres.\n")
for sp in ('', ' '):
    s.append(text(f'"unit":{sp}"মি."', f'"unit":{sp}"মিলিয়ন ডলার"', locale='bn'))
    s.append(text(f'"value":{sp}"US$৪১২"', f'"value":{sp}"৪১২"', locale='bn'))

s.append("\nINSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('52-audit-trust-fixes');\n")

# --------------------------------------------------------------------------
# 53: everyday Bangla (audit 2b)
# --------------------------------------------------------------------------
e = ["""-- 53: everyday Bangla (human-quality audit, section 2b).
--
-- GENERATED by scripts/content/gen_audit_fixes.py. Edit that, not this.
--
-- The Bangla a road user in Dhaka reads on signs, apps and news sites uses
-- the English word where that is what people say: ম্যাপ, not মানচিত্র;
-- আপডেট, not হালনাগাদ; পেজ, not পাতা. Statutory terms stay formal
-- (তথ্য অধিকার, নাগরিক সনদ, টোল বিজ্ঞপ্তি…), and the tariff notification
-- page keeps "যানবাহনের শ্রেণি", the wording of the gazette. Longer forms are
-- replaced before shorter ones, so suffixes come out right (পাতায় → পেজে).
-- Safe to import twice.

SET NAMES utf8mb4;
"""]

GENERAL = [
    ('মানচিত্রের', 'ম্যাপের'), ('মানচিত্রে', 'ম্যাপে'), ('মানচিত্র', 'ম্যাপ'),
    ('হালনাগাদ', 'আপডেট'),
    ('পৃষ্ঠস্তর', 'কার্পেটিং'),
    ('বহির্গমন পথ', 'এক্সিট'), ('বহির্গমন', 'এক্সিট'),
    ('আলোকচিত্র', 'ছবি'),
    ('পৃষ্ঠার', 'পেজের'), ('পৃষ্ঠায়', 'পেজে'), ('পৃষ্ঠাটি', 'পেজটি'), ('পৃষ্ঠা', 'পেজ'),
    ('পাতাগুলো', 'পেজগুলো'), ('পাতাগুলি', 'পেজগুলো'), ('পাতাতেই', 'পেজেই'), ('পাতাতেও', 'পেজেও'),
    ('পাতাপ্রতি', 'পেজপ্রতি'), ('পাতায়', 'পেজে'), ('পাতার', 'পেজের'), ('পাতাটি', 'পেজটি'), ('পাতা', 'পেজ'),
    ('প্রবেশ, প্রস্থান', 'এন্ট্রি, এক্সিট'), ('প্রবেশ ও প্রস্থানের', 'এন্ট্রি ও এক্সিটের'), ('প্রবেশ ও প্রস্থান', 'এন্ট্রি ও এক্সিট'),
    ('প্রস্থানের', 'এক্সিটের'), ('প্রস্থানে', 'এক্সিটে'), ('প্রস্থান', 'এক্সিট'),
]
VEHICLE = [
    ('যানবাহনের শ্রেণির', 'গাড়ির ধরনের'), ('যানবাহন শ্রেণির', 'গাড়ির ধরনের'),
    ('যানবাহনের শ্রেণি', 'গাড়ির ধরন'), ('যানবাহন শ্রেণি', 'গাড়ির ধরন'),
    ('আপনার শ্রেণির', 'আপনার গাড়ির ধরনের'),
]

e.append("-- Blocks\n")
for old, new in GENERAL:
    e.append(text(old, new, locale='bn'))
for old, new in VEHICLE:
    e.append(text(old, new, locale='bn', exclude=['disclosures/tariff']))
# "live" on the cameras page, and the search page's own name
for old, new in (('সরাসরি দেখুন', 'লাইভ দেখুন'), ('সরাসরি ভিডিও', 'লাইভ ভিডিও')):
    e.append(text(old, new, locale='bn', slugs=['travel/cameras']))
e.append(text('"heading":"অনুসন্ধান"', '"heading":"সার্চ"', locale='bn', slugs=['search']))
e.append(text('"heading": "অনুসন্ধান"', '"heading": "সার্চ"', locale='bn', slugs=['search']))
e.append(text('অভিযোগ ও অনুসন্ধান', 'অভিযোগ ও সার্চ', locale='bn', slugs=['accessibility']))

e.append("\n-- Page titles and descriptions\n")
for old, new in GENERAL:
    e.append(page_title(old, new))
for old, new in VEHICLE:
    e.append(page_title(old, new))
e.append(page_title('সরাসরি দৃশ্য', 'লাইভ দৃশ্য', slugs=['travel/cameras']))
e.append(page_title('অনুসন্ধান', 'সার্চ', slugs=['search']))

e.append("\n-- Menu labels (they are copies of the page titles)\n")
for old, new in GENERAL + VEHICLE:
    e.append(menu(old, new))

e.append("\nINSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('53-everyday-bangla');\n")

for name, parts in (('52-audit-trust-fixes.sql', s), ('53-everyday-bangla.sql', e)):
    with open(os.path.join(ROOT, 'db', 'sql', name), 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(parts))
    print('wrote', name)
