-- 22-callout-migration.sql — inline provenance markers become callout blocks.
--
-- GENERATED by scripts/generate-callout-migration.mjs from the seeded content;
-- do not edit by hand, regenerate.
--
-- The "Not yet published" and "Previous website information" notices were
-- <p class="db-pending"> and <div class="db-archive"> paragraphs typed inside
-- rich-text bodies: a convention held together by a class name that one
-- careless edit in the rich-text editor drops, silently turning a legal
-- provenance marker into an ordinary paragraph. The callout block makes the
-- tone a FIELD (lib/blocks/types/callout.js); its standard tag comes from
-- ui_strings so every notice reads the same and is edited in one place.
--
-- Two shapes were found, both identical across en/bn/zh:
--   [marker]          the block IS the notice -> its type becomes callout
--   [prose, marker]   the marker is trimmed off the body and a new callout
--                     block is inserted at the same sort_order with a higher
--                     id, so it renders directly after (order is sort_order, id)
--
-- Blocks are located by PAGE SLUG + TYPE + a run of the English marker text,
-- never by id or sort order: 02-seed.sql numbers these blocks 12, 16, 18...
-- and a re-seeded development database numbers the same blocks 135, 137,
-- 143...; 07-block-order.sql renumbers sort orders and an operator can drag a
-- block. The content is the one thing both databases share.
--
-- Every statement is guarded on the marker still being present, so a
-- re-import changes nothing and an operator's later edit is never overwritten.
-- ID map: new blocks 360+.


-- /about/governance sort 1 (source block 16): prose,legacy
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'about/governance' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'l 2021. The current concession terms and ownership should be checked with DBEDC.') > 0
    ORDER BY b.`id` LIMIT 1);
SET @sort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @blk);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 360, (SELECT `id` FROM `pages` WHERE `slug` = 'about/governance' LIMIT 1), 'callout', @sort, NULL, 'published' FROM DUAL
  WHERE @blk IS NOT NULL AND EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 360, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current.</p><p>The previous site described a 25-year concession covering design, construction, finance, operation, maintenance and transfer. It listed the ownership as SRBG 60%, Shamim Enterprise 30% and UDC Construction 10%.</p><p>It identified China Development Bank and BIFFL as lenders and described financing agreements signed in April 2021. The current concession terms and ownership should be checked with DBEDC.</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>The Dhaka Bypass Expressway is delivered as a public–private partnership. A government contracting authority owns the corridor and sets the terms; DBEDC, as the concession company, finances, builds, operates and maintains it for a fixed term, recovers its investment through tolls, and returns the asset at the end.</p><p>That structure decides everything a road user experiences: who sets the toll, who is accountable for the road surface, and who answers a complaint.</p><p>The public partner is the Roads and Highways Department. The private consortium comprises Sichuan Road and Bridge (Group) Corporation Ltd, Shamim Enterprise (Pvt) Ltd and UDC Construction Ltd. <a href=\\"https://www.pppo.gov.bd/projects-dhaka-bypass.php\\">Source: PPPA</a>.</p>","heading":"The contractual structure"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 360, 'bn', '{"tone":"legacy","heading":"","body":"<p>আগের ওয়েবসাইট থেকে সংরক্ষিত তথ্য। এগুলি পরিবর্তিত হয়ে থাকতে পারে এবং বর্তমান তথ্য হিসেবে নিশ্চিত নয়।</p><p>আগের সাইটে নকশা, নির্মাণ, অর্থায়ন, পরিচালনা, রক্ষণাবেক্ষণ ও হস্তান্তরসহ ২৫ বছরের কনসেশনের কথা ছিল। সেখানে মালিকানা হিসেবে SRBG ৬০%, Shamim Enterprise ৩০% এবং UDC Construction ১০% উল্লেখ করা হয়েছিল।</p><p>ঋণদাতা হিসেবে China Development Bank ও BIFFL এবং এপ্রিল ২০২১-এ অর্থায়ন চুক্তির উল্লেখ ছিল। বর্তমান চুক্তির শর্ত ও মালিকানা DBEDC-এর কাছে যাচাই করুন।</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'bn' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>Dhaka Bypass Expressway সরকারি-বেসরকারি অংশীদারিত্বের (PPP) আওতায় বাস্তবায়িত হচ্ছে। সরকারি চুক্তিকারী কর্তৃপক্ষ করিডোরের মালিক এবং শর্ত নির্ধারণ করে; কনসেশন কোম্পানি হিসেবে DBEDC নির্দিষ্ট মেয়াদের জন্য অর্থায়ন, নির্মাণ, পরিচালনা ও রক্ষণাবেক্ষণ করে, টোলের মাধ্যমে বিনিয়োগ ফিরে পায় এবং মেয়াদ শেষে সম্পদ ফিরিয়ে দেয়।</p><p>সড়ক ব্যবহারকারী যা কিছু অনুভব করেন তার সবই এই কাঠামো নির্ধারণ করে — কে টোল নির্ধারণ করে, সড়কের পৃষ্ঠের জন্য কে দায়ী, এবং অভিযোগের জবাব কে দেয়।</p><p>সরকারি অংশীদার সড়ক ও জনপথ অধিদপ্তর। বেসরকারি কনসোর্টিয়ামে রয়েছে Sichuan Road and Bridge (Group) Corporation Ltd, Shamim Enterprise (Pvt) Ltd এবং UDC Construction Ltd। <a href=\\"https://www.pppo.gov.bd/projects-dhaka-bypass.php\\">সূত্র: PPPA</a>।</p>","heading":"চুক্তিগত কাঠামো"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 360, 'zh', '{"tone":"legacy","heading":"","body":"<p>以下内容恢复自旧版网站，可能已有变化，尚未确认为当前信息。</p><p>旧版网站描述了涵盖设计、建设、融资、运营、养护及移交的 25 年特许经营期，并列出 SRBG 持股 60%、Shamim Enterprise 持股 30%、UDC Construction 持股 10%。</p><p>旧资料将 China Development Bank 和 BIFFL 列为贷款方，并提及 2021 年 4 月签署的融资协议。当前经营条款与持股情况请向 DBEDC 核实。</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'zh' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>Dhaka Bypass Expressway 采用政府与社会资本合作（PPP）模式实施。政府签约机构拥有该走廊并确定各项条件；DBEDC 作为特许经营公司，在约定期限内负责融资、建设、运营与养护，通过收取通行费回收投资，期满后移交资产。</p><p>道路使用者所感受到的一切都由这一架构决定：由谁制定收费标准、由谁对路面状况负责、以及由谁答复投诉。</p><p>公共合作方为公路局（RHD），私人联合体由 Sichuan Road and Bridge (Group) Corporation Ltd、Shamim Enterprise (Pvt) Ltd 和 UDC Construction Ltd 组成。<a href=\\"https://www.pppo.gov.bd/projects-dhaka-bypass.php\\">来源：PPPA</a>。</p>","heading":"合同架构"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';

-- /about/governance sort 3 (source block 18): legacy
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'about/governance' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'the previous website; this is an archived roster, not a current staff directory.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current.</p><ul><li>Liu Xiaobo — Chairman</li><li>Xiao Zhiming — Chief Executive Officer</li><li>Md. Shafiqul Islam Akand — Chief Operating Officer</li><li>Syed Aslam Ali — RHD Project Director</li></ul><p>Names and titles are reproduced as listed on the previous website; this is an archived roster, not a current staff directory.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>আগের ওয়েবসাইট থেকে সংরক্ষিত তথ্য। এগুলি পরিবর্তিত হয়ে থাকতে পারে এবং বর্তমান তথ্য হিসেবে নিশ্চিত নয়।</p><ul><li>Liu Xiaobo — চেয়ারম্যান</li><li>Xiao Zhiming — প্রধান নির্বাহী কর্মকর্তা</li><li>Md. Shafiqul Islam Akand — প্রধান পরিচালন কর্মকর্তা</li><li>Syed Aslam Ali — RHD প্রকল্প পরিচালক</li></ul><p>নাম ও পদবি আগের ওয়েবসাইট অনুযায়ী সংরক্ষিত। এটি পুরোনো তালিকা, বর্তমান কর্মকর্তা তালিকা নয়।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>以下内容恢复自旧版网站，可能已有变化，尚未确认为当前信息。</p><ul><li>Liu Xiaobo — 董事长</li><li>Xiao Zhiming — 首席执行官</li><li>Md. Shafiqul Islam Akand — 首席运营官</li><li>Syed Aslam Ali — RHD 项目主任</li></ul><p>姓名与职务按旧版网站保留，属于历史名单，并非现任人员名录。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /project sort 4 (source block 24): prose,legacy
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'project' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'he remaining road is open. Use the route map for the published operating status.') > 0
    ORDER BY b.`id` LIMIT 1);
SET @sort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @blk);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 361, (SELECT `id` FROM `pages` WHERE `slug` = 'project' LIMIT 1), 'callout', @sort, NULL, 'published' FROM DUAL
  WHERE @blk IS NOT NULL AND EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 361, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current.</p><p><strong>Construction snapshot dated 31 December 2024:</strong> the previous project page reported overall progress of 69.11%, earthworks at 82.89%, pavement at 53.95%, foundations at 100% and structures at 90.9%.</p><p>It described an initial project investment of US$412 million and an appointed date of 15 May 2022. These are figures reported by the previous site, not an updated financial statement.</p><p>The old July 2025 and December 2025 opening targets are historical targets that have passed. They do not indicate that the remaining road is open. Use the route map for the published operating status.</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>Project history: the PPP contract was signed on 6 December 2018. BIFFL reports that its first loan disbursement to the project was made in April 2022. These are historical milestones, separate from the road’s current operating status. <a href=\\"https://www.pppo.gov.bd/projects-dhaka-bypass.php\\">PPPA project profile</a>; <a href=\\"https://www.biffl.org.bd/uploads/images/reports/BIFFL%20Annual%20Report%202022%20Final%20Update.pdf\\">BIFFL annual report 2022, page 88</a>.</p>","heading":"Programme and cost"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 361, 'bn', '{"tone":"legacy","heading":"","body":"<p>আগের ওয়েবসাইট থেকে সংরক্ষিত তথ্য। এগুলি পরিবর্তিত হয়ে থাকতে পারে এবং বর্তমান তথ্য হিসেবে নিশ্চিত নয়।</p><p><strong>৩১ ডিসেম্বর ২০২৪-এর নির্মাণ চিত্র:</strong> আগের প্রকল্প পাতায় সার্বিক অগ্রগতি ৬৯.১১%, মাটির কাজ ৮২.৮৯%, পেভমেন্ট ৫৩.৯৫%, ভিত্তি ১০০% ও অবকাঠামো ৯০.৯% বলা হয়েছিল।</p><p>প্রাথমিক প্রকল্প বিনিয়োগ ৪১২ মিলিয়ন মার্কিন ডলার এবং নির্ধারিত সূচনার তারিখ ১৫ মে ২০২২ উল্লেখ ছিল। এগুলি আগের সাইটের তথ্য, হালনাগাদ আর্থিক বিবরণী নয়।</p><p>জুলাই ও ডিসেম্বর ২০২৫-এর পুরোনো উদ্বোধনের লক্ষ্য ইতোমধ্যে পেরিয়ে গেছে। এগুলি অবশিষ্ট সড়ক খোলা থাকার প্রমাণ নয়। প্রকাশিত পরিচালনার অবস্থা রুট মানচিত্রে দেখুন।</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'bn' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>প্রকল্পের ইতিহাস: ৬ ডিসেম্বর ২০১৮ PPP চুক্তি স্বাক্ষরিত হয়। BIFFL-এর প্রতিবেদন অনুযায়ী প্রকল্পে তাদের প্রথম ঋণ বিতরণ হয় এপ্রিল ২০২২-এ। এগুলি ঐতিহাসিক মাইলফলক, বর্তমান সড়ক পরিচালনার অবস্থা নয়। <a href=\\"https://www.pppo.gov.bd/projects-dhaka-bypass.php\\">PPPA প্রকল্প পরিচিতি</a>; <a href=\\"https://www.biffl.org.bd/uploads/images/reports/BIFFL%20Annual%20Report%202022%20Final%20Update.pdf\\">BIFFL বার্ষিক প্রতিবেদন ২০২২, পৃষ্ঠা ৮৮</a>।</p>","heading":"কর্মসূচি ও ব্যয়"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 361, 'zh', '{"tone":"legacy","heading":"","body":"<p>以下内容恢复自旧版网站，可能已有变化，尚未确认为当前信息。</p><p><strong>截至 2024 年 12 月 31 日的施工记录：</strong>旧项目页面报告总体进度为 69.11%，土方 82.89%，路面 53.95%，基础 100%，结构 90.9%。</p><p>旧网站还提及初始项目投资 4.12 亿美元，约定开工日期为 2022 年 5 月 15 日。这些是旧网站所述数据，并非最新财务报表。</p><p>原定 2025 年 7 月及 12 月的开放目标日期已经过去，不能据此认定剩余路段已开放。已公布的运营状态请查看路线地图。</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'zh' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>项目历程：PPP 合同于 2018 年 12 月 6 日签署。BIFFL 报告称，首次向项目发放贷款是在 2022 年 4 月。这些属于历史里程碑，并非道路当前运营状态。<a href=\\"https://www.pppo.gov.bd/projects-dhaka-bypass.php\\">PPPA 项目资料</a>；<a href=\\"https://www.biffl.org.bd/uploads/images/reports/BIFFL%20Annual%20Report%202022%20Final%20Update.pdf\\">BIFFL 2022 年报，第 88 页</a>。</p>","heading":"工期与投资"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';

-- /safety sort 3 (source block 28): prose,legacy
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'safety' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'ency service in an emergency. The website contact form is for general enquiries.') > 0
    ORDER BY b.`id` LIMIT 1);
SET @sort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @blk);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 362, (SELECT `id` FROM `pages` WHERE `slug` = 'safety' LIMIT 1), 'callout', @sort, NULL, 'published' FROM DUAL
  WHERE @blk IS NOT NULL AND EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 362, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current.</p><p>The previous site described emergency call points, ambulance and towing support. Their present availability and a dedicated expressway number have not been verified. Follow roadside instructions and contact the national emergency service in an emergency. The website contact form is for general enquiries.</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>Move the vehicle as far left as you safely can, switch on hazard lights, and get every passenger out on the side away from traffic and behind a barrier where one exists. Do not attempt a repair in a running lane, and do not cross the carriageway on foot.</p>","heading":"If you break down"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 362, 'bn', '{"tone":"legacy","heading":"","body":"<p>আগের ওয়েবসাইট থেকে সংরক্ষিত তথ্য। এগুলি পরিবর্তিত হয়ে থাকতে পারে এবং বর্তমান তথ্য হিসেবে নিশ্চিত নয়।</p><p>আগের সাইটে জরুরি কল পয়েন্ট, অ্যাম্বুলেন্স ও টোয়িং সহায়তার উল্লেখ ছিল। বর্তমানে এসব সেবার প্রাপ্যতা ও এক্সপ্রেসওয়ের নির্দিষ্ট নম্বর যাচাই করা হয়নি। সড়কের নির্দেশনা অনুসরণ করুন এবং জরুরি অবস্থায় জাতীয় জরুরি সেবায় যোগাযোগ করুন। ওয়েবসাইটের ফরম সাধারণ অনুসন্ধানের জন্য।</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'bn' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>নিরাপদে যতটা সম্ভব বাঁ দিকে যানবাহনটি সরিয়ে নিন, হ্যাজার্ড লাইট জ্বালান, এবং সব যাত্রীকে যান চলাচলের বিপরীত পাশ দিয়ে নামিয়ে ব্যারিয়ার থাকলে তার পিছনে নিয়ে যান। চলমান লেনে মেরামতের চেষ্টা করবেন না এবং পায়ে হেঁটে ক্যারিজওয়ে পার হবেন না।</p>","heading":"যানবাহন বিকল হলে"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 362, 'zh', '{"tone":"legacy","heading":"","body":"<p>以下内容恢复自旧版网站，可能已有变化，尚未确认为当前信息。</p><p>旧网站曾介绍紧急呼叫点、救护车及拖车支持。这些服务目前是否提供及快速路专用号码尚未核实。请遵循路边指示，紧急时联系国家紧急服务。网站联系表单用于一般咨询。</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'zh' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%');
UPDATE `block_translations` SET `data` = '{"body":"<p>在确保安全的前提下尽量将车辆靠左停放，开启危险报警闪光灯，并让所有乘员从背离车流的一侧下车，如有护栏应转移至护栏之后。切勿在行车道内尝试修车，也不要步行横穿路面。</p>","heading":"车辆故障时"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';

-- /sustainability sort 2 (source block 31): legacy
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'sustainability' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'onitoring report for download. Request those documents through the contact form.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current.</p><p>The previous website described school support, community visits, pandemic relief supplies, staff training and construction quality-control activities. The gallery preserves project photographs of construction work, a school plaque presentation and joint project ceremonies.</p><p>The archived folder contains no public environmental assessment, management plan or monitoring report for download. Request those documents through the contact form.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>আগের ওয়েবসাইট থেকে সংরক্ষিত তথ্য। এগুলি পরিবর্তিত হয়ে থাকতে পারে এবং বর্তমান তথ্য হিসেবে নিশ্চিত নয়।</p><p>আগের সাইটে বিদ্যালয়ে সহায়তা, কমিউনিটি পরিদর্শন, মহামারির সময় ত্রাণসামগ্রী, কর্মীদের প্রশিক্ষণ ও নির্মাণের মান নিয়ন্ত্রণের বর্ণনা ছিল। গ্যালারিতে নির্মাণকাজ, বিদ্যালয়ে স্মারক প্রদান ও যৌথ প্রকল্প অনুষ্ঠানের ছবি সংরক্ষিত রয়েছে।</p><p>পুরোনো ফোল্ডারে ডাউনলোডযোগ্য প্রকাশ্য পরিবেশ মূল্যায়ন, ব্যবস্থাপনা পরিকল্পনা বা পর্যবেক্ষণ প্রতিবেদন নেই। নথির জন্য যোগাযোগ ফরম ব্যবহার করুন।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>以下内容恢复自旧版网站，可能已有变化，尚未确认为当前信息。</p><p>旧网站介绍了学校支持、社区走访、疫情物资援助、员工培训与施工质量管理。图库保留了施工、学校牌匾交接及联合项目活动的照片。</p><p>归档文件夹中没有可下载的公开环境评估、管理计划或监测报告。请通过联系表单申请这些文件。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /procurement sort 3 (source block 36): pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'procurement' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'ng confirmation. Use the general contact form for supplier and tender enquiries.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>Supplier registration requirements and a dedicated procurement contact are awaiting confirmation. Use the general contact form for supplier and tender enquiries.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>সরবরাহকারী নিবন্ধনের শর্ত ও ক্রয়সংক্রান্ত নির্দিষ্ট যোগাযোগ নিশ্চিতকরণের অপেক্ষায় রয়েছে। সরবরাহকারী ও দরপত্রের অনুসন্ধানে সাধারণ যোগাযোগ ফরম ব্যবহার করুন।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>供应商注册要求及采购专用联系方式尚待确认。供应商和招标咨询请使用一般联系表单。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /disclosures/land-acquisition sort 2 (source block 42): pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'disclosures/land-acquisition' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 't assistance. Use the contact form to request information about a specific case.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>The public land acquisition and compensation record is awaiting publication, including affected areas and resettlement assistance. Use the contact form to request information about a specific case.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>ক্ষতিগ্রস্ত এলাকা ও পুনর্বাসন সহায়তাসহ ভূমি অধিগ্রহণ এবং ক্ষতিপূরণের প্রকাশ্য নথি প্রকাশের অপেক্ষায় রয়েছে। নির্দিষ্ট বিষয়ে তথ্যের জন্য যোগাযোগ ফরম ব্যবহার করুন।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>土地征收与补偿的公开记录尚待公布，包括受影响区域及安置援助。查询具体事项，请使用联系表单。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /disclosures/tariff sort 2 (source block 46): pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'disclosures/tariff' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'ublication. Confirmed rates for the open section are available on the toll page.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>The tariff notification reference, issue date and original document are awaiting publication. Confirmed rates for the open section are available on the toll page.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>টোল প্রজ্ঞাপনের সূত্র নম্বর, প্রকাশের তারিখ ও মূল নথি প্রকাশের অপেক্ষায় রয়েছে। খোলা অংশের নিশ্চিত হার টোল পাতায় পাওয়া যাবে।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>收费通知的编号、发布日期及原件尚待公布。已开放路段的确认费率可在收费页面查看。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /grievances sort 3 (source block 51): legacy
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'grievances' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'iry using the contact form on this site while the dedicated details are updated.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current.</p><p>The previous website used info@dbedc.com for general enquiries. It did not publish a dedicated grievance officer, response deadline or escalation process. You can submit an enquiry using the contact form on this site while the dedicated details are updated.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>আগের ওয়েবসাইট থেকে সংরক্ষিত তথ্য। এগুলি পরিবর্তিত হয়ে থাকতে পারে এবং বর্তমান তথ্য হিসেবে নিশ্চিত নয়।</p><p>আগের সাইটে সাধারণ অনুসন্ধানের জন্য info@dbedc.com ব্যবহার করা হতো। নির্দিষ্ট অভিযোগ কর্মকর্তা, উত্তরের সময়সীমা বা পরবর্তী ধাপ প্রকাশিত ছিল না। নির্দিষ্ট তথ্য হালনাগাদের সময় এই সাইটের যোগাযোগ ফরম ব্যবহার করতে পারেন।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `block_translations` SET `data` = '{"tone":"legacy","heading":"","body":"<p>以下内容恢复自旧版网站，可能已有变化，尚未确认为当前信息。</p><p>旧网站将 info@dbedc.com 用于一般咨询，未列出专门投诉负责人、回复时限或升级处理流程。在专用信息更新期间，可使用本网站的联系表单提交咨询。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-archive%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /travel/rules sort 2 (source block 302): pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'travel/rules' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'ly on — the posted limit governs and may be lower. Follow the signs on the road.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>The posted speed limits for the toll carriageways and for the service roads have not been supplied by DBEDC for publication. The corridor was designed to an 80 km/h standard, but a design speed is the engineering basis for the geometry and is not a limit a driver may rely on — the posted limit governs and may be lower. Follow the signs on the road.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>টোল ক্যারেজওয়ে ও সার্ভিস রোডের নির্ধারিত গতিসীমা DBEDC এখনও প্রকাশের জন্য সরবরাহ করেনি। করিডোরটি ৮০ কিমি/ঘণ্টা মানে নকশা করা হয়েছে, তবে ডিজাইন স্পিড হল জ্যামিতির প্রকৌশলগত ভিত্তি — এটি চালকের জন্য নির্ভরযোগ্য গতিসীমা নয়; সড়কে প্রদর্শিত সীমাই প্রযোজ্য এবং তা কম হতে পারে। সড়কের সাইনবোর্ড অনুসরণ করুন।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>收费行车道与辅路的公布限速尚未由 DBEDC 提供发布。该走廊按 80 公里/小时标准设计，但设计速度是道路几何的工程依据，并非驾驶人可依据的限速——以路侧标志公布的限速为准，且可能更低。请遵守道路标志。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /travel/rules sort 3 (source block 303): pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'travel/rules' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), ' roadside. Until they are published here, use the national emergency number 999.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>DBEDC has not yet supplied the rules for stopping on the expressway, the arrangements for breakdown recovery and patrolling, or the numbers to call from the roadside. Until they are published here, use the national emergency number 999.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>এক্সপ্রেসওয়েতে থামার নিয়ম, বিকল যান উদ্ধার ও টহলের ব্যবস্থা, কিংবা সড়ক থেকে কোন নম্বরে ফোন করতে হবে — DBEDC এখনও তা সরবরাহ করেনি। এখানে প্রকাশিত না হওয়া পর্যন্ত জাতীয় জরুরি নম্বর ৯৯৯ ব্যবহার করুন।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>DBEDC 尚未提供高速公路上的停车规定、故障救援与巡逻安排，也未提供路侧求助电话。在此处公布之前，请拨打国家紧急电话 999。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /travel/rules sort 4 (source block 304): pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'travel/rules' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'the toll plaza lanes are allocated — have not yet been supplied for publication.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>The lane rules for this corridor — which lane heavy vehicles must keep to, where overtaking is restricted, and how the toll plaza lanes are allocated — have not yet been supplied for publication.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>এই করিডোরের লেন সংক্রান্ত নিয়ম — ভারী যানবাহনকে কোন লেনে চলতে হবে, কোথায় ওভারটেকিং সীমাবদ্ধ, এবং টোল প্লাজার লেন কীভাবে বরাদ্দ হয় — এখনও প্রকাশের জন্য সরবরাহ করা হয়নি।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>本走廊的车道规定——重型车辆应行驶的车道、限制超车的路段，以及收费广场车道的分配方式——尚未提供发布。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /privacy sort 1 (source block 311): pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'privacy' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'shed here, write using the contact form and ask for the data protection contact.') > 0
    ORDER BY b.`id` LIMIT 1);
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>The registered identity and address of the data controller, how long messages and subscriptions are kept, how to ask for a copy of what is held about you or to have it deleted, and the law under which these rights are exercised, have not yet been settled with DBEDC and its legal advisers. Until they are published here, write using the contact form and ask for the data protection contact.</p>"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>ডেটা নিয়ন্ত্রকের নিবন্ধিত পরিচয় ও ঠিকানা, বার্তা ও সাবস্ক্রিপশন কত দিন সংরক্ষিত থাকে, আপনার সম্পর্কে রক্ষিত তথ্যের অনুলিপি চাওয়া বা তা মুছে ফেলার অনুরোধের পদ্ধতি, এবং কোন আইনের অধীনে এসব অধিকার প্রযোজ্য — এগুলি DBEDC ও তার আইন উপদেষ্টাদের সঙ্গে এখনও চূড়ান্ত হয়নি। এখানে প্রকাশিত না হওয়া পর্যন্ত যোগাযোগ ফরম ব্যবহার করে ডেটা সুরক্ষা সংক্রান্ত যোগাযোগের ঠিকানা জানতে চান।</p>"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `block_translations` SET `data` = '{"tone":"pending","heading":"","body":"<p>数据控制者的登记名称与地址、留言与订阅信息的保存期限、如何索取或删除我们持有的您的信息，以及这些权利所依据的法律，尚未与 DBEDC 及其法律顾问确定。在此处公布之前，请通过联系表单索取数据保护联系人。</p>"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
UPDATE `blocks` SET `type` = 'callout' WHERE `id` = @blk AND `type` = 'rich-text'
  AND NOT EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND JSON_EXTRACT(`data`, '$.tone') IS NULL);

-- /privacy sort 2 (source block 312): prose,pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'privacy' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'tion that processes data on DBEDC&rsquo;s behalf, have not yet been listed here.') > 0
    ORDER BY b.`id` LIMIT 1);
SET @sort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @blk);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 363, (SELECT `id` FROM `pages` WHERE `slug` = 'privacy' LIMIT 1), 'callout', @sort, NULL, 'published' FROM DUAL
  WHERE @blk IS NOT NULL AND EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 363, 'en', '{"tone":"pending","heading":"","body":"<p>The hosting arrangements for this site, and any other organisation that processes data on DBEDC&rsquo;s behalf, have not yet been listed here.</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
UPDATE `block_translations` SET `data` = '{"body":"<p>If you accept analytics, Google receives the usage data that Google Analytics collects, under Google&rsquo;s own terms.</p>","heading":"Who else sees this data"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 363, 'bn', '{"tone":"pending","heading":"","body":"<p>এই সাইটের হোস্টিং ব্যবস্থা এবং DBEDC-এর পক্ষে তথ্য প্রক্রিয়াকারী অন্য কোনও প্রতিষ্ঠানের তালিকা এখনও এখানে দেওয়া হয়নি।</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'bn' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
UPDATE `block_translations` SET `data` = '{"body":"<p>আপনি অ্যানালিটিক্সে সম্মতি দিলে Google Analytics-এর সংগৃহীত ব্যবহারের তথ্য Google তাদের নিজস্ব শর্তাবলি অনুযায়ী পায়।</p>","heading":"এই তথ্য আর কারা দেখে"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 363, 'zh', '{"tone":"pending","heading":"","body":"<p>本站的托管安排，以及代表 DBEDC 处理数据的其他机构，尚未在此列出。</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'zh' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
UPDATE `block_translations` SET `data` = '{"body":"<p>若您接受分析统计，Google 将按其自身条款获取 Google Analytics 所收集的使用数据。</p>","heading":"还有谁能看到这些数据"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';

-- /terms sort 0 (source block 313): prose,pending
SET @blk = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id`
    JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
    WHERE p.`slug` = 'terms' AND b.`type` = 'rich-text'
      AND INSTR(JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')), 'putes are handled — have not yet been settled with DBEDC and its legal advisers.') > 0
    ORDER BY b.`id` LIMIT 1);
SET @sort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @blk);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 364, (SELECT `id` FROM `pages` WHERE `slug` = 'terms' LIMIT 1), 'callout', @sort, NULL, 'published' FROM DUAL
  WHERE @blk IS NOT NULL AND EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 364, 'en', '{"tone":"pending","heading":"","body":"<p>The formal terms of use — the limits of liability, the rules for reusing text and photographs from this site, and how disputes are handled — have not yet been settled with DBEDC and its legal advisers.</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'en' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
UPDATE `block_translations` SET `data` = '{"body":"<p>This website is published by Dhaka Bypass Expressway Development Company. Information about tolls, open sections and traffic conditions is published in good faith and may change; the signs and instructions on the road itself always take precedence over anything shown here.</p>","heading":"Terms of use"}' WHERE `block_id` = @blk AND `locale` = 'en'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 364, 'bn', '{"tone":"pending","heading":"","body":"<p>আনুষ্ঠানিক ব্যবহারের শর্তাবলি — দায়ের সীমা, এই সাইটের লেখা ও ছবি পুনর্ব্যবহারের নিয়ম, এবং বিরোধ নিষ্পত্তির পদ্ধতি — DBEDC ও তার আইন উপদেষ্টাদের সঙ্গে এখনও চূড়ান্ত হয়নি।</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'bn' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
UPDATE `block_translations` SET `data` = '{"body":"<p>এই ওয়েবসাইটটি প্রকাশ করে ঢাকা বাইপাস এক্সপ্রেসওয়ে ডেভেলপমেন্ট কোম্পানি। টোল, চালু অংশ ও যান চলাচলের অবস্থা সম্পর্কিত তথ্য সরল বিশ্বাসে প্রকাশ করা হয় এবং তা পরিবর্তিত হতে পারে; সড়কে প্রদর্শিত সাইনবোর্ড ও নির্দেশনা সর্বদা এখানে দেখানো যেকোনও তথ্যের চেয়ে অগ্রাধিকার পাবে।</p>","heading":"ব্যবহারের শর্তাবলি"}' WHERE `block_id` = @blk AND `locale` = 'bn'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 364, 'zh', '{"tone":"pending","heading":"","body":"<p>正式使用条款——责任范围、转载本站文字与图片的规则，以及争议处理方式——尚未与 DBEDC 及其法律顾问确定。</p>"}', 'published' FROM DUAL
  WHERE EXISTS (SELECT 1 FROM `block_translations` WHERE `block_id` = @blk AND `locale` = 'zh' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%');
UPDATE `block_translations` SET `data` = '{"body":"<p>本网站由达卡绕城高速公路发展公司发布。有关通行费、通车路段与路况的信息均本着诚信发布，且可能变动；道路现场的标志与指示始终优先于本站所示内容。</p>","heading":"使用条款"}' WHERE `block_id` = @blk AND `locale` = 'zh'
  AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.body')) LIKE '%db-pending%';
