-- 24-legacy-content.sql — the previous website's structured facts, as blocks (W2.2–W2.7).
--
-- GENERATED by scripts/generate-legacy-content.mjs; regenerate, do not edit.
--
-- The old site's project timeline, the December 2024 progress figures, the
-- specification tiles, the partners and their financing, the Chinese
-- contribution, the economic-impact figures, the key locations, facilities
-- and full-corridor tolls, placed on the pages that replaced those routes.
-- English only, as the source was; bn and zh fall back to English with the
-- site's "shown in English" notice. Every group opens with a `callout` of
-- tone `legacy` — the standard "recovered from the previous website, not
-- confirmed as current" provenance — so nothing here reads as verified.
--
-- Pages are resolved by SLUG. New blocks take the sort_order of the block
-- they follow, with higher ids, so they render after it and before the next
-- (order is sort_order, id); the editor renumbers on the next drag.
-- Idempotent: INSERT IGNORE. ID map: blocks 400+.


-- /project: 10 blocks after sort_order 4
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'project' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 400, @p, 'callout', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 400, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. The figures in this section were last updated on the previous website on 31 December 2024.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 401, @p, 'timeline', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 401, 'en', '{"heading":"Project timeline as previously published","intro":"","items":[{"date":"December 2018","datetime":"2018-12-06","title":"PPP contract signed","description":"<p>The PPP contract was signed between the Roads and Highways Department and DBEDC.</p>","image":"","progress":0},{"date":"November 2020","datetime":"2020-11-01","title":"Construction begins","description":"<p>Initial construction works commenced, with final construction officially starting in May 2022 after the Appointed Date was established.</p>","image":"","progress":0},{"date":"15 May 2022","datetime":"2022-05-15","title":"Appointed Date","description":"<p>Established as the official Appointed Date, marking the formal commencement of the construction period.</p>","image":"","progress":0},{"date":"March 2025","datetime":"2025-03-27","title":"First section opening","description":"<p>The section from K4 to K22 was put into trial operation during the Eid-ul-Fitr period from 27 March to 5 April 2025.</p>","image":"","progress":0},{"date":"December 2025 (target)","datetime":"2025-12-01","title":"Second section opening","description":"<p>The section from K22 to K35, including service roads, was targeted to open by December 2025.</p>","image":"","progress":0}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 402, @p, 'rich-text', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 402, 'en', '{"heading":"Progress by category, 31 December 2024","body":"<p>Overall progress was reported as 69.11%. The breakdown below is as the previous website published it.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 403, @p, 'stat-row', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 403, 'en', '{"stats":[{"value":"93.9","unit":"%","label":"General"},{"value":"82.89","unit":"%","label":"Earthwork"},{"value":"53.95","unit":"%","label":"Pavement"},{"value":"100","unit":"%","label":"Foundation"},{"value":"90.9","unit":"%","label":"Structure"},{"value":"54.21","unit":"%","label":"Incidental"}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 404, @p, 'card-grid', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 404, 'en', '{"heading":"Key achievements as previously published","intro":"Reported at 31 December 2024.","items":[{"title":"Completed foundations","meta":"Foundation","body":"All foundation work has been completed (100%)."},{"title":"Major structures","meta":"Structure","body":"Structural work at 90.9% completion, including the Ulukhula, Nagda, Mirer Bazar and Dhirasram overpasses."},{"title":"Road construction","meta":"Earthwork","body":"Over 31.76 km of embankment fill for the toll road and 40.44 km for service roads completed."},{"title":"Pavement layers","meta":"Pavement","body":"Approximately 22 km of asphalt layers (AC-20 and AC-13) completed for toll roads and 28 km for service roads."},{"title":"Box culverts","meta":"Structure","body":"62 of 73 planned box culverts completed."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 405, @p, 'card-grid', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 405, 'en', '{"heading":"Specifications as previously published","intro":"","items":[{"title":"48.07 km","meta":"Length","body":"Total expressway length from Joydebpur to Madanpur."},{"title":"4 lanes","meta":"Main carriageway","body":"9.7 m width (7.3 m plus a 2.4 m shoulder), design speed 80 km/h."},{"title":"2 lanes","meta":"Service roads","body":"5.8 m width (7.3 m every 5 km in the RAJUK section), design speed 50 km/h."},{"title":"6","meta":"Toll plazas","body":"Placed along the expressway."},{"title":"100+","meta":"Major structures","body":"Including 5 river bridges, 3 minor bridges, 4 flyovers, 45 underpasses and 87 culverts."},{"title":"25 years","meta":"Contract period","body":"Design, Build, Finance, Operate, Maintain, Transfer (DBFOMT)."},{"title":"US$412 million","meta":"Investment","body":"Total initial project investment."},{"title":"12 · 7 · 27","meta":"Bridges · flyovers · underpasses","body":"As listed on the previous project overview; the structures count above lists them differently. Neither is confirmed."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 406, @p, 'card-grid', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 406, 'en', '{"heading":"Project objectives as previously published","intro":"","items":[{"title":"An efficient corridor around Dhaka","meta":"1","body":"Create an efficient transportation corridor around the capital."},{"title":"Less congestion in the capital","meta":"2","body":"Reduce traffic congestion in Dhaka."},{"title":"Four national highways connected","meta":"3","body":"Connect N1, N2, N3 and N4."},{"title":"Better logistics","meta":"4","body":"Enhance logistics and supply-chain efficiency."},{"title":"Development along the route","meta":"5","body":"Promote economic development in adjoining areas."},{"title":"Modern expressway standards","meta":"6","body":"Introduce modern expressway standards to Bangladesh."},{"title":"Lower travel time and cost","meta":"7","body":"Reduce travel time and transportation costs."},{"title":"Safer roads","meta":"8","body":"Improve road safety with controlled access."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 407, @p, 'media-prose', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 407, 'en', '{"image":"/semi.webp","side":"right","heading":"Semi-rigid pavement","body":"<p>A hybrid pavement system combining flexibility and durability, introduced to Bangladesh on this project.</p><p><strong>Technical advantages</strong></p><ul><li>High load-bearing capacity for heavy commercial vehicles</li><li>Enhanced durability compared to conventional asphalt pavements</li><li>Better resistance to rutting and deformation under tropical conditions</li><li>Reduced maintenance requirements over the project lifecycle</li></ul><p><strong>Construction process</strong></p><ul><li>Precision thickness control using advanced equipment</li><li>Specialised curing techniques to prevent premature cracking</li><li>Continuous quality monitoring during construction</li><li>Computerised mix design for optimal performance</li></ul>","caption":"","linkLabel":"","linkHref":""}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 408, @p, 'media-prose', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 408, 'en', '{"image":"/cp.webp","side":"left","heading":"Technology benefits as previously published","body":"<ul><li><strong>Extended lifespan</strong> — 30+ years of service life compared to 15–20 years for conventional pavements</li><li><strong>Cost efficiency</strong> — higher initial investment but significantly lower lifecycle maintenance costs</li><li><strong>Weather resistance</strong> — superior performance during monsoon seasons and extreme temperature variations</li></ul>","caption":"","linkLabel":"","linkHref":""}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 409, @p, 'rich-text', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 409, 'en', '{"heading":"Vision and mission as previously published","body":"<p><strong>Vision.</strong> To transform Bangladesh’s transportation infrastructure by creating a world-class expressway that serves as a model for future development projects, enhancing connectivity and supporting economic growth.</p><p><strong>Mission.</strong> To deliver a transformative expressway that sets new standards for safety, efficiency and sustainability in Bangladesh’s transportation network — implementing innovative engineering solutions, fostering knowledge transfer and capacity building, and creating opportunities for economic development along the corridor.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;

-- /about/governance: 5 blocks after sort_order 2
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'about/governance' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 410, @p, 'callout', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 410, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. The partner descriptions, links and financing figures below are as the previous website published them.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 411, @p, 'stat-row', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 411, 'en', '{"stats":[{"value":"1st","unit":"","label":"Road PPP in Bangladesh"},{"value":"7","unit":"","label":"Organisations in partnership"},{"value":"25","unit":"years","label":"Concession — design, build, finance, operate, maintain, transfer"}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 412, @p, 'card-grid', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 412, 'en', '{"heading":"Partners as previously published","intro":"","items":[{"title":"Sichuan Road & Bridge Group (SRBG)","meta":"Lead investor and contractor","body":"Lead private investor with a 60% equity stake; main EPC contractor; introduced semi-rigid pavement and reinforced retaining walls. Member of Shudao Investment Group (SDIG). Employs over 1,000 local workers."},{"title":"Shamim Enterprise Ltd (SEL)","meta":"Local partner, 30%","body":"Major local private partner providing local knowledge, construction expertise, regulatory compliance and local supply chains."},{"title":"UDC Construction Ltd","meta":"Local partner, 10%","body":"Second Bangladeshi partner, providing additional local construction capacity and stakeholder coordination. The two local partners together hold 40%."},{"title":"Public-Private Partnership Authority (PPPA)","meta":"PPP facilitator","body":"Approved the project in principle in 2012 and helped structure the PPP agreement through to contract signing in December 2018. Operates under the Prime Minister’s Office."},{"title":"Roads and Highways Department (RHD)","meta":"Contracting authority","body":"Public-sector client and concession grantor; provides land acquisition and resettlement and contributes viability gap funding. Receives the asset back after the 25-year concession."},{"title":"China Development Bank (CDB)","meta":"Major foreign lender","body":"Extended a ৳1,614 crore loan to DBEDC under a financing agreement signed in April 2021, completing the US$412 million financing package."},{"title":"Bangladesh Infrastructure Finance Fund Ltd (BIFFL)","meta":"Domestic lender","body":"State-owned infrastructure financier; loan facility of ৳1,075 crore to DBEDC, with a first instalment of ৳42.5 crore disbursed in April 2022, under a 2020 ADB-backed credit line."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 413, @p, 'rich-text', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 413, 'en', '{"heading":"Financing as previously published","body":"<p>Viability gap funding from the Government of Bangladesh was initially ৳224 crore and later revised to ৳674 crore. China Development Bank lent ৳1,614 crore (agreement signed April 2021); BIFFL lent ৳1,075 crore, with a first instalment of ৳42.5 crore disbursed in April 2022. The total package was described as US$412 million (about ৳3,585–3,723 crore).</p><p>Partner websites as listed: <a href=\\"https://www.scrbg.com\\" rel=\\"noopener\\">scrbg.com</a>, <a href=\\"https://www.udccl.com.bd\\" rel=\\"noopener\\">udccl.com.bd</a>, <a href=\\"https://www.rhd.gov.bd\\" rel=\\"noopener\\">rhd.gov.bd</a>, <a href=\\"https://www.cdb.com.cn\\" rel=\\"noopener\\">cdb.com.cn</a>, <a href=\\"https://www.pppo.gov.bd\\" rel=\\"noopener\\">pppo.gov.bd</a>, <a href=\\"https://www.biffl.org.bd\\" rel=\\"noopener\\">biffl.org.bd</a>.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 414, @p, 'card-grid', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 414, 'en', '{"heading":"Governance structure as previously published","intro":"","items":[{"title":"Board of Directors","meta":"Strategy","body":"Representatives of all equity partners (SRBG, SEL and UDC) in proportion to shareholding; provides strategic direction and approves major decisions."},{"title":"Executive management","meta":"Operations","body":"Led by the CEO with the COO and general managers: day-to-day operations, project delivery, stakeholder management and performance reporting."},{"title":"Government oversight","meta":"Compliance","body":"The RHD Project Director monitors progress, ensures compliance with the concession agreement and is the liaison between DBEDC and government agencies."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;

-- /about: 5 blocks after sort_order 3
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'about' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 415, @p, 'callout', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 415, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. The account of the Chinese partners’ contribution below is as the previous website published it.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 416, @p, 'stat-row', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 416, 'en', '{"stats":[{"value":"US$412","unit":"M","label":"Total project investment"},{"value":"60","unit":"%","label":"SRBG equity stake"},{"value":"1,000","unit":"+","label":"Jobs created"}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 417, @p, 'card-grid', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 417, 'en', '{"heading":"Chinese contribution as previously published","intro":"","items":[{"title":"Financial investment","meta":"Finance","body":"SRBG holds a 60% majority stake, about US$240 million in equity; China Development Bank provided a ৳1,614 crore (about US$190 million) loan; financial close in April 2021."},{"title":"Technical expertise","meta":"Engineering","body":"Semi-rigid pavement technology and reinforced retaining wall systems, both for the first time in Bangladesh, with international quality-control standards and traffic management systems."},{"title":"Construction management","meta":"Delivery","body":"Modern project management systems, construction planning and scheduling, environmental management plans and quality-assurance protocols."},{"title":"Knowledge transfer","meta":"Capacity","body":"Training programmes for Bangladeshi engineers in China and on site; modern highway construction methodologies; operations and maintenance knowledge."},{"title":"Belt and Road Initiative","meta":"Cooperation","body":"Featured as a practical cooperation project at the Third Belt and Road Forum; supports regional connectivity across South Asia."},{"title":"Social responsibility","meta":"Community","body":"Multimedia classrooms donated to primary schools; support for local orphanages; COVID-19 prevention supplies; welfare programmes for local workers."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 418, @p, 'stat-row', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 418, 'en', '{"stats":[{"value":"50","unit":"+","label":"Engineers trained"},{"value":"2","unit":"","label":"New technologies introduced"},{"value":"3","unit":"","label":"Community programmes"}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 419, @p, 'rich-text', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 419, 'en', '{"heading":"Semi-rigid pavement case study as previously published","body":"<p>The semi-rigid pavement method combines the flexibility of asphalt with the strength of concrete. SRBG implemented it and trained Bangladeshi engineers in China and on site. Benefits as listed: road life extended by up to 30% compared with conventional methods; effective use of Bangladesh’s abundant fine sand; lower lifecycle costs through less frequent repairs; reduced use of traditional brick materials. Technical documentation was provided in English and Bengali.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;

-- /sustainability: 6 blocks after sort_order 2
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'sustainability' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 420, @p, 'callout', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 420, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. The economic-impact figures below are as the previous website published them; several were projections.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 421, @p, 'stat-row', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 421, 'en', '{"stats":[{"value":"75","unit":"%","label":"Travel time reduction"},{"value":"1,000","unit":"+","label":"Jobs created"},{"value":"US$412","unit":"M","label":"Total investment"},{"value":"4","unit":"","label":"National highways connected"}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 422, @p, 'rich-text', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 422, 'en', '{"heading":"Trade and commerce as previously published","body":"<p>The expressway was described as a freight corridor linking Gazipur’s manufacturing hubs with the southern ports via Narayanganj, cutting freight transit times by up to 75%, with exports projected to rise by 0.8% of GDP and transport costs to fall by an estimated 15–20%.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 423, @p, 'stat-row', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 423, 'en', '{"stats":[{"value":"+65","unit":"%","label":"Freight transport efficiency"},{"value":"+42","unit":"%","label":"Regional business growth"},{"value":"+85","unit":"%","label":"Industrial land value"},{"value":"+120","unit":"","label":"New business establishments"}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 424, @p, 'stat-row', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 424, 'en', '{"stats":[{"value":"2,000","unit":"+","label":"Direct jobs at peak construction"},{"value":"10,000","unit":"+","label":"Indirect jobs supported"},{"value":"500","unit":"+","label":"Workers trained in new technologies"}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 425, @p, 'rich-text', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 425, 'en', '{"heading":"Regional development as previously published","body":"<p>Growth areas listed: Purbachal Economic Zone, 46% land value increase; Gazipur Industrial Corridor, 38% business growth; Narayanganj Logistics Hub, 52% capacity expansion. Long-term effects projected: decentralisation of economic activity from the Dhaka core, specialised industrial clusters along the route, higher property values and local tax revenues, and integration with other planned infrastructure.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;

-- /travel/route: 2 blocks after sort_order 3
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'travel/route' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 426, @p, 'callout', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 426, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. The five location descriptions below are as the previous website published them; the interchange table above is the live record.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 427, @p, 'card-grid', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 427, 'en', '{"heading":"Key locations as previously described","intro":"","items":[{"title":"Joydebpur","meta":"Northern terminus","body":"Starting point in Gazipur District linking to N4 (Dhaka–Mymensingh/Tangail) and N3 (Dhaka–Mymensingh); a major interchange with access to industrial zones."},{"title":"Vogra","meta":"Toll plaza","body":"First section opened for Eid 2025; K3+900 marks the beginning of the partial toll collection point. Connection to local roads."},{"title":"Kanchan / Purbachal","meta":"Interchange","body":"Access to the Purbachal New Town at the K22+00 marker."},{"title":"Debogram / Bhulta","meta":"Interchange with N2","body":"Mid-route interchange with the Dhaka–Sylhet highway, connecting the expressway to the eastern regions; service area."},{"title":"Madanpur","meta":"Southern terminus","body":"Endpoint in Narayanganj District connecting to N1 towards Chattogram port, with links to N2 by nearby connections."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;

-- /travel/facilities: 2 blocks after sort_order 2
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'travel/facilities' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 428, @p, 'callout', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 428, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. The facilities described below are as the previous website published them; the list above is the live record.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 429, @p, 'card-grid', 2, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 429, 'en', '{"heading":"Facilities as previously described","intro":"","items":[{"title":"Rest areas","meta":"Service areas","body":"Two service areas, one in each direction, with restrooms and washrooms, food outlets and prayer rooms."},{"title":"Toll stations","meta":"Toll plazas","body":"Five toll plazas with multiple lanes, electronic toll collection capability and clear rate display."},{"title":"Emergency services","meta":"Round the clock","body":"Emergency call points every 2 km, ambulance services, towing and recovery."}]}', 'published' FROM DUAL WHERE @p IS NOT NULL;

-- /travel/status: 1 blocks after sort_order 4
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'travel/status' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 430, @p, 'callout', 4, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 430, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. An 18 km section from Vogra (Gazipur) to Kanchan (K3+900 to K22+00) was opened on a trial basis in late March 2025 for Eid-ul-Fitr travellers, toll-free during the Eid period, benefiting over 2 million travellers, with construction reported at 68% and completion targeted for July 2025.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;

-- /travel/toll: 2 blocks after sort_order 3
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'travel/toll' LIMIT 1);
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 431, @p, 'callout', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 431, 'en', '{"tone":"legacy","heading":"","body":"<p>Recovered from the previous website. These details may have changed and are not confirmed as current. The full-corridor tolls below are as the previous website published them for the whole 48 km; the table above is the rate in force on the open section. The per-kilometre formula shown is the one DBEDC used; the origin-destination matrix on this site derives from the same formula.</p>"}', 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `blocks` (`id`, `page_id`, `type`, `sort_order`, `settings`, `status`)
  SELECT 432, @p, 'data-table', 3, NULL, 'published' FROM DUAL WHERE @p IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT 432, 'en', '{"heading":"Full-corridor tolls as previously published","intro":"","caption":"Vehicle classes, full-distance toll and the published formula (per-km rate × distance + 50, plus 15%).","columns":[{"label":"Vehicle class","numeric":0},{"label":"Full distance (৳)","numeric":1},{"label":"Formula","numeric":0},{"label":"Open section (৳)","numeric":1}],"rows":[{"cells":["Large truck, 3+ axles (trailer), 15–25 t","1,600","(33.06 × km + 50) × 115%","740"]},{"cells":["Large/heavy truck, 2–3 axles, 7+ t","1,280","(26.45 × km + 50) × 115%","610"]},{"cells":["Medium truck, 2+ axles, 5–7 t","800","(16.53 × km + 50) × 115%","400"]},{"cells":["Large bus, 31+ seats","600","(12.40 × km + 50) × 115%","310"]},{"cells":["Small truck, 3 t","480","(9.92 × km + 50) × 115%","260"]},{"cells":["Minibus, coaster","360","(7.44 × km + 50) × 115%","210"]},{"cells":["Microbus","320","(6.61 × km + 50) × 115%","190"]},{"cells":["Pick-up, jeep, wrecker, crane","280","(5.79 × km + 50) × 115%","180"]},{"cells":["Sedan car","200","(4.31 × km + 50) × 115%","150"]}],"rowHeaderColumn":0,"note":"Previous website, routes-facilities page. Not a published tariff notification."}', 'published' FROM DUAL WHERE @p IS NOT NULL;
