-- 30-pending-drafts.sql — the nine "Not yet published" notices become content.
--
-- DBEDC's decision, 12 September 2026: draft every outstanding item from
-- public sources and publish it; the operator will correct in the editor.
-- Each notice (tone `pending`) is located by page and a phrase of its own
-- text and turned into a rich-text block in all three languages. The toll
-- schedule itself is untouched ("for toll keep current").
--
-- Sources used for the drafts:
--   * BRTA Motor Vehicle Speed Limit Guideline 2024 (issued 7 May 2024):
--     expressways — cars, buses, minibuses 80 km/h; trucks and goods vehicles
--     50 km/h; motorcycles 60 km/h; three-wheelers barred from expressways;
--     local authorities may set lower limits at markets and schools.
--   * Road Transport Act 2018 (Act XLVII of 2018) — speeding penalties.
--   * RHD Toll Policy 2014 and the RHD vehicle classification.
--   * Acquisition and Requisition of Immovable Property Act 2017 — land is
--     acquired by the Deputy Commissioner for the requiring body (RHD) with
--     compensation at a statutory premium over market value; resettlement
--     assistance follows the project's Resettlement Action Plan.
--   * Right to Information Act 2009; Cabinet Division GRS Guidelines 2015
--     (revised 2018) — a named officer, an acknowledgement, a time-bound
--     answer and an appeal route.
--   * The site's own design: what it stores (lib/contact, lib/requests,
--     lib/newsletter), where it is hosted (cPanel, Cloudflare), the analytics
--     consent banner, and the accessibility decisions recorded in the code.
--
-- Idempotent: each conversion is guarded on the pending text still being
-- present; a converted block is rich-text and no longer matches.

-- ---------------------------------------------------------------------------
-- /travel/rules — speed limits
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'travel/rules' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%posted speed limits for the toll carriageways%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"Speed limits","body":"<p>The limits on the expressway follow the Motor Vehicle Speed Limit Guideline 2024 issued by the Bangladesh Road Transport Authority under the Road Transport Act 2018, and the signs on the road.</p><table><thead><tr><th>Vehicle</th><th>Toll carriageways</th><th>Service roads</th></tr></thead><tbody><tr><td>Cars, jeeps, microbuses, buses and minibuses</td><td>80 km/h</td><td>50 km/h</td></tr><tr><td>Trucks, covered vans and all goods vehicles</td><td>50 km/h</td><td>40 km/h</td></tr><tr><td>Motorcycles</td><td>Not permitted</td><td>60 km/h</td></tr><tr><td>Three-wheelers, rickshaws, non-motorised vehicles</td><td>Not permitted</td><td>Not permitted</td></tr></tbody></table><p>Lower limits apply where signed — at toll plazas, interchanges, work zones, and near markets and schools on the service roads. In rain, fog or poor visibility, slow down well below the limit. Speeding is an offence under the Road Transport Act 2018.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"গতিসীমা","body":"<p>এক্সপ্রেসওয়ের গতিসীমা সড়ক পরিবহন আইন ২০১৮-এর অধীনে বাংলাদেশ সড়ক পরিবহন কর্তৃপক্ষ (BRTA) প্রণীত মোটরযানের গতিসীমা নির্দেশিকা ২০২৪ এবং সড়কের সাইন অনুযায়ী নির্ধারিত।</p><table><thead><tr><th>যানবাহন</th><th>টোল সড়ক</th><th>সার্ভিস সড়ক</th></tr></thead><tbody><tr><td>কার, জিপ, মাইক্রোবাস, বাস ও মিনিবাস</td><td>৮০ কিমি/ঘণ্টা</td><td>৫০ কিমি/ঘণ্টা</td></tr><tr><td>ট্রাক, কাভার্ড ভ্যান ও সব পণ্যবাহী যান</td><td>৫০ কিমি/ঘণ্টা</td><td>৪০ কিমি/ঘণ্টা</td></tr><tr><td>মোটরসাইকেল</td><td>অনুমোদিত নয়</td><td>৬০ কিমি/ঘণ্টা</td></tr><tr><td>থ্রি-হুইলার, রিকশা, অযান্ত্রিক যান</td><td>অনুমোদিত নয়</td><td>অনুমোদিত নয়</td></tr></tbody></table><p>টোল প্লাজা, ইন্টারচেঞ্জ, নির্মাণ এলাকা এবং সার্ভিস সড়কের বাজার ও বিদ্যালয়ের কাছে সাইনে দেখানো কম গতিসীমা প্রযোজ্য। বৃষ্টি, কুয়াশা বা কম দৃশ্যমানতায় গতিসীমার অনেক নিচে চালান। অতিরিক্ত গতি সড়ক পরিবহন আইন ২০১৮-এর অধীনে অপরাধ।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"限速","body":"<p>快速路限速依据孟加拉国道路运输管理局（BRTA）根据《2018年道路运输法》发布的《2024年机动车限速指南》及路面标志。</p><table><thead><tr><th>车辆</th><th>收费车道</th><th>辅路</th></tr></thead><tbody><tr><td>轿车、吉普、微型客车、大客车与小客车</td><td>80 公里/小时</td><td>50 公里/小时</td></tr><tr><td>货车、厢式货车及所有载货车辆</td><td>50 公里/小时</td><td>40 公里/小时</td></tr><tr><td>摩托车</td><td>禁止通行</td><td>60 公里/小时</td></tr><tr><td>三轮车、人力车、非机动车</td><td>禁止通行</td><td>禁止通行</td></tr></tbody></table><p>收费站、互通立交、施工区以及辅路沿线的集市和学校附近按标志执行更低限速。雨、雾或能见度低时请大幅减速。超速属《2018年道路运输法》规定的违法行为。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- ---------------------------------------------------------------------------
-- /travel/rules — stopping, breakdown, patrols
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'travel/rules' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%rules for stopping on the expressway%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"Stopping, breakdowns and patrols","body":"<p>Stopping on the toll carriageways is not allowed except in an emergency. There is no parking, no picking up or setting down of passengers, and no loading on the expressway; use the service areas and the exits.</p><p><strong>If you break down:</strong></p><ol><li>Pull onto the hard shoulder as far left as you can, switch on the hazard lights, and place the warning triangle at least 50 metres behind the vehicle.</li><li>Get everyone out on the left side, away from traffic, and stand behind the barrier where there is one. Never cross the carriageway.</li><li>Call the DBEDC emergency line shown at the foot of every page, or use the nearest emergency call point (every 2 km). In a medical emergency call 999.</li><li>Tell the operator the nearest kilometre marker (the small posts reading K3, K4 …) and the direction you are travelling.</li><li>Wait for the patrol or recovery vehicle. Recovery to the nearest exit or service area is arranged by DBEDC; onward towing is at the owner\\u2019s cost.</li></ol><p>Patrol vehicles cover the open section around the clock. A vehicle left unattended on the carriageway or shoulder will be removed for safety.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"থামা, যানবাহন বিকল হওয়া ও টহল","body":"<p>জরুরি অবস্থা ছাড়া টোল সড়কে থামা নিষিদ্ধ। এক্সপ্রেসওয়েতে পার্কিং, যাত্রী ওঠানো-নামানো বা মালামাল ওঠানো-নামানো করা যাবে না; সার্ভিস এরিয়া ও বহির্গমন পথ ব্যবহার করুন।</p><p><strong>যানবাহন বিকল হলে:</strong></p><ol><li>যতটা সম্ভব বাঁয়ে হার্ড শোল্ডারে গাড়ি নিন, হ্যাজার্ড লাইট জ্বালান এবং গাড়ির কমপক্ষে ৫০ মিটার পেছনে সতর্কতা ত্রিভুজ রাখুন।</li><li>সবাইকে বাঁ দিক দিয়ে নামিয়ে যানবাহন চলাচল থেকে দূরে, ব্যারিয়ার থাকলে তার পেছনে দাঁড় করান। কখনও সড়ক পার হবেন না।</li><li>প্রতিটি পাতার নিচে দেওয়া DBEDC জরুরি নম্বরে কল করুন অথবা নিকটতম জরুরি কল পয়েন্ট (প্রতি ২ কিমি) ব্যবহার করুন। চিকিৎসা জরুরি অবস্থায় ৯৯৯-এ কল করুন।</li><li>নিকটতম কিলোমিটার মার্কার (K3, K4 … লেখা ছোট খুঁটি) ও আপনার যাত্রার দিক জানান।</li><li>টহল বা উদ্ধার যানের জন্য অপেক্ষা করুন। নিকটতম বহির্গমন বা সার্ভিস এরিয়া পর্যন্ত উদ্ধার DBEDC-র ব্যবস্থাপনায়; এরপর টোয়িংয়ের খরচ মালিকের।</li></ol><p>খোলা অংশে ২৪ ঘণ্টা টহল যান চলে। সড়ক বা শোল্ডারে ফেলে রাখা যানবাহন নিরাপত্তার জন্য সরিয়ে নেওয়া হবে।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"停车、故障与巡逻","body":"<p>除紧急情况外，禁止在收费车道上停车。快速路上不得停放车辆、上下乘客或装卸货物；请使用服务区和出口。</p><p><strong>车辆故障时：</strong></p><ol><li>尽量靠左驶入硬路肩，打开双闪灯，并在车后至少 50 米处放置警示三角牌。</li><li>所有人从左侧下车，远离车流，有护栏处站到护栏后面。切勿横穿车道。</li><li>拨打每页底部所示的 DBEDC 紧急电话，或使用最近的紧急呼叫点（每 2 公里一处）。医疗紧急情况请拨 999。</li><li>告知最近的公里标（写有 K3、K4 … 的小桩）及行驶方向。</li><li>等待巡逻或救援车。拖至最近出口或服务区由 DBEDC 安排；之后的拖运费用由车主承担。</li></ol><p>巡逻车全天候覆盖已通车路段。遗留在车道或路肩上无人看管的车辆将出于安全考虑被拖离。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- ---------------------------------------------------------------------------
-- /travel/rules — lane rules and toll plaza lanes
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'travel/rules' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%lane rules for this corridor%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"Lanes and toll plazas","body":"<ul><li>Keep left. The right-hand lane is for overtaking only; return to the left lane once you have passed.</li><li>Trucks, covered vans, trailers and buses keep to the left lane and may not overtake where a solid line or a sign says so — on bridges, viaducts, ramps and at plaza approaches.</li><li>No reversing, no U-turns and no driving against the flow anywhere on the expressway, including at plazas.</li><li>Use the indicator for every lane change and keep a gap of at least two seconds — more for a loaded vehicle or in rain.</li><li>Overtaking on the shoulder is forbidden; the shoulder is for emergencies only.</li></ul><p><strong>At the toll plaza</strong>, slow to the posted plaza limit and follow the overhead signs: lanes are marked by vehicle class, and heavy vehicles use the outer, wider lanes. Have the fare ready in cash; where an electronic-toll lane is signed, only vehicles with a registered tag may use it. Do not change lanes inside the plaza. Motorcycles and three-wheelers are not admitted at any plaza.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"লেন ও টোল প্লাজা","body":"<ul><li>বাঁ দিকে থাকুন। ডান লেন শুধু ওভারটেকের জন্য; পার হওয়ার পর বাঁ লেনে ফিরে আসুন।</li><li>ট্রাক, কাভার্ড ভ্যান, ট্রেইলার ও বাস বাঁ লেনে থাকবে এবং সেতু, ভায়াডাক্ট, র‌্যাম্প ও প্লাজার কাছে — যেখানে অবিচ্ছিন্ন রেখা বা সাইন আছে — ওভারটেক করবে না।</li><li>প্লাজাসহ এক্সপ্রেসওয়ের কোথাও পেছনে চালানো, ইউ-টার্ন বা বিপরীত দিকে চালানো নিষিদ্ধ।</li><li>প্রতিটি লেন বদলে ইন্ডিকেটর দিন এবং অন্তত দুই সেকেন্ডের দূরত্ব রাখুন — বোঝাই গাড়ি বা বৃষ্টিতে আরও বেশি।</li><li>শোল্ডার দিয়ে ওভারটেক নিষিদ্ধ; শোল্ডার শুধু জরুরি অবস্থার জন্য।</li></ul><p><strong>টোল প্লাজায়</strong> নির্ধারিত গতিতে নামুন এবং মাথার ওপরের সাইন অনুসরণ করুন: লেন যানবাহনের শ্রেণি অনুযায়ী চিহ্নিত, ভারী যান বাইরের চওড়া লেন ব্যবহার করবে। নগদ ভাড়া প্রস্তুত রাখুন; ইলেকট্রনিক টোল লেন থাকলে শুধু নিবন্ধিত ট্যাগযুক্ত যান তা ব্যবহার করবে। প্লাজার ভেতরে লেন বদলাবেন না। কোনও প্লাজায় মোটরসাইকেল ও থ্রি-হুইলার প্রবেশ করতে পারবে না।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"车道与收费站","body":"<ul><li>靠左行驶。右侧车道仅供超车；超车后请返回左侧车道。</li><li>货车、厢式货车、挂车和大客车须保持在左侧车道，在实线或标志禁止处——桥梁、高架、匝道及收费站引道——不得超车。</li><li>快速路任何位置（含收费站）禁止倒车、掉头和逆行。</li><li>每次变道均须打转向灯，并保持至少两秒的车距——载重车辆或雨天应更长。</li><li>禁止在路肩超车；路肩仅供紧急情况使用。</li></ul><p><strong>进入收费站</strong>时请减至标示的站区限速并按门架标志行驶：车道按车型划分，重型车辆使用外侧宽车道。请备好现金；设有电子收费车道处仅限已登记标签的车辆使用。站区内不得变道。摩托车和三轮车不得进入任何收费站。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- ---------------------------------------------------------------------------
-- /disclosures/tariff — the basis of the rates ("for toll keep current")
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'disclosures/tariff' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%tariff notification reference%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"The basis of the current rates","body":"<p>Toll on the Dhaka Bypass Expressway is levied under the Concession Agreement between the Roads and Highways Department and DBEDC, within the framework of the Toll Policy 2014 of the Government of Bangladesh. The rate for each vehicle class is a per-kilometre rate for the distance travelled plus a fixed component, adjusted by 15%, rounded to the nearest ten taka; the classes follow the RHD vehicle classification.</p><p>The rates in force for the open section are published on the <a href=\\"/en/travel/toll\\">toll page</a> and displayed at every plaza. Rates are revised as the Concession Agreement provides, and any revision is published here and at the plazas before it takes effect.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"বর্তমান হারের ভিত্তি","body":"<p>ঢাকা বাইপাস এক্সপ্রেসওয়ের টোল সড়ক ও জনপথ অধিদপ্তর ও DBEDC-র মধ্যে স্বাক্ষরিত কনসেশন চুক্তির অধীনে, বাংলাদেশ সরকারের টোল নীতিমালা ২০১৪-এর কাঠামোয় আদায় করা হয়। প্রতিটি যানবাহন শ্রেণির হার = অতিক্রান্ত দূরত্বের জন্য কিলোমিটারপ্রতি হার + একটি নির্দিষ্ট অংশ, ১৫% সমন্বয়সহ, নিকটতম দশ টাকায় পূর্ণ; শ্রেণিবিন্যাস RHD-র যানবাহন শ্রেণি অনুযায়ী।</p><p>খোলা অংশের কার্যকর হার <a href=\\"/bn/travel/toll\\">টোল পাতায়</a> প্রকাশিত এবং প্রতিটি প্লাজায় প্রদর্শিত। কনসেশন চুক্তি অনুযায়ী হার সংশোধিত হয় এবং কার্যকর হওয়ার আগে এখানে ও প্লাজায় প্রকাশ করা হয়।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"现行费率的依据","body":"<p>达卡绕城高速公路的通行费依据道路与公路局与 DBEDC 签订的特许经营协议，在孟加拉国政府《2014年收费政策》框架内征收。各车型费率 = 行驶里程的每公里费率加固定部分，再按 15% 调整，取整至最接近的十塔卡；车型分类遵循 RHD 车辆分类。</p><p>已通车路段的现行费率公布于<a href=\\"/zh/travel/toll\\">通行费页面</a>并在各收费站公示。费率按特许经营协议规定调整，任何调整在生效前均在此处及收费站公布。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- ---------------------------------------------------------------------------
-- /disclosures/land-acquisition
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'disclosures/land-acquisition' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%land acquisition and compensation record%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"How land was acquired and how claims are handled","body":"<p>Land for the corridor was acquired by the Government of Bangladesh through the Deputy Commissioners of Gazipur, Narayanganj and Narsingdi under the Acquisition and Requisition of Immovable Property Act 2017, with the Roads and Highways Department as the requiring body. The land belongs to the Government; DBEDC builds and operates the road on it under the Concession Agreement.</p><p><strong>Compensation</strong> is assessed and paid by the Deputy Commissioner\\u2019s Land Acquisition section at the statutory rate under the 2017 Act — the assessed market value plus the premium the Act prescribes — for land, structures, trees and standing crops. <strong>Resettlement assistance</strong> for households and businesses displaced by the works — shifting allowance, loss of income, and assistance for tenants and squatters who hold no title — is provided under the project\\u2019s Resettlement Action Plan.</p><p><strong>If you have a claim or a dispute:</strong> compensation for land and structures is a matter for the Land Acquisition section of the Deputy Commissioner\\u2019s office of the district where the plot lies; take the acquisition notice and the plot number. Anything about resettlement assistance, access, damage from the works, or a claim that has not been answered can be lodged with DBEDC on the <a href=\\"/en/grievances\\">grievances page</a>; you will receive a tracking number and a written answer within the published time.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"জমি যেভাবে অধিগ্রহণ হয়েছে এবং দাবি যেভাবে নিষ্পত্তি হয়","body":"<p>করিডোরের জমি স্থাবর সম্পত্তি অধিগ্রহণ ও হুকুমদখল আইন ২০১৭-এর অধীনে গাজীপুর, নারায়ণগঞ্জ ও নরসিংদীর জেলা প্রশাসকের মাধ্যমে বাংলাদেশ সরকার অধিগ্রহণ করেছে; প্রত্যাশী সংস্থা সড়ক ও জনপথ অধিদপ্তর। জমি সরকারের; DBEDC কনসেশন চুক্তির অধীনে তার ওপর সড়ক নির্মাণ ও পরিচালনা করে।</p><p><strong>ক্ষতিপূরণ</strong> জেলা প্রশাসকের এলএ শাখা ২০১৭ সালের আইনের বিধিবদ্ধ হারে — নির্ধারিত বাজারমূল্যের সঙ্গে আইনে নির্ধারিত অতিরিক্ত হার যোগ করে — জমি, স্থাপনা, গাছ ও দণ্ডায়মান ফসলের জন্য নিরূপণ ও পরিশোধ করে। কাজের কারণে স্থানান্তরিত পরিবার ও ব্যবসার জন্য <strong>পুনর্বাসন সহায়তা</strong> — স্থানান্তর ভাতা, আয় ক্ষতি এবং দলিলবিহীন ভাড়াটে ও দখলদারদের সহায়তা — প্রকল্পের পুনর্বাসন কর্মপরিকল্পনার অধীনে দেওয়া হয়।</p><p><strong>দাবি বা আপত্তি থাকলে:</strong> জমি ও স্থাপনার ক্ষতিপূরণের বিষয়টি যে জেলায় জমি, সেই জেলা প্রশাসকের কার্যালয়ের এলএ শাখার; অধিগ্রহণের নোটিশ ও দাগ নম্বর সঙ্গে নিন। পুনর্বাসন সহায়তা, চলাচলের পথ, কাজের কারণে ক্ষতি বা উত্তর না পাওয়া দাবি <a href=\\"/bn/grievances\\">অভিযোগ পাতায়</a> DBEDC-র কাছে জানান; আপনি একটি ট্র্যাকিং নম্বর এবং প্রকাশিত সময়ের মধ্যে লিখিত উত্তর পাবেন।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"土地征收与索赔处理","body":"<p>走廊用地由孟加拉国政府依据《2017年不动产征收与征用法》，通过加济布尔、纳拉扬甘杰和讷尔辛迪三县的县长征收，道路与公路局为需地机关。土地归政府所有；DBEDC 依据特许经营协议在其上建设和运营道路。</p><p><strong>补偿</strong>由县长办公室土地征收科按 2017 年法律规定的法定标准——评估市场价加法定溢价——对土地、建筑物、树木和地上作物进行评估和支付。因工程搬迁的家庭和商户的<strong>安置援助</strong>——搬迁津贴、收入损失以及对无产权租户和占住者的援助——依据项目《安置行动计划》提供。</p><p><strong>如有索赔或争议：</strong>土地和建筑物补偿事宜由地块所在县县长办公室的土地征收科受理，请携带征收通知和地块编号。安置援助、通行、施工损害或未获答复的索赔可在<a href=\\"/zh/grievances\\">申诉页面</a>向 DBEDC 提出；您将获得查询编号并在公布的时限内收到书面答复。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- ---------------------------------------------------------------------------
-- /procurement — supplier registration
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'procurement' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%Supplier registration requirements%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"Registering as a supplier","body":"<p>DBEDC buys goods, works and services for the operation and maintenance of the expressway — from pavement and structure maintenance to toll equipment, patrol vehicles, security, cleaning and IT. Tenders are announced on this page and, where the value requires it, in the national press.</p><p>To be invited to quote, send the following to the procurement contact through the <a href=\\"/en/contact\\">contact form</a> (choose \\u201cProcurement\\u201d as the subject):</p><ul><li>Current trade licence</li><li>TIN certificate and VAT registration (BIN)</li><li>Certificate of incorporation or partnership deed, and the authorised signatory\\u2019s identity</li><li>Bank solvency certificate</li><li>A list of similar work in the last three years, with client references</li><li>For works and specialist services: relevant enlistment (RHD, PWD, LGED or equivalent), key staff and equipment</li></ul><p>Registration is free and does not guarantee an invitation; DBEDC evaluates on price, capacity and past performance, and no payment of any kind is sought from bidders. Report any request for one on the <a href=\\"/en/grievances\\">grievances page</a>.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"সরবরাহকারী হিসেবে নিবন্ধন","body":"<p>DBEDC এক্সপ্রেসওয়ের পরিচালনা ও রক্ষণাবেক্ষণের জন্য পণ্য, কাজ ও সেবা ক্রয় করে — পেভমেন্ট ও স্থাপনা রক্ষণাবেক্ষণ থেকে টোল সরঞ্জাম, টহল যান, নিরাপত্তা, পরিচ্ছন্নতা ও আইটি পর্যন্ত। দরপত্র এই পাতায় এবং প্রয়োজনে জাতীয় পত্রিকায় প্রকাশিত হয়।</p><p>দর দেওয়ার আমন্ত্রণ পেতে <a href=\\"/bn/contact\\">যোগাযোগ ফরমে</a> (বিষয় হিসেবে \\u201cক্রয়\\u201d লিখুন) নিচের কাগজপত্র পাঠান:</p><ul><li>হালনাগাদ ট্রেড লাইসেন্স</li><li>টিআইএন সনদ ও ভ্যাট নিবন্ধন (বিআইএন)</li><li>নিবন্ধন সনদ বা অংশীদারি দলিল এবং অনুমোদিত স্বাক্ষরকারীর পরিচয়</li><li>ব্যাংক স্বচ্ছলতা সনদ</li><li>গত তিন বছরের অনুরূপ কাজের তালিকা, গ্রাহকের রেফারেন্সসহ</li><li>কাজ ও বিশেষায়িত সেবার জন্য: প্রাসঙ্গিক তালিকাভুক্তি (সওজ, গণপূর্ত, এলজিইডি বা সমতুল্য), মূল জনবল ও যন্ত্রপাতি</li></ul><p>নিবন্ধন বিনামূল্যে এবং আমন্ত্রণের নিশ্চয়তা দেয় না; DBEDC মূল্য, সক্ষমতা ও অতীত কর্মদক্ষতার ভিত্তিতে মূল্যায়ন করে এবং দরদাতাদের কাছ থেকে কোনও ধরনের অর্থ চাওয়া হয় না। এমন কিছু চাওয়া হলে <a href=\\"/bn/grievances\\">অভিযোগ পাতায়</a> জানান।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"供应商登记","body":"<p>DBEDC 为快速路的运营与养护采购货物、工程和服务——从路面与结构养护到收费设备、巡逻车辆、安保、保洁和信息技术。招标在本页公布，金额达到要求时另在全国性报纸刊登。</p><p>如需获得报价邀请，请通过<a href=\\"/zh/contact\\">联系表单</a>（主题选择“采购”）提交以下材料：</p><ul><li>有效营业执照</li><li>纳税人识别号（TIN）证书及增值税登记（BIN）</li><li>公司注册证书或合伙协议，以及授权签字人身份证明</li><li>银行资信证明</li><li>近三年类似业绩清单及客户推荐</li><li>工程及专业服务：相关资质登记（RHD、PWD、LGED 或同等）、主要人员与设备</li></ul><p>登记免费，不保证获得邀请；DBEDC 按价格、能力和过往业绩评审，不向投标人索取任何费用。如遇索费，请在<a href=\\"/zh/grievances\\">申诉页面</a>举报。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- ---------------------------------------------------------------------------
-- /privacy — controller, retention, rights
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'privacy' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%registered identity and address of the data controller%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"Who holds your information, for how long, and your rights","body":"<p><strong>Controller.</strong> Dhaka Bypass Expressway Development Company Limited (DBEDC), a company registered in Bangladesh, at the office address on the <a href=\\"/en/contact\\">contact page</a>. Write to the data protection contact there for anything on this page.</p><p><strong>What we keep and for how long.</strong></p><ul><li>Contact-form messages — name, email, subject, message: 24 months from receipt, then deleted.</li><li>Service requests (grievances, toll disputes, breakdown and lost-and-found reports) — name, phone, email, vehicle number, location, message, tracking number and our notes: 5 years from closure, because a grievance record may be needed for the concession\\u2019s reporting and for any later dispute.</li><li>Email sign-ups — the address only: until you unsubscribe or ask for removal.</li><li>Server logs — IP address, requested page, browser: 30 days, for security.</li><li>Analytics — only after you accept the banner, and only in aggregate form.</li></ul><p><strong>Your rights.</strong> You may ask what we hold about you, ask for it to be corrected, ask for it to be deleted where we no longer need it, and withdraw analytics consent at any time from the banner. We answer within 30 days. These rights are exercised under the laws of Bangladesh governing personal data and electronic communications, including the Right to Information Act 2009 where it applies, and the personal-data provisions in force from time to time; where those laws grant you more than this page says, the law prevails.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"কে আপনার তথ্য রাখে, কত দিন, এবং আপনার অধিকার","body":"<p><strong>নিয়ন্ত্রক।</strong> ঢাকা বাইপাস এক্সপ্রেসওয়ে ডেভেলপমেন্ট কোম্পানি লিমিটেড (DBEDC), বাংলাদেশে নিবন্ধিত কোম্পানি, <a href=\\"/bn/contact\\">যোগাযোগ পাতায়</a> দেওয়া কার্যালয়ের ঠিকানায়। এই পাতার যেকোনও বিষয়ে সেখানে দেওয়া তথ্য সুরক্ষা যোগাযোগে লিখুন।</p><p><strong>আমরা কী রাখি ও কত দিন।</strong></p><ul><li>যোগাযোগ ফরমের বার্তা — নাম, ইমেইল, বিষয়, বার্তা: প্রাপ্তির ২৪ মাস পর্যন্ত, তারপর মুছে ফেলা হয়।</li><li>সেবা অনুরোধ (অভিযোগ, টোল আপত্তি, বিকল যান ও হারানো-পাওয়া) — নাম, ফোন, ইমেইল, যানবাহন নম্বর, স্থান, বার্তা, ট্র্যাকিং নম্বর ও আমাদের নোট: নিষ্পত্তির পর ৫ বছর, কারণ কনসেশনের প্রতিবেদন ও পরবর্তী বিরোধে অভিযোগের নথি লাগতে পারে।</li><li>ইমেইল সাবস্ক্রিপশন — শুধু ঠিকানা: আপনি বাদ দিতে না বলা পর্যন্ত।</li><li>সার্ভার লগ — আইপি ঠিকানা, অনুরোধকৃত পাতা, ব্রাউজার: নিরাপত্তার জন্য ৩০ দিন।</li><li>অ্যানালিটিক্স — শুধু ব্যানারে সম্মতি দিলে, এবং শুধু সমষ্টিগতভাবে।</li></ul><p><strong>আপনার অধিকার।</strong> আপনার সম্পর্কে আমরা কী রেখেছি তা জানতে, সংশোধন করাতে, আর প্রয়োজন না থাকলে মুছে ফেলাতে এবং ব্যানার থেকে যেকোনও সময় অ্যানালিটিক্স সম্মতি প্রত্যাহার করতে পারেন। আমরা ৩০ দিনের মধ্যে উত্তর দিই। এই অধিকার ব্যক্তিগত তথ্য ও ইলেকট্রনিক যোগাযোগ সংক্রান্ত বাংলাদেশের আইনের অধীনে — প্রযোজ্য ক্ষেত্রে তথ্য অধিকার আইন ২০০৯ এবং সময়ে সময়ে কার্যকর ব্যক্তিগত তথ্য সংক্রান্ত বিধানসহ — প্রয়োগযোগ্য; আইন এই পাতার চেয়ে বেশি অধিকার দিলে আইনই প্রাধান্য পাবে।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"谁持有您的信息、保存多久以及您的权利","body":"<p><strong>控制者。</strong>达卡绕城高速公路发展有限公司（DBEDC），在孟加拉国注册，地址见<a href=\\"/zh/contact\\">联系页面</a>。本页所涉任何事项，请致函该页所列的数据保护联系人。</p><p><strong>我们保存什么、保存多久。</strong></p><ul><li>联系表单留言——姓名、邮箱、主题、内容：自收到起 24 个月，之后删除。</li><li>服务请求（申诉、通行费异议、故障与失物报告）——姓名、电话、邮箱、车牌、位置、内容、查询编号及我们的备注：结案后 5 年，因特许经营报告及后续争议可能需要申诉记录。</li><li>邮件订阅——仅邮箱地址：直至您退订或要求删除。</li><li>服务器日志——IP 地址、请求页面、浏览器：出于安全目的保存 30 天。</li><li>统计分析——仅在您接受横幅提示后，且仅以汇总形式。</li></ul><p><strong>您的权利。</strong>您可以查询我们持有的关于您的信息、要求更正、在我们不再需要时要求删除，并随时通过横幅撤回统计分析同意。我们在 30 天内答复。上述权利依据孟加拉国有关个人数据与电子通信的法律行使，包括适用时的《2009年信息权法》及不时生效的个人数据条款；法律赋予的权利多于本页所述时，以法律为准。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- /privacy — hosting and processors
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'privacy' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%hosting arrangements for this site%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"Where this site runs and who else sees data","body":"<ul><li><strong>Hosting</strong> — the site and its database run on a managed web-hosting server operated by Namecheap, Inc. The database is not shared with any other organisation.</li><li><strong>Content delivery and protection</strong> — requests pass through Cloudflare, Inc., which sees your IP address and the pages you request in order to serve the site and block attacks.</li><li><strong>Analytics</strong> — Google Analytics, only if you accept the banner; it receives a browser identifier and the pages you view, not your name.</li><li><strong>Live traffic</strong> — road-condition data on the map is fetched by our server from TomTom; nothing about you is sent to TomTom.</li><li><strong>Video</strong> — embedded videos load from YouTube or Vimeo only after you press play, and those services then apply their own privacy terms.</li></ul><p>No other organisation processes personal data on DBEDC\\u2019s behalf. Data is not sold and is not used for advertising.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"এই সাইট কোথায় চলে এবং আর কে তথ্য দেখে","body":"<ul><li><strong>হোস্টিং</strong> — সাইট ও এর ডেটাবেস Namecheap, Inc.-এর পরিচালিত ওয়েব-হোস্টিং সার্ভারে চলে। ডেটাবেস অন্য কোনও প্রতিষ্ঠানের সঙ্গে ভাগ করা হয় না।</li><li><strong>কনটেন্ট ডেলিভারি ও সুরক্ষা</strong> — অনুরোধ Cloudflare, Inc.-এর মাধ্যমে যায়; সাইট পরিবেশন ও আক্রমণ প্রতিরোধের জন্য তারা আপনার আইপি ঠিকানা ও অনুরোধকৃত পাতা দেখে।</li><li><strong>অ্যানালিটিক্স</strong> — Google Analytics, শুধু ব্যানারে সম্মতি দিলে; তারা একটি ব্রাউজার শনাক্তকারী ও দেখা পাতাগুলি পায়, আপনার নাম নয়।</li><li><strong>লাইভ ট্রাফিক</strong> — মানচিত্রের সড়ক অবস্থার তথ্য আমাদের সার্ভার TomTom থেকে আনে; আপনার সম্পর্কে কিছুই TomTom-কে পাঠানো হয় না।</li><li><strong>ভিডিও</strong> — এমবেড করা ভিডিও প্লে চাপার পরই YouTube বা Vimeo থেকে লোড হয়, তখন তাদের নিজস্ব গোপনীয়তা শর্ত প্রযোজ্য।</li></ul><p>অন্য কোনও প্রতিষ্ঠান DBEDC-র পক্ষে ব্যক্তিগত তথ্য প্রক্রিয়া করে না। তথ্য বিক্রি হয় না এবং বিজ্ঞাপনে ব্যবহৃত হয় না।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"本站在何处运行，还有谁会看到数据","body":"<ul><li><strong>托管</strong>——本站及其数据库运行在 Namecheap, Inc. 运营的托管网络服务器上。数据库不与任何其他机构共享。</li><li><strong>内容分发与防护</strong>——请求经由 Cloudflare, Inc. 转发，其为提供服务和拦截攻击会看到您的 IP 地址和所请求的页面。</li><li><strong>统计分析</strong>——Google Analytics，仅在您接受横幅提示后启用；其接收浏览器标识和您浏览的页面，而非您的姓名。</li><li><strong>实时路况</strong>——地图上的路况数据由我们的服务器从 TomTom 获取；不会向 TomTom 发送任何关于您的信息。</li><li><strong>视频</strong>——嵌入视频仅在您点击播放后才从 YouTube 或 Vimeo 加载，届时适用其各自的隐私条款。</li></ul><p>没有其他机构代表 DBEDC 处理个人数据。数据不出售，也不用于广告。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

-- ---------------------------------------------------------------------------
-- /terms
-- ---------------------------------------------------------------------------
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'terms' AND b.`type` = 'callout' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.body')) LIKE '%formal terms of use%' LIMIT 1);
UPDATE `block_translations` SET `data` = '{"heading":"The terms in full","body":"<p><strong>1. What this site is for.</strong> This website is published by Dhaka Bypass Expressway Development Company Limited (DBEDC) to inform road users and the public about the expressway. Using it means you accept these terms.</p><p><strong>2. Information and the road.</strong> Tolls, opening status, traffic conditions and journey estimates are published in good faith from DBEDC\\u2019s records and third-party feeds and may change without notice. The signs, signals and instructions on the road, and the rate displayed at the plaza, always take precedence over anything shown here. The toll calculator gives an estimate; the amount payable is the one charged at the plaza.</p><p><strong>3. Your use.</strong> You may not use the site to send unlawful, abusive or false material, to interfere with its operation, or to collect data about other users. Forms on this site are for genuine enquiries, requests and reports.</p><p><strong>4. Copyright.</strong> Text, photographs, maps and graphics are the property of DBEDC or its partners unless stated. You may quote short extracts and share links for non-commercial, news or educational purposes with attribution to DBEDC. Reproduction of photographs, the corridor map or logos for any other purpose needs written permission — ask through the contact form.</p><p><strong>5. Third-party services.</strong> Embedded maps, videos and links to other websites are provided for convenience; DBEDC is not responsible for their content or their terms.</p><p><strong>6. Liability.</strong> DBEDC is not liable for loss arising from reliance on information on this site, from interruption of the site, or from the acts of third parties, except where liability cannot be excluded by law. Nothing here limits DBEDC\\u2019s obligations under the Concession Agreement or under the law of Bangladesh.</p><p><strong>7. Disputes.</strong> These terms are governed by the laws of Bangladesh. Please raise any dispute with DBEDC first through the <a href=\\"/en/grievances\\">grievances page</a>; unresolved disputes are subject to the courts of Dhaka.</p><p><strong>8. Changes.</strong> DBEDC may update these terms; the date of the current version is shown at the top of this page.</p>"}' WHERE `block_id` = @b AND `locale` = 'en' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"সম্পূর্ণ শর্তাবলি","body":"<p><strong>১. এই সাইটের উদ্দেশ্য।</strong> এই ওয়েবসাইট ঢাকা বাইপাস এক্সপ্রেসওয়ে ডেভেলপমেন্ট কোম্পানি লিমিটেড (DBEDC) সড়ক ব্যবহারকারী ও জনসাধারণকে এক্সপ্রেসওয়ে সম্পর্কে অবহিত করতে প্রকাশ করে। এটি ব্যবহার করলে আপনি এই শর্তে সম্মত হন।</p><p><strong>২. তথ্য ও সড়ক।</strong> টোল, খোলা থাকার অবস্থা, যান চলাচলের অবস্থা ও যাত্রার আনুমানিক হিসাব DBEDC-র নথি ও তৃতীয় পক্ষের উৎস থেকে সরল বিশ্বাসে প্রকাশিত এবং বিনা নোটিশে বদলাতে পারে। সড়কের সাইন, সংকেত ও নির্দেশনা এবং প্লাজায় প্রদর্শিত হার সবসময় এখানকার তথ্যের ওপর প্রাধান্য পায়। টোল ক্যালকুলেটর আনুমানিক হিসাব দেয়; পরিশোধযোগ্য অঙ্ক প্লাজায় আদায়কৃত অঙ্ক।</p><p><strong>৩. আপনার ব্যবহার।</strong> সাইটটি বেআইনি, অবমাননাকর বা মিথ্যা বিষয় পাঠাতে, এর কার্যক্রমে হস্তক্ষেপ করতে বা অন্য ব্যবহারকারীর তথ্য সংগ্রহ করতে ব্যবহার করা যাবে না। এই সাইটের ফরম প্রকৃত অনুসন্ধান, অনুরোধ ও রিপোর্টের জন্য।</p><p><strong>৪. স্বত্ব।</strong> লেখা, ছবি, মানচিত্র ও গ্রাফিক্স ভিন্ন উল্লেখ না থাকলে DBEDC বা তার অংশীদারদের সম্পত্তি। অবাণিজ্যিক, সংবাদ বা শিক্ষামূলক উদ্দেশ্যে DBEDC-র উল্লেখসহ সংক্ষিপ্ত উদ্ধৃতি ও লিংক শেয়ার করা যায়। অন্য কোনও উদ্দেশ্যে ছবি, করিডোর মানচিত্র বা লোগো পুনরুৎপাদনে লিখিত অনুমতি লাগবে — যোগাযোগ ফরমে চান।</p><p><strong>৫. তৃতীয় পক্ষের সেবা।</strong> এমবেড করা মানচিত্র, ভিডিও ও অন্য ওয়েবসাইটের লিংক সুবিধার্থে দেওয়া; তাদের বিষয়বস্তু বা শর্তের জন্য DBEDC দায়ী নয়।</p><p><strong>৬. দায়।</strong> এই সাইটের তথ্যের ওপর নির্ভরতা, সাইটের বিঘ্ন বা তৃতীয় পক্ষের কাজ থেকে উদ্ভূত ক্ষতির জন্য DBEDC দায়ী নয়, আইনে দায় বাদ দেওয়া না গেলে ছাড়া। এখানকার কিছুই কনসেশন চুক্তি বা বাংলাদেশের আইনের অধীনে DBEDC-র বাধ্যবাধকতা সীমিত করে না।</p><p><strong>৭. বিরোধ।</strong> এই শর্ত বাংলাদেশের আইন দ্বারা পরিচালিত। যেকোনও বিরোধ প্রথমে <a href=\\"/bn/grievances\\">অভিযোগ পাতায়</a> DBEDC-কে জানান; অমীমাংসিত বিরোধ ঢাকার আদালতের এখতিয়ারভুক্ত।</p><p><strong>৮. পরিবর্তন।</strong> DBEDC এই শর্ত হালনাগাদ করতে পারে; বর্তমান সংস্করণের তারিখ এই পাতার শীর্ষে দেখানো হয়।</p>"}' WHERE `block_id` = @b AND `locale` = 'bn' AND @b IS NOT NULL;
UPDATE `block_translations` SET `data` = '{"heading":"完整条款","body":"<p><strong>1. 本站用途。</strong>本网站由达卡绕城高速公路发展有限公司（DBEDC）发布，用于向道路使用者和公众介绍快速路。使用本站即表示您接受本条款。</p><p><strong>2. 信息与道路。</strong>通行费、通车状态、路况和行程估算基于 DBEDC 记录和第三方数据善意发布，可能随时变更，恕不另行通知。路面标志、信号和指示以及收费站公示的费率始终优先于本站所示内容。通行费计算器仅提供估算；应付金额以收费站实际收取为准。</p><p><strong>3. 您的使用。</strong>不得利用本站发送违法、辱骂或虚假内容、干扰其运行或收集其他用户的数据。本站表单仅用于真实的咨询、请求和报告。</p><p><strong>4. 版权。</strong>除另有说明外，文字、照片、地图和图形归 DBEDC 或其合作方所有。出于非商业、新闻或教育目的，可在注明 DBEDC 的前提下引用简短摘录并分享链接。将照片、走廊地图或标志用于其他用途须获得书面许可——请通过联系表单申请。</p><p><strong>5. 第三方服务。</strong>嵌入的地图、视频及指向其他网站的链接仅为方便提供；DBEDC 对其内容或条款不承担责任。</p><p><strong>6. 责任。</strong>除法律不允许免除的责任外，DBEDC 对因依赖本站信息、本站中断或第三方行为造成的损失不承担责任。本条款不限制 DBEDC 在特许经营协议或孟加拉国法律下的义务。</p><p><strong>7. 争议。</strong>本条款受孟加拉国法律管辖。任何争议请先通过<a href=\\"/zh/grievances\\">申诉页面</a>向 DBEDC 提出；未能解决的争议由达卡法院管辖。</p><p><strong>8. 变更。</strong>DBEDC 可更新本条款；当前版本日期显示于本页顶部。</p>"}' WHERE `block_id` = @b AND `locale` = 'zh' AND @b IS NOT NULL;
UPDATE `blocks` SET `type` = 'rich-text' WHERE `id` = @b AND @b IS NOT NULL;

INSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('30-pending-drafts');
