-- 33-translation-parity.sql — every published block and page in Bangla and Chinese (W3.25).
--
-- The Bangla-parity audit found 23 blocks recovered from the previous website
-- (24-legacy-content.sql) published in English only — the project timeline,
-- progress, specifications, objectives, pavement, vision; the partners,
-- financing and governance structure; the Chinese contribution; the economic
-- figures; the first-section history — and no page titles at all for the
-- privacy, terms and accessibility pages. A Bangla or Chinese reader got
-- English for those sections.
--
-- Each block is located by page, type and a phrase of its English row, never
-- by id. INSERT IGNORE: a translation an operator has already written is kept.
-- tests/db/fresh-import.test.js asserts no published block or page is left
-- without all three languages.

-- project · timeline · Project timeline
-- The connection charset: without it a client defaulting to latin1 stores
-- every non-ASCII character double-encoded (repaired 14 September 2026).
SET NAMES utf8mb4;

SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'timeline' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Project timeline' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"intro":"","heading":"প্রকল্পের সময়রেখা","items":[{"date":"ডিসেম্বর ২০১৮","image":"","title":"পিপিপি চুক্তি স্বাক্ষর","datetime":"2018-12-06","progress":0,"description":"<p>সড়ক ও জনপথ অধিদপ্তর এবং DBEDC-এর মধ্যে পিপিপি চুক্তি স্বাক্ষরিত হয়।</p>"},{"date":"নভেম্বর ২০২০","image":"","title":"নির্মাণকাজ শুরু","datetime":"2020-11-01","progress":0,"description":"<p>প্রাথমিক নির্মাণকাজ শুরু হয়; অ্যাপয়েন্টেড ডেট নির্ধারণের পর মে ২০২২-এ চূড়ান্ত নির্মাণকাজ আনুষ্ঠানিকভাবে শুরু হয়।</p>"},{"date":"১৫ মে ২০২২","image":"","title":"অ্যাপয়েন্টেড ডেট","datetime":"2022-05-15","progress":0,"description":"<p>আনুষ্ঠানিক অ্যাপয়েন্টেড ডেট হিসেবে নির্ধারিত, যা নির্মাণকালের আনুষ্ঠানিক সূচনা চিহ্নিত করে।</p>"},{"date":"মার্চ ২০২৫","image":"","title":"প্রথম অংশ চালু","datetime":"2025-03-27","progress":0,"description":"<p>ঈদুল ফিতরের সময় ২৭ মার্চ থেকে ৫ এপ্রিল ২০২৫ পর্যন্ত K4 থেকে K22 অংশ পরীক্ষামূলকভাবে চালু করা হয়।</p>"},{"date":"ডিসেম্বর ২০২৫ (লক্ষ্য)","image":"","title":"দ্বিতীয় অংশ চালু","datetime":"2025-12-01","progress":0,"description":"<p>সার্ভিস রোডসহ K22 থেকে K35 অংশ ডিসেম্বর ২০২৫-এর মধ্যে চালুর লক্ষ্য ছিল।</p>"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"intro":"","heading":"项目时间线","items":[{"date":"2018年12月","image":"","title":"签署PPP合同","datetime":"2018-12-06","progress":0,"description":"<p>孟加拉国公路局（RHD）与DBEDC签署PPP合同。</p>"},{"date":"2020年11月","image":"","title":"开工建设","datetime":"2020-11-01","progress":0,"description":"<p>前期施工启动；确定开工日后，正式施工于2022年5月全面展开。</p>"},{"date":"2022年5月15日","image":"","title":"开工日","datetime":"2022-05-15","progress":0,"description":"<p>确定为正式开工日，标志着建设期正式开始。</p>"},{"date":"2025年3月","image":"","title":"首段通车","datetime":"2025-03-27","progress":0,"description":"<p>K4至K22路段于2025年3月27日至4月5日开斋节期间试运行。</p>"},{"date":"2025年12月（目标）","image":"","title":"第二段通车","datetime":"2025-12-01","progress":0,"description":"<p>K22至K35路段（含辅路）计划于2025年12月前通车。</p>"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · rich-text · Progress by category
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'rich-text' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Progress by category' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"খাতভিত্তিক অগ্রগতি","body":"<p>সামগ্রিক অগ্রগতি: ৬৯.১১% (৩১ ডিসেম্বর ২০২৪)।</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"分项进度","body":"<p>总体进度：69.11%（截至2024年12月31日）。</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · stat-row · Earthwork
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'stat-row' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.stats[1].label')) = 'Earthwork' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"stats":[{"unit":"%","label":"সাধারণ","value":"৯৩.৯"},{"unit":"%","label":"মাটির কাজ","value":"৮২.৮৯"},{"unit":"%","label":"পেভমেন্ট","value":"৫৩.৯৫"},{"unit":"%","label":"ভিত্তি","value":"১০০"},{"unit":"%","label":"অবকাঠামো","value":"৯০.৯"},{"unit":"%","label":"আনুষঙ্গিক","value":"৫৪.২১"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"stats":[{"unit":"%","label":"总体","value":"93.9"},{"unit":"%","label":"土方","value":"82.89"},{"unit":"%","label":"路面","value":"53.95"},{"unit":"%","label":"基础","value":"100"},{"unit":"%","label":"结构","value":"90.9"},{"unit":"%","label":"附属工程","value":"54.21"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · card-grid · Key achievements
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'card-grid' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Key achievements' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"প্রধান অর্জন","intro":"৩১ ডিসেম্বর ২০২৪ পর্যন্ত।","items":[{"meta":"ভিত্তি","title":"ভিত্তির কাজ সম্পন্ন","body":"সব ভিত্তির কাজ সম্পন্ন হয়েছে (১০০%)।"},{"meta":"অবকাঠামো","title":"প্রধান অবকাঠামো","body":"উলুখোলা, নাগদা, মিরের বাজার ও ধীরাশ্রম ওভারপাসসহ অবকাঠামোর কাজ ৯০.৯% সম্পন্ন।"},{"meta":"মাটির কাজ","title":"সড়ক নির্মাণ","body":"টোল রোডের জন্য ৩১.৭৬ কিমি এবং সার্ভিস রোডের জন্য ৪০.৪৪ কিমি বাঁধ ভরাট সম্পন্ন।"},{"meta":"পেভমেন্ট","title":"পেভমেন্টের স্তর","body":"টোল রোডে প্রায় ২২ কিমি এবং সার্ভিস রোডে ২৮ কিমি অ্যাসফল্ট স্তর (AC-20 ও AC-13) সম্পন্ন।"},{"meta":"অবকাঠামো","title":"বক্স কালভার্ট","body":"পরিকল্পিত ৭৩টির মধ্যে ৬২টি বক্স কালভার্ট সম্পন্ন।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"主要成果","intro":"截至2024年12月31日。","items":[{"meta":"基础","title":"基础工程完成","body":"全部基础工程已完成（100%）。"},{"meta":"结构","title":"主要构造物","body":"结构工程完成90.9%，包括Ulukhula、Nagda、Mirer Bazar和Dhirasram立交桥。"},{"meta":"土方","title":"道路施工","body":"收费主线路堤填筑完成31.76公里，辅路完成40.44公里。"},{"meta":"路面","title":"路面结构层","body":"收费主线沥青层（AC-20和AC-13）完成约22公里，辅路完成28公里。"},{"meta":"结构","title":"箱涵","body":"计划73座箱涵中已完成62座。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · card-grid · Specifications
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'card-grid' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Specifications' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"বৈশিষ্ট্য","intro":"","items":[{"meta":"প্রধান ক্যারেজওয়ে","title":"৪ লেন","body":"৯.৭ মিটার প্রস্থ (৭.৩ মিটার ও ২.৪ মিটার শোল্ডার), নকশাকৃত গতি ঘণ্টায় ৮০ কিমি।"},{"meta":"সার্ভিস রোড","title":"২ লেন","body":"৫.৮ মিটার প্রস্থ (রাজউক অংশে প্রতি ৫ কিমিতে ৭.৩ মিটার), নকশাকৃত গতি ঘণ্টায় ৫০ কিমি।"},{"meta":"প্রধান অবকাঠামো","title":"১০০+","body":"৫টি নদীর সেতু, ৩টি ছোট সেতু, ৪টি ফ্লাইওভার, ৪৫টি আন্ডারপাস ও ৮৭টি কালভার্টসহ।"},{"meta":"চুক্তির মেয়াদ","title":"২৫ বছর","body":"নকশা, নির্মাণ, অর্থায়ন, পরিচালনা, রক্ষণাবেক্ষণ ও হস্তান্তর (DBFOMT)।"},{"meta":"বিনিয়োগ","title":"৪১২ মিলিয়ন মার্কিন ডলার","body":"প্রকল্পের মোট প্রাথমিক বিনিয়োগ।"},{"meta":"সেতু · ফ্লাইওভার · আন্ডারপাস","title":"১২ · ৭ · ২৭","body":"পথজুড়ে প্রধান সেতু, ফ্লাইওভার ও আন্ডারপাস।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"技术指标","intro":"","items":[{"meta":"主车道","title":"双向4车道","body":"宽9.7米（7.3米行车道加2.4米路肩），设计速度80公里/小时。"},{"meta":"辅路","title":"双车道","body":"宽5.8米（RAJUK段每5公里设7.3米），设计速度50公里/小时。"},{"meta":"主要构造物","title":"100+","body":"包括5座跨河桥、3座小桥、4座高架桥、45座下穿通道和87座涵洞。"},{"meta":"合同期限","title":"25年","body":"设计、建设、融资、运营、维护、移交（DBFOMT）。"},{"meta":"投资","title":"4.12亿美元","body":"项目初始总投资。"},{"meta":"桥梁 · 高架桥 · 下穿通道","title":"12 · 7 · 27","body":"沿线主要桥梁、高架桥和下穿通道。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · card-grid · Project objectives
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'card-grid' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Project objectives' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"প্রকল্পের উদ্দেশ্য","intro":"","items":[{"meta":"১","title":"ঢাকা ঘিরে একটি দক্ষ করিডোর","body":"রাজধানীর চারপাশে একটি দক্ষ পরিবহন করিডোর গড়ে তোলা।"},{"meta":"২","title":"রাজধানীতে যানজট কমানো","body":"ঢাকার যানজট কমানো।"},{"meta":"৩","title":"চারটি জাতীয় মহাসড়কের সংযোগ","body":"N1, N2, N3 ও N4 সংযুক্ত করা।"},{"meta":"৪","title":"উন্নত লজিস্টিকস","body":"লজিস্টিকস ও সরবরাহ ব্যবস্থার দক্ষতা বাড়ানো।"},{"meta":"৫","title":"পথজুড়ে উন্নয়ন","body":"সংলগ্ন এলাকায় অর্থনৈতিক উন্নয়ন ত্বরান্বিত করা।"},{"meta":"৬","title":"আধুনিক এক্সপ্রেসওয়ে মান","body":"বাংলাদেশে আধুনিক এক্সপ্রেসওয়ের মান প্রবর্তন করা।"},{"meta":"৭","title":"কম সময় ও খরচ","body":"যাতায়াতের সময় ও পরিবহন খরচ কমানো।"},{"meta":"৮","title":"নিরাপদ সড়ক","body":"নিয়ন্ত্রিত প্রবেশের মাধ্যমে সড়ক নিরাপত্তা বাড়ানো।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"项目目标","intro":"","items":[{"meta":"1","title":"环绕达卡的高效走廊","body":"打造环绕首都的高效交通走廊。"},{"meta":"2","title":"缓解首都拥堵","body":"缓解达卡交通拥堵。"},{"meta":"3","title":"连通四条国道","body":"连接N1、N2、N3和N4国道。"},{"meta":"4","title":"提升物流效率","body":"提升物流和供应链效率。"},{"meta":"5","title":"带动沿线发展","body":"促进沿线地区经济发展。"},{"meta":"6","title":"现代高速公路标准","body":"将现代高速公路标准引入孟加拉国。"},{"meta":"7","title":"降低时间与成本","body":"缩短出行时间，降低运输成本。"},{"meta":"8","title":"更安全的道路","body":"通过出入控制提升道路安全。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · media-prose · Semi-rigid pavement
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'media-prose' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Semi-rigid pavement' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"সেমি-রিজিড পেভমেন্ট","side":"right","image":"/semi.webp","caption":"","linkHref":"","linkLabel":"","body":"<p>নমনীয়তা ও স্থায়িত্বের সমন্বয়ে একটি হাইব্রিড পেভমেন্ট ব্যবস্থা, যা এই প্রকল্পে বাংলাদেশে প্রথম প্রবর্তিত হয়েছে।</p><p><strong>কারিগরি সুবিধা</strong></p><ul><li>ভারী বাণিজ্যিক যানবাহনের জন্য উচ্চ ভারবহন ক্ষমতা</li><li>প্রচলিত অ্যাসফল্ট পেভমেন্টের তুলনায় বেশি টেকসই</li><li>গ্রীষ্মমণ্ডলীয় আবহাওয়ায় রাটিং ও বিকৃতি প্রতিরোধে ভালো</li><li>প্রকল্পের পুরো মেয়াদে কম রক্ষণাবেক্ষণ</li></ul><p><strong>নির্মাণ প্রক্রিয়া</strong></p><ul><li>আধুনিক যন্ত্রপাতিতে নিখুঁত পুরুত্ব নিয়ন্ত্রণ</li><li>অকালে ফাটল রোধে বিশেষ কিউরিং পদ্ধতি</li><li>নির্মাণকালে নিরবচ্ছিন্ন মান পর্যবেক্ষণ</li><li>সর্বোত্তম কার্যকারিতার জন্য কম্পিউটারাইজড মিশ্রণ নকশা</li></ul>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"半刚性路面","side":"right","image":"/semi.webp","caption":"","linkHref":"","linkLabel":"","body":"<p>一种兼具柔性与耐久性的复合路面结构，由本项目首次引入孟加拉国。</p><p><strong>技术优势</strong></p><ul><li>承载能力高，适合重型商用车辆</li><li>耐久性优于传统沥青路面</li><li>在热带气候下抗车辙和抗变形能力更强</li><li>全寿命周期养护需求更低</li></ul><p><strong>施工工艺</strong></p><ul><li>采用先进设备精确控制厚度</li><li>专门养生工艺防止早期开裂</li><li>施工全过程持续质量监控</li><li>计算机配合比设计，确保最佳性能</li></ul>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · media-prose · Technology benefits
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'media-prose' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Technology benefits' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"প্রযুক্তির সুফল","side":"left","image":"/cp.webp","caption":"","linkHref":"","linkLabel":"","body":"<ul><li><strong>দীর্ঘ আয়ু</strong> — প্রচলিত পেভমেন্টের ১৫–২০ বছরের তুলনায় ৩০+ বছর সেবা</li><li><strong>ব্যয় সাশ্রয়</strong> — প্রাথমিক বিনিয়োগ বেশি, তবে পুরো মেয়াদে রক্ষণাবেক্ষণ খরচ অনেক কম</li><li><strong>আবহাওয়া সহনশীলতা</strong> — বর্ষা মৌসুম ও চরম তাপমাত্রার পরিবর্তনে উন্নত কার্যকারিতা</li></ul>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"技术效益","side":"left","image":"/cp.webp","caption":"","linkHref":"","linkLabel":"","body":"<ul><li><strong>使用寿命更长</strong>——设计使用寿命30年以上，传统路面为15–20年</li><li><strong>成本效益</strong>——初期投资较高，但全寿命周期养护成本显著降低</li><li><strong>耐候性强</strong>——在季风季节和极端温度变化下表现更优</li></ul>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- project · rich-text · Vision and mission
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'project' AND b.`type` = 'rich-text' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Vision and mission' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"রূপকল্প ও লক্ষ্য","body":"<p><strong>রূপকল্প।</strong> বিশ্বমানের একটি এক্সপ্রেসওয়ে গড়ে তুলে বাংলাদেশের পরিবহন অবকাঠামোয় রূপান্তর আনা, যা ভবিষ্যৎ উন্নয়ন প্রকল্পের দৃষ্টান্ত হবে, সংযোগ বাড়াবে এবং অর্থনৈতিক প্রবৃদ্ধিতে সহায়তা করবে।</p><p><strong>লক্ষ্য।</strong> বাংলাদেশের পরিবহন নেটওয়ার্কে নিরাপত্তা, দক্ষতা ও টেকসইতার নতুন মান স্থাপনকারী একটি রূপান্তরমূলক এক্সপ্রেসওয়ে সরবরাহ করা — উদ্ভাবনী প্রকৌশল সমাধান বাস্তবায়ন, জ্ঞান স্থানান্তর ও সক্ষমতা বৃদ্ধি, এবং করিডোর বরাবর অর্থনৈতিক উন্নয়নের সুযোগ সৃষ্টি।</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"愿景与使命","body":"<p><strong>愿景。</strong>打造世界一流的高速公路，推动孟加拉国交通基础设施转型，为未来发展项目树立典范，增强互联互通，支持经济增长。</p><p><strong>使命。</strong>建成一条在安全、效率和可持续性方面为孟加拉国交通网络树立新标准的高速公路——应用创新工程方案，促进知识转移和能力建设，并为走廊沿线创造经济发展机会。</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about/governance · stat-row · Road PPP in Bangladesh
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about/governance' AND b.`type` = 'stat-row' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.stats[0].label')) = 'Road PPP in Bangladesh' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"stats":[{"unit":"","label":"বাংলাদেশে সড়ক পিপিপি","value":"প্রথম"},{"unit":"","label":"অংশীদার প্রতিষ্ঠান","value":"৭"},{"unit":"বছর","label":"কনসেশন — নকশা, নির্মাণ, অর্থায়ন, পরিচালনা, রক্ষণাবেক্ষণ, হস্তান্তর","value":"২৫"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"stats":[{"unit":"","label":"孟加拉国首个公路PPP项目","value":"首个"},{"unit":"家","label":"合作机构","value":"7"},{"unit":"年","label":"特许经营期——设计、建设、融资、运营、维护、移交","value":"25"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about/governance · card-grid · Partners
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about/governance' AND b.`type` = 'card-grid' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Partners' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"অংশীদার","intro":"","items":[{"meta":"প্রধান বিনিয়োগকারী ও ঠিকাদার","title":"সিচুয়ান রোড অ্যান্ড ব্রিজ গ্রুপ (SRBG)","body":"৬০% ইকুইটির প্রধান বেসরকারি বিনিয়োগকারী; প্রধান ইপিসি ঠিকাদার; সেমি-রিজিড পেভমেন্ট ও রিইনফোর্সড রিটেইনিং ওয়াল প্রবর্তন করেছে। শুদাও ইনভেস্টমেন্ট গ্রুপের (SDIG) সদস্য। ১,০০০-এর বেশি স্থানীয় শ্রমিক নিয়োজিত।"},{"meta":"স্থানীয় অংশীদার, ৩০%","title":"শামীম এন্টারপ্রাইজ লিমিটেড (SEL)","body":"স্থানীয় জ্ঞান, নির্মাণ দক্ষতা, নিয়ন্ত্রক বিধি পরিপালন ও স্থানীয় সরবরাহ ব্যবস্থা দিয়ে সহায়তাকারী প্রধান স্থানীয় বেসরকারি অংশীদার।"},{"meta":"স্থানীয় অংশীদার, ১০%","title":"ইউডিসি কনস্ট্রাকশন লিমিটেড","body":"অতিরিক্ত স্থানীয় নির্মাণ সক্ষমতা ও অংশীজন সমন্বয়ে সহায়তাকারী দ্বিতীয় বাংলাদেশি অংশীদার। দুই স্থানীয় অংশীদারের সম্মিলিত অংশ ৪০%।"},{"meta":"পিপিপি সহায়তাকারী","title":"পাবলিক-প্রাইভেট পার্টনারশিপ কর্তৃপক্ষ (PPPA)","body":"২০১২ সালে প্রকল্পটির নীতিগত অনুমোদন দেয় এবং ডিসেম্বর ২০১৮-এ চুক্তি স্বাক্ষর পর্যন্ত পিপিপি চুক্তির কাঠামো নির্ধারণে সহায়তা করে। প্রধানমন্ত্রীর কার্যালয়ের অধীনে পরিচালিত।"},{"meta":"চুক্তিকারী কর্তৃপক্ষ","title":"সড়ক ও জনপথ অধিদপ্তর (RHD)","body":"সরকারি খাতের ক্লায়েন্ট ও কনসেশন প্রদানকারী; ভূমি অধিগ্রহণ ও পুনর্বাসন সম্পন্ন করে এবং ভায়াবিলিটি গ্যাপ ফান্ডিং প্রদান করে। ২৫ বছরের কনসেশন শেষে সম্পদ ফেরত পায়।"},{"meta":"প্রধান বিদেশি ঋণদাতা","title":"চায়না ডেভেলপমেন্ট ব্যাংক (CDB)","body":"এপ্রিল ২০২১-এ স্বাক্ষরিত অর্থায়ন চুক্তির আওতায় DBEDC-কে ১,৬১৪ কোটি টাকা ঋণ দেয়, যা ৪১২ মিলিয়ন মার্কিন ডলারের অর্থায়ন প্যাকেজ সম্পূর্ণ করে।"},{"meta":"দেশীয় ঋণদাতা","title":"বাংলাদেশ ইনফ্রাস্ট্রাকচার ফাইন্যান্স ফান্ড লিমিটেড (BIFFL)","body":"রাষ্ট্রায়ত্ত অবকাঠামো অর্থায়নকারী; ২০২০ সালের এডিবি-সমর্থিত ঋণ সুবিধার আওতায় DBEDC-কে ১,০৭৫ কোটি টাকার ঋণ সুবিধা, যার প্রথম কিস্তি ৪২.৫ কোটি টাকা এপ্রিল ২০২২-এ ছাড় করা হয়।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"合作伙伴","intro":"","items":[{"meta":"牵头投资方和承包商","title":"四川路桥集团（SRBG）","body":"持股60%的牵头私营投资方；EPC总承包商；引入半刚性路面和加筋挡土墙技术。蜀道投资集团（SDIG）成员企业。雇用当地员工逾1,000人。"},{"meta":"本地合作方，30%","title":"Shamim Enterprise Ltd（SEL）","body":"主要本地私营合作方，提供本地经验、施工能力、合规支持和本地供应链。"},{"meta":"本地合作方，10%","title":"UDC Construction Ltd","body":"第二家孟加拉国合作方，提供补充施工能力并协调相关方。两家本地合作方合计持股40%。"},{"meta":"PPP促进机构","title":"政府与社会资本合作管理局（PPPA）","body":"2012年原则批准本项目，并协助构建PPP协议直至2018年12月签约。隶属总理办公室。"},{"meta":"合同授予方","title":"孟加拉国公路局（RHD）","body":"公共部门业主及特许权授予方；负责征地和安置，并提供可行性缺口补助。25年特许经营期满后收回资产。"},{"meta":"主要外国贷款方","title":"国家开发银行（CDB）","body":"根据2021年4月签署的融资协议向DBEDC提供161.4亿塔卡贷款，完成4.12亿美元融资安排。"},{"meta":"国内贷款方","title":"孟加拉国基础设施融资基金有限公司（BIFFL）","body":"国有基础设施融资机构；依据2020年亚行支持的信贷额度向DBEDC提供107.5亿塔卡贷款，首期4.25亿塔卡于2022年4月发放。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about/governance · rich-text · Financing
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about/governance' AND b.`type` = 'rich-text' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Financing' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"অর্থায়ন","body":"<p>বাংলাদেশ সরকারের ভায়াবিলিটি গ্যাপ ফান্ডিং প্রাথমিকভাবে ২২৪ কোটি টাকা ছিল, পরে সংশোধন করে ৬৭৪ কোটি টাকা করা হয়। চায়না ডেভেলপমেন্ট ব্যাংক ১,৬১৪ কোটি টাকা ঋণ দেয় (চুক্তি এপ্রিল ২০২১); BIFFL ১,০৭৫ কোটি টাকা ঋণ দেয়, যার প্রথম কিস্তি ৪২.৫ কোটি টাকা এপ্রিল ২০২২-এ ছাড় করা হয়। মোট প্যাকেজ ৪১২ মিলিয়ন মার্কিন ডলার (প্রায় ৩,৫৮৫–৩,৭২৩ কোটি টাকা)।</p><p>অংশীদারদের ওয়েবসাইট: <a href=\\"https://www.scrbg.com\\" rel=\\"noopener\\">scrbg.com</a>, <a href=\\"https://www.udccl.com.bd\\" rel=\\"noopener\\">udccl.com.bd</a>, <a href=\\"https://www.rhd.gov.bd\\" rel=\\"noopener\\">rhd.gov.bd</a>, <a href=\\"https://www.cdb.com.cn\\" rel=\\"noopener\\">cdb.com.cn</a>, <a href=\\"https://www.pppo.gov.bd\\" rel=\\"noopener\\">pppo.gov.bd</a>, <a href=\\"https://www.biffl.org.bd\\" rel=\\"noopener\\">biffl.org.bd</a>।</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"融资","body":"<p>孟加拉国政府可行性缺口补助最初为22.4亿塔卡，后调整为67.4亿塔卡。国家开发银行贷款161.4亿塔卡（协议于2021年4月签署）；BIFFL贷款107.5亿塔卡，首期4.25亿塔卡于2022年4月发放。融资总额4.12亿美元（约358.5–372.3亿塔卡）。</p><p>合作方网站：<a href=\\"https://www.scrbg.com\\" rel=\\"noopener\\">scrbg.com</a>、<a href=\\"https://www.udccl.com.bd\\" rel=\\"noopener\\">udccl.com.bd</a>、<a href=\\"https://www.rhd.gov.bd\\" rel=\\"noopener\\">rhd.gov.bd</a>、<a href=\\"https://www.cdb.com.cn\\" rel=\\"noopener\\">cdb.com.cn</a>、<a href=\\"https://www.pppo.gov.bd\\" rel=\\"noopener\\">pppo.gov.bd</a>、<a href=\\"https://www.biffl.org.bd\\" rel=\\"noopener\\">biffl.org.bd</a>。</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about/governance · card-grid · Governance structure
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about/governance' AND b.`type` = 'card-grid' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Governance structure' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"পরিচালনা কাঠামো","intro":"","items":[{"meta":"কৌশল","title":"পরিচালনা পর্ষদ","body":"শেয়ারের অনুপাতে সব ইকুইটি অংশীদারের (SRBG, SEL ও UDC) প্রতিনিধি; কৌশলগত দিকনির্দেশনা দেয় এবং বড় সিদ্ধান্ত অনুমোদন করে।"},{"meta":"পরিচালনা","title":"নির্বাহী ব্যবস্থাপনা","body":"প্রধান নির্বাহী কর্মকর্তার নেতৃত্বে প্রধান পরিচালন কর্মকর্তা ও মহাব্যবস্থাপকগণ: দৈনন্দিন পরিচালনা, প্রকল্প বাস্তবায়ন, অংশীজন ব্যবস্থাপনা ও কার্যক্রম প্রতিবেদন।"},{"meta":"পরিপালন","title":"সরকারি তদারকি","body":"সওজ-এর প্রকল্প পরিচালক অগ্রগতি পর্যবেক্ষণ করেন, কনসেশন চুক্তি পরিপালন নিশ্চিত করেন এবং DBEDC ও সরকারি সংস্থার মধ্যে যোগাযোগ রক্ষা করেন।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"治理结构","intro":"","items":[{"meta":"战略","title":"董事会","body":"由各股东（SRBG、SEL和UDC）按持股比例委派代表组成；负责战略指导并审批重大决策。"},{"meta":"运营","title":"执行管理层","body":"由首席执行官领导，首席运营官及各总经理组成：负责日常运营、项目实施、相关方管理和绩效报告。"},{"meta":"合规","title":"政府监督","body":"公路局项目主任监督进度，确保遵守特许经营协议，并负责DBEDC与政府部门之间的联络。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about · stat-row · SRBG equity stake
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about' AND b.`type` = 'stat-row' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.stats[1].label')) = 'SRBG equity stake' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"stats":[{"unit":"মি.","label":"প্রকল্পের মোট বিনিয়োগ","value":"US$৪১২"},{"unit":"%","label":"SRBG-এর ইকুইটি অংশ","value":"৬০"},{"unit":"+","label":"সৃষ্ট কর্মসংস্থান","value":"১,০০০"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"stats":[{"unit":"M","label":"项目总投资","value":"US$412"},{"unit":"%","label":"SRBG持股比例","value":"60"},{"unit":"+","label":"创造就业岗位","value":"1,000"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about · card-grid · Chinese contribution
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about' AND b.`type` = 'card-grid' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Chinese contribution' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"চীনের অবদান","intro":"","items":[{"meta":"অর্থায়ন","title":"আর্থিক বিনিয়োগ","body":"SRBG-এর ৬০% সংখ্যাগরিষ্ঠ অংশ, প্রায় ২৪০ মিলিয়ন মার্কিন ডলার ইকুইটি; চায়না ডেভেলপমেন্ট ব্যাংকের ১,৬১৪ কোটি টাকা (প্রায় ১৯০ মিলিয়ন মার্কিন ডলার) ঋণ; এপ্রিল ২০২১-এ ফাইন্যান্সিয়াল ক্লোজ।"},{"meta":"প্রকৌশল","title":"কারিগরি দক্ষতা","body":"বাংলাদেশে প্রথমবারের মতো সেমি-রিজিড পেভমেন্ট প্রযুক্তি ও রিইনফোর্সড রিটেইনিং ওয়াল ব্যবস্থা, আন্তর্জাতিক মাননিয়ন্ত্রণ ও ট্রাফিক ব্যবস্থাপনা পদ্ধতিসহ।"},{"meta":"বাস্তবায়ন","title":"নির্মাণ ব্যবস্থাপনা","body":"আধুনিক প্রকল্প ব্যবস্থাপনা পদ্ধতি, নির্মাণ পরিকল্পনা ও সময়সূচি, পরিবেশ ব্যবস্থাপনা পরিকল্পনা এবং মান নিশ্চিতকরণ প্রটোকল।"},{"meta":"সক্ষমতা","title":"জ্ঞান স্থানান্তর","body":"চীনে ও প্রকল্প এলাকায় বাংলাদেশি প্রকৌশলীদের প্রশিক্ষণ; আধুনিক মহাসড়ক নির্মাণ পদ্ধতি; পরিচালনা ও রক্ষণাবেক্ষণ জ্ঞান।"},{"meta":"সহযোগিতা","title":"বেল্ট অ্যান্ড রোড ইনিশিয়েটিভ","body":"তৃতীয় বেল্ট অ্যান্ড রোড ফোরামে বাস্তব সহযোগিতা প্রকল্প হিসেবে উপস্থাপিত; দক্ষিণ এশিয়াজুড়ে আঞ্চলিক সংযোগে সহায়ক।"},{"meta":"সম্প্রদায়","title":"সামাজিক দায়বদ্ধতা","body":"প্রাথমিক বিদ্যালয়ে মাল্টিমিডিয়া ক্লাসরুম প্রদান; স্থানীয় এতিমখানায় সহায়তা; কোভিড-১৯ প্রতিরোধ সামগ্রী; স্থানীয় শ্রমিকদের কল্যাণ কর্মসূচি।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"中方贡献","intro":"","items":[{"meta":"融资","title":"资金投入","body":"SRBG持股60%，股本约2.4亿美元；国家开发银行提供161.4亿塔卡（约1.9亿美元）贷款；2021年4月实现融资关闭。"},{"meta":"工程","title":"技术专长","body":"在孟加拉国首次应用半刚性路面技术和加筋挡土墙体系，并配套国际质量控制标准和交通管理系统。"},{"meta":"实施","title":"施工管理","body":"现代项目管理体系、施工计划与进度安排、环境管理计划和质量保证制度。"},{"meta":"能力","title":"知识转移","body":"在中国及现场培训孟加拉国工程师；现代公路施工方法；运营和养护知识。"},{"meta":"合作","title":"“一带一路”倡议","body":"作为务实合作项目亮相第三届“一带一路”国际合作高峰论坛；促进南亚区域互联互通。"},{"meta":"社区","title":"社会责任","body":"向小学捐赠多媒体教室；资助当地孤儿院；捐赠新冠防疫物资；开展当地员工福利项目。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about · stat-row · Engineers trained
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about' AND b.`type` = 'stat-row' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.stats[0].label')) = 'Engineers trained' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"stats":[{"unit":"+","label":"প্রশিক্ষিত প্রকৌশলী","value":"৫০"},{"unit":"","label":"প্রবর্তিত নতুন প্রযুক্তি","value":"২"},{"unit":"","label":"সামাজিক কর্মসূচি","value":"৩"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"stats":[{"unit":"+","label":"培训工程师","value":"50"},{"unit":"项","label":"引入新技术","value":"2"},{"unit":"项","label":"社区项目","value":"3"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- about · rich-text · Semi-rigid pavement case study
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'about' AND b.`type` = 'rich-text' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Semi-rigid pavement case study' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"সেমি-রিজিড পেভমেন্ট: একটি দৃষ্টান্ত","body":"<p>সেমি-রিজিড পেভমেন্ট পদ্ধতি অ্যাসফল্টের নমনীয়তার সঙ্গে কংক্রিটের দৃঢ়তা যুক্ত করে। SRBG এটি বাস্তবায়ন করেছে এবং চীনে ও প্রকল্প এলাকায় বাংলাদেশি প্রকৌশলীদের প্রশিক্ষণ দিয়েছে। সুফল: প্রচলিত পদ্ধতির তুলনায় সড়কের আয়ু ৩০% পর্যন্ত বৃদ্ধি; বাংলাদেশে সহজলভ্য মিহি বালুর কার্যকর ব্যবহার; কম মেরামতের ফলে জীবনচক্রের ব্যয় হ্রাস; প্রচলিত ইটের ব্যবহার কমানো। কারিগরি নথি ইংরেজি ও বাংলায় সরবরাহ করা হয়েছে।</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"半刚性路面案例","body":"<p>半刚性路面兼具沥青的柔性与混凝土的强度。SRBG负责实施，并在中国和现场培训孟加拉国工程师。效益：路面寿命比传统做法延长最多30%；有效利用孟加拉国丰富的细砂资源；维修频次降低，全寿命周期成本下降；减少传统砖材用量。技术文件以英文和孟加拉文提供。</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- sustainability · stat-row · Travel time reduction
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'sustainability' AND b.`type` = 'stat-row' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.stats[0].label')) = 'Travel time reduction' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"stats":[{"unit":"%","label":"যাতায়াতের সময় হ্রাস","value":"৭৫"},{"unit":"+","label":"সৃষ্ট কর্মসংস্থান","value":"১,০০০"},{"unit":"মি.","label":"মোট বিনিয়োগ","value":"US$৪১২"},{"unit":"","label":"সংযুক্ত জাতীয় মহাসড়ক","value":"৪"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"stats":[{"unit":"%","label":"出行时间缩短","value":"75"},{"unit":"+","label":"创造就业岗位","value":"1,000"},{"unit":"M","label":"总投资","value":"US$412"},{"unit":"条","label":"连通国道","value":"4"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- sustainability · rich-text · Trade and commerce
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'sustainability' AND b.`type` = 'rich-text' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Trade and commerce' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"বাণিজ্য ও ব্যবসা","body":"<p>এক্সপ্রেসওয়েটি গাজীপুরের উৎপাদন কেন্দ্রগুলোকে নারায়ণগঞ্জ হয়ে দক্ষিণের বন্দরগুলোর সঙ্গে যুক্ত করা একটি পণ্যবাহী করিডোর, যা পণ্য পরিবহনের সময় ৭৫% পর্যন্ত কমায়। রপ্তানি জিডিপির ০.৮% বৃদ্ধি এবং পরিবহন খরচ আনুমানিক ১৫–২০% কমার প্রক্ষেপণ রয়েছে।</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"贸易与商业","body":"<p>本高速公路是一条货运走廊，经纳拉扬甘杰连接加济普尔的制造业中心与南部港口，货运时间最多缩短75%。预计出口将增加相当于GDP的0.8%，运输成本预计下降15–20%。</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- sustainability · stat-row · Freight transport efficiency
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'sustainability' AND b.`type` = 'stat-row' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.stats[0].label')) = 'Freight transport efficiency' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"stats":[{"unit":"%","label":"পণ্য পরিবহনের দক্ষতা","value":"+৬৫"},{"unit":"%","label":"আঞ্চলিক ব্যবসার প্রবৃদ্ধি","value":"+৪২"},{"unit":"%","label":"শিল্প জমির মূল্য","value":"+৮৫"},{"unit":"","label":"নতুন ব্যবসা প্রতিষ্ঠান","value":"+১২০"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"stats":[{"unit":"%","label":"货运效率","value":"+65"},{"unit":"%","label":"区域商业增长","value":"+42"},{"unit":"%","label":"工业用地价值","value":"+85"},{"unit":"家","label":"新增企业","value":"+120"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- sustainability · stat-row · Direct jobs at peak construction
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'sustainability' AND b.`type` = 'stat-row' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.stats[0].label')) = 'Direct jobs at peak construction' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"stats":[{"unit":"+","label":"নির্মাণের সর্বোচ্চ পর্যায়ে প্রত্যক্ষ কর্মসংস্থান","value":"২,০০০"},{"unit":"+","label":"পরোক্ষ কর্মসংস্থান","value":"১০,০০০"},{"unit":"+","label":"নতুন প্রযুক্তিতে প্রশিক্ষিত শ্রমিক","value":"৫০০"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"stats":[{"unit":"+","label":"施工高峰期直接就业","value":"2,000"},{"unit":"+","label":"带动间接就业","value":"10,000"},{"unit":"+","label":"接受新技术培训的工人","value":"500"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- sustainability · rich-text · Regional development
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'sustainability' AND b.`type` = 'rich-text' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Regional development' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"আঞ্চলিক উন্নয়ন","body":"<p>প্রবৃদ্ধির এলাকা: পূর্বাচল অর্থনৈতিক অঞ্চল, জমির মূল্য ৪৬% বৃদ্ধি; গাজীপুর শিল্প করিডোর, ব্যবসায় ৩৮% প্রবৃদ্ধি; নারায়ণগঞ্জ লজিস্টিকস হাব, সক্ষমতা ৫২% সম্প্রসারণ। দীর্ঘমেয়াদি প্রক্ষেপিত প্রভাব: ঢাকার কেন্দ্র থেকে অর্থনৈতিক কর্মকাণ্ডের বিকেন্দ্রীকরণ, পথজুড়ে বিশেষায়িত শিল্প ক্লাস্টার, সম্পত্তির মূল্য ও স্থানীয় রাজস্ব বৃদ্ধি, এবং অন্যান্য পরিকল্পিত অবকাঠামোর সঙ্গে সমন্বয়।</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"区域发展","body":"<p>增长区域：Purbachal经济区，地价上涨46%；加济普尔工业走廊，商业增长38%；纳拉扬甘杰物流枢纽，能力扩张52%。预计长期影响：经济活动从达卡核心区向外疏解，沿线形成专业化产业集群，房地产价值和地方税收提升，并与其他规划基础设施形成衔接。</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- travel/status · rich-text · The first section
SET @b = (SELECT b.`id` FROM `blocks` b JOIN `pages` p ON p.`id` = b.`page_id` JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en'
  WHERE p.`slug` = 'travel/status' AND b.`type` = 'rich-text' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'The first section' LIMIT 1);
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"প্রথম অংশ","body":"<p>ভোগড়া (গাজীপুর) থেকে কাঞ্চন পর্যন্ত প্রথম অংশটি ২০২৫ সালের মার্চের শেষে ঈদুল ফিতরের যাত্রীদের জন্য পরীক্ষামূলকভাবে খোলা হয়। ঈদের সময় এটি টোলমুক্ত ছিল এবং ২০ লাখের বেশি যাত্রী এটি ব্যবহার করেন। এর বর্তমান বিস্তার ও অবস্থা এই পাতায় দেখানো আছে।</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT IGNORE INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"首段","body":"<p>自Vogra（加济普尔）至Kanchan的首段于2025年3月下旬开斋节期间试通车，节日期间免收通行费，通行旅客超过200万人次。其当前通车范围和状态见本页。</p>"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- Page titles and search descriptions for the three legal pages.
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'en', 'Privacy notice', 'How DBEDC collects, uses and protects personal information on this website.', 'published' FROM `pages` p WHERE p.`slug` = 'privacy'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'bn', 'গোপনীয়তা বিজ্ঞপ্তি', 'এই ওয়েবসাইটে DBEDC কীভাবে ব্যক্তিগত তথ্য সংগ্রহ, ব্যবহার ও সুরক্ষা করে।', 'published' FROM `pages` p WHERE p.`slug` = 'privacy'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'zh', '隐私声明', 'DBEDC如何在本网站收集、使用和保护个人信息。', 'published' FROM `pages` p WHERE p.`slug` = 'privacy'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'en', 'Terms of use', 'The terms that apply to using the Dhaka Bypass Expressway website.', 'published' FROM `pages` p WHERE p.`slug` = 'terms'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'bn', 'ব্যবহারের শর্ত', 'Dhaka Bypass Expressway ওয়েবসাইট ব্যবহারের ক্ষেত্রে প্রযোজ্য শর্তাবলি।', 'published' FROM `pages` p WHERE p.`slug` = 'terms'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'zh', '使用条款', '使用达卡绕城高速公路网站所适用的条款。', 'published' FROM `pages` p WHERE p.`slug` = 'terms'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'en', 'Accessibility statement', 'How accessible this website is, the standard it is tested against, and how to report a barrier.', 'published' FROM `pages` p WHERE p.`slug` = 'accessibility'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'bn', 'প্রবেশগম্যতা বিবৃতি', 'এই ওয়েবসাইট কতটা প্রবেশগম্য, কোন মানদণ্ডে পরীক্ষা করা হয় এবং কোনো বাধা কীভাবে জানাবেন।', 'published' FROM `pages` p WHERE p.`slug` = 'accessibility'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `seo_description`, `status`) SELECT p.`id`, 'zh', '无障碍声明', '本网站的无障碍程度、所依据的测试标准，以及如何报告访问障碍。', 'published' FROM `pages` p WHERE p.`slug` = 'accessibility'
  ON DUPLICATE KEY UPDATE `title` = IF(`title` = '', VALUES(`title`), `title`), `seo_description` = IF(`seo_description` = '', VALUES(`seo_description`), `seo_description`), `page_translations`.`status` = 'published';

INSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('33-translation-parity');
