-- 39-sample-records.sql — every item that waits on DBEDC, built out with SAMPLE data.
--
-- Named officers (control room, customer service, grievance focal and appeal,
-- RTI designated officer and appellate authority, media, integrity), the
-- document libraries lenders and the RTI Act expect (resettlement plan,
-- entitlement matrix, monitoring reports, IEE/ECC, annual report, audited
-- accounts, policies, tariff notifications), a key-facts table with source and
-- date, and awards. Every sample carries the word "Sample" / "নমুনা" / "示例"
-- in a visible field. The register of what to replace is
-- docs/handover/2026-09-14-information-to-replace.md.
--
-- Also: sample S.R.O. citations on the toll records for the open section,
-- sample company identity settings, and the DBEDC control-room number, so the
-- toll table cites an instrument and the footer shows both numbers.
--
-- Additions are guarded on their own wording. Safe to import twice.

SET NAMES utf8mb4;

-- ---------------------------------------------------------------- addition to contact
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'contact');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'contact-directory' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Who to contact');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'contact-directory', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Who to contact","intro":"Role lines and mailboxes. Names, numbers and addresses shown here are sample entries until DBEDC confirms them.","items":[{"department":"Control room","role":"24-hour incident line","name":"Sample officer: Duty Controller","phone":"+880 2 5555 0199","email":"control@dhakabypass.com","hours":"24 hours, every day","notes":"Sample entry. Breakdowns, crashes, obstructions on the expressway."},{"department":"Customer service","role":"Toll and account enquiries","name":"","phone":"+880 2 5555 0100","email":"info@dhakabypass.com","hours":"Sunday–Thursday 9:00–17:00","notes":"Sample entry."},{"department":"Grievances","role":"Grievance Redress focal officer","name":"Sample officer: Manager, Customer Relations","phone":"+880 2 5555 0101","email":"grievance@dhakabypass.com","hours":"Sunday–Thursday 9:00–17:00","notes":"Sample entry. First-instance answer within the published deadline."},{"department":"Grievances","role":"Appeal officer","name":"Sample officer: Head of Operations","phone":"+880 2 5555 0102","email":"appeals@dhakabypass.com","hours":"Sunday–Thursday 9:00–17:00","notes":"Sample entry. Reviews a grievance the focal officer''s answer did not resolve, within 15 working days."},{"department":"Right to information","role":"Designated Information Officer (RTI Act 2009, s.10)","name":"Sample officer: Company Secretary","phone":"+880 2 5555 0103","email":"rti@dhakabypass.com","hours":"Sunday–Thursday 9:00–17:00","notes":"Sample entry. Requests answered within 20 working days; 30 where a third party is involved."},{"department":"Right to information","role":"Appellate authority","name":"Sample officer: Chief Executive Officer","phone":"","email":"rti-appeal@dhakabypass.com","hours":"","notes":"Sample entry. Appeal within 30 days of a refusal or a missed deadline."},{"department":"Media","role":"Press and media enquiries","name":"Sample officer: Communications Manager","phone":"+880 2 5555 0104","email":"media@dhakabypass.com","hours":"Sunday–Thursday 9:00–17:00","notes":"Sample entry."},{"department":"Integrity","role":"Integrity focal point (National Integrity Strategy)","name":"Sample officer: Head of Internal Audit","phone":"","email":"integrity@dhakabypass.com","hours":"","notes":"Sample entry. Reports of corruption or misconduct; anonymous reports accepted."}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"কার সঙ্গে যোগাযোগ করবেন","intro":"দায়িত্বভিত্তিক লাইন ও মেইলবক্স। এখানে দেখানো নাম, নম্বর ও ঠিকানা DBEDC নিশ্চিত না করা পর্যন্ত নমুনা।","items":[{"department":"নিয়ন্ত্রণ কক্ষ","role":"২৪ ঘণ্টার দুর্ঘটনা লাইন","name":"নমুনা কর্মকর্তা: ডিউটি কন্ট্রোলার","phone":"+880 2 5555 0199","email":"control@dhakabypass.com","hours":"প্রতিদিন ২৪ ঘণ্টা","notes":"নমুনা তথ্য। বিকল গাড়ি, দুর্ঘটনা ও প্রতিবন্ধকতা।"},{"department":"গ্রাহক সেবা","role":"টোল ও অ্যাকাউন্ট বিষয়ক","name":"","phone":"+880 2 5555 0100","email":"info@dhakabypass.com","hours":"রবি–বৃহস্পতি ৯:০০–১৭:০০","notes":"নমুনা তথ্য।"},{"department":"অভিযোগ","role":"অভিযোগ প্রতিকার ফোকাল কর্মকর্তা","name":"নমুনা কর্মকর্তা: ব্যবস্থাপক, গ্রাহক সম্পর্ক","phone":"+880 2 5555 0101","email":"grievance@dhakabypass.com","hours":"রবি–বৃহস্পতি ৯:০০–১৭:০০","notes":"নমুনা তথ্য। প্রকাশিত সময়সীমার মধ্যে প্রথম উত্তর।"},{"department":"অভিযোগ","role":"আপিল কর্মকর্তা","name":"নমুনা কর্মকর্তা: পরিচালনা প্রধান","phone":"+880 2 5555 0102","email":"appeals@dhakabypass.com","hours":"রবি–বৃহস্পতি ৯:০০–১৭:০০","notes":"নমুনা তথ্য। ১৫ কার্যদিবসের মধ্যে পুনর্বিবেচনা।"},{"department":"তথ্য অধিকার","role":"দায়িত্বপ্রাপ্ত কর্মকর্তা (তথ্য অধিকার আইন ২০০৯, ধারা ১০)","name":"নমুনা কর্মকর্তা: কোম্পানি সচিব","phone":"+880 2 5555 0103","email":"rti@dhakabypass.com","hours":"রবি–বৃহস্পতি ৯:০০–১৭:০০","notes":"নমুনা তথ্য। ২০ কার্যদিবসে উত্তর; তৃতীয় পক্ষ জড়িত থাকলে ৩০।"},{"department":"তথ্য অধিকার","role":"আপিল কর্তৃপক্ষ","name":"নমুনা কর্মকর্তা: প্রধান নির্বাহী কর্মকর্তা","phone":"","email":"rti-appeal@dhakabypass.com","hours":"","notes":"নমুনা তথ্য। প্রত্যাখ্যান বা সময়সীমা পার হলে ৩০ দিনের মধ্যে আপিল।"},{"department":"গণমাধ্যম","role":"সংবাদমাধ্যম বিষয়ক","name":"নমুনা কর্মকর্তা: যোগাযোগ ব্যবস্থাপক","phone":"+880 2 5555 0104","email":"media@dhakabypass.com","hours":"রবি–বৃহস্পতি ৯:০০–১৭:০০","notes":"নমুনা তথ্য।"},{"department":"শুদ্ধাচার","role":"শুদ্ধাচার ফোকাল পয়েন্ট (জাতীয় শুদ্ধাচার কৌশল)","name":"নমুনা কর্মকর্তা: অভ্যন্তরীণ নিরীক্ষা প্রধান","phone":"","email":"integrity@dhakabypass.com","hours":"","notes":"নমুনা তথ্য। দুর্নীতি বা অসদাচরণের অভিযোগ; পরিচয় গোপন রাখা যায়।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"联系对象","intro":"职能电话与邮箱。此处的姓名、号码和地址为示例，待DBEDC确认。","items":[{"department":"控制室","role":"24小时事故热线","name":"示例官员：值班控制员","phone":"+880 2 5555 0199","email":"control@dhakabypass.com","hours":"每天24小时","notes":"示例信息。车辆故障、事故、道路障碍。"},{"department":"客户服务","role":"通行费与账户咨询","name":"","phone":"+880 2 5555 0100","email":"info@dhakabypass.com","hours":"周日至周四 9:00–17:00","notes":"示例信息。"},{"department":"投诉","role":"投诉处理联络官","name":"示例官员：客户关系经理","phone":"+880 2 5555 0101","email":"grievance@dhakabypass.com","hours":"周日至周四 9:00–17:00","notes":"示例信息。在公布期限内作出初次答复。"},{"department":"投诉","role":"申诉官员","name":"示例官员：运营负责人","phone":"+880 2 5555 0102","email":"appeals@dhakabypass.com","hours":"周日至周四 9:00–17:00","notes":"示例信息。15个工作日内复核。"},{"department":"信息公开","role":"指定信息官员（2009年信息权利法第10条）","name":"示例官员：公司秘书","phone":"+880 2 5555 0103","email":"rti@dhakabypass.com","hours":"周日至周四 9:00–17:00","notes":"示例信息。20个工作日内答复；涉及第三方时为30日。"},{"department":"信息公开","role":"申诉机关","name":"示例官员：首席执行官","phone":"","email":"rti-appeal@dhakabypass.com","hours":"","notes":"示例信息。被拒绝或逾期后30日内申诉。"},{"department":"媒体","role":"新闻与媒体咨询","name":"示例官员：传播经理","phone":"+880 2 5555 0104","email":"media@dhakabypass.com","hours":"周日至周四 9:00–17:00","notes":"示例信息。"},{"department":"廉政","role":"廉政联络人（国家廉政战略）","name":"示例官员：内部审计负责人","phone":"","email":"integrity@dhakabypass.com","hours":"","notes":"示例信息。举报腐败或不当行为；接受匿名举报。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to disclosures/right-to-information
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures/right-to-information');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'contact-directory' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Designated officers');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'contact-directory', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Designated officers","intro":"Under section 10 of the Right to Information Act 2009. Sample entries until DBEDC designates the officers.","items":[{"department":"Right to information","role":"Designated Information Officer","name":"Sample officer: Company Secretary","phone":"+880 2 5555 0103","email":"rti@dhakabypass.com","hours":"Sunday–Thursday 9:00–17:00","notes":"Sample entry."},{"department":"Right to information","role":"Appellate authority","name":"Sample officer: Chief Executive Officer","phone":"","email":"rti-appeal@dhakabypass.com","hours":"","notes":"Sample entry."}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"দায়িত্বপ্রাপ্ত কর্মকর্তা","intro":"তথ্য অধিকার আইন ২০০৯-এর ধারা ১০ অনুযায়ী। DBEDC কর্মকর্তা মনোনীত না করা পর্যন্ত নমুনা।","items":[{"department":"তথ্য অধিকার","role":"দায়িত্বপ্রাপ্ত কর্মকর্তা","name":"নমুনা কর্মকর্তা: কোম্পানি সচিব","phone":"+880 2 5555 0103","email":"rti@dhakabypass.com","hours":"রবি–বৃহস্পতি ৯:০০–১৭:০০","notes":"নমুনা তথ্য।"},{"department":"তথ্য অধিকার","role":"আপিল কর্তৃপক্ষ","name":"নমুনা কর্মকর্তা: প্রধান নির্বাহী কর্মকর্তা","phone":"","email":"rti-appeal@dhakabypass.com","hours":"","notes":"নমুনা তথ্য।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"指定官员","intro":"依据2009年信息权利法第10条。DBEDC指定官员前为示例。","items":[{"department":"信息公开","role":"指定信息官员","name":"示例官员：公司秘书","phone":"+880 2 5555 0103","email":"rti@dhakabypass.com","hours":"周日至周四 9:00–17:00","notes":"示例信息。"},{"department":"信息公开","role":"申诉机关","name":"示例官员：首席执行官","phone":"","email":"rti-appeal@dhakabypass.com","hours":"","notes":"示例信息。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to disclosures/right-to-information
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures/right-to-information');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'document-list' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Proactive disclosure');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'document-list', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Proactive disclosure","intro":"Published without a request, as section 6 of the Act asks. Sample documents until DBEDC supplies the originals.","documents":[{"title":"Sample: Organisational structure and functions","description":"Departments, their heads and what each is responsible for.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2026-07-01"},{"title":"Sample: Information request form and fee schedule","description":"The form prescribed by the Information Commission and the fee per page.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2026-07-01"},{"title":"Sample: Annual RTI report 2025","description":"Requests received, answered, refused and appealed in the year.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-01-31"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"স্বপ্রণোদিত তথ্য প্রকাশ","intro":"আইনের ধারা ৬ অনুযায়ী অনুরোধ ছাড়াই প্রকাশিত। DBEDC মূল নথি দেওয়া পর্যন্ত নমুনা।","documents":[{"title":"নমুনা: সাংগঠনিক কাঠামো ও কার্যাবলি","description":"বিভাগ, বিভাগীয় প্রধান ও দায়িত্ব।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2026-07-01"},{"title":"নমুনা: তথ্য প্রাপ্তির আবেদন ফরম ও ফি","description":"তথ্য কমিশন নির্ধারিত ফরম ও পাতাপ্রতি ফি।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2026-07-01"},{"title":"নমুনা: বার্ষিক তথ্য অধিকার প্রতিবেদন ২০২৫","description":"বছরে প্রাপ্ত, উত্তরদত্ত, প্রত্যাখ্যাত ও আপিলকৃত অনুরোধ।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-01-31"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"主动公开","intro":"依法第6条无需申请即公开。DBEDC提供原件前为示例。","documents":[{"title":"示例：组织架构与职能","description":"各部门、负责人及职责。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2026-07-01"},{"title":"示例：信息申请表及收费标准","description":"信息委员会规定的表格及每页费用。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2026-07-01"},{"title":"示例：2025年信息公开年报","description":"年度内收到、答复、拒绝及申诉的申请数。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-01-31"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to disclosures/land-acquisition
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures/land-acquisition');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'document-list' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Resettlement documents');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'document-list', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Resettlement documents","intro":"The plan, the entitlement matrix and the monitoring reports lenders require to be public. Sample files until DBEDC supplies the approved versions.","documents":[{"title":"Sample: Resettlement Plan (final)","description":"Affected households, entitlements, budget and grievance mechanism for the Madanpur–Joydebpur corridor.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"4.2 MB","date":"2019-06-30"},{"title":"Sample: Entitlement matrix (Bangla summary)","description":"What each category of affected person is entitled to, in plain Bangla.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.4 MB","date":"2019-06-30"},{"title":"Sample: Social monitoring report, January–June 2026","description":"Compensation paid, relocation progress and grievances received in the half-year.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.1 MB","date":"2026-07-31"},{"title":"Sample: Grievance Redress Committee — members and contacts","description":"The committee at upazila level, its members and how to reach them.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2026-01-15"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"পুনর্বাসন নথি","intro":"পরিকল্পনা, প্রাপ্যতা ছক ও ঋণদাতাদের প্রয়োজনীয় পর্যবেক্ষণ প্রতিবেদন। DBEDC অনুমোদিত সংস্করণ দেওয়া পর্যন্ত নমুনা।","documents":[{"title":"নমুনা: পুনর্বাসন পরিকল্পনা (চূড়ান্ত)","description":"ক্ষতিগ্রস্ত পরিবার, প্রাপ্যতা, বাজেট ও অভিযোগ প্রতিকার ব্যবস্থা।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"4.2 MB","date":"2019-06-30"},{"title":"নমুনা: প্রাপ্যতা ছক (বাংলা সারসংক্ষেপ)","description":"প্রতিটি শ্রেণির ক্ষতিগ্রস্ত ব্যক্তি কী পাবেন, সহজ বাংলায়।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.4 MB","date":"2019-06-30"},{"title":"নমুনা: সামাজিক পর্যবেক্ষণ প্রতিবেদন, জানুয়ারি–জুন ২০২৬","description":"ছয় মাসে প্রদত্ত ক্ষতিপূরণ, স্থানান্তর অগ্রগতি ও প্রাপ্ত অভিযোগ।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.1 MB","date":"2026-07-31"},{"title":"নমুনা: অভিযোগ প্রতিকার কমিটি — সদস্য ও যোগাযোগ","description":"উপজেলা পর্যায়ের কমিটি, সদস্য ও যোগাযোগের উপায়।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2026-01-15"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"移民安置文件","intro":"安置计划、权益矩阵及贷款方要求公开的监测报告。DBEDC提供批准版本前为示例。","documents":[{"title":"示例：移民安置计划（终稿）","description":"受影响家庭、权益、预算及投诉机制。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"4.2 MB","date":"2019-06-30"},{"title":"示例：权益矩阵（孟加拉文摘要）","description":"各类受影响人员的权益，通俗孟加拉文。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.4 MB","date":"2019-06-30"},{"title":"示例：社会监测报告（2026年1–6月）","description":"半年内已付补偿、搬迁进展及收到的投诉。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.1 MB","date":"2026-07-31"},{"title":"示例：投诉处理委员会——成员及联系方式","description":"乡级委员会成员及联络方式。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2026-01-15"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to disclosures/environment
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures/environment');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'document-list' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Environmental documents');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'document-list', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Environmental documents","intro":"Assessment, clearance and monitoring. Sample files until DBEDC supplies the approved versions.","documents":[{"title":"Sample: Initial Environmental Examination and Environmental Management Plan","description":"Impacts identified along the corridor and the measures that manage them.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"6.8 MB","date":"2019-03-31"},{"title":"Sample: Environmental Clearance Certificate","description":"Issued by the Department of Environment, with its conditions.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2019-09-12"},{"title":"Sample: Environmental monitoring report, January–June 2026","description":"Air, noise and water results against the standards, and corrective actions.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.6 MB","date":"2026-07-31"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"পরিবেশগত নথি","intro":"মূল্যায়ন, ছাড়পত্র ও পর্যবেক্ষণ। DBEDC অনুমোদিত সংস্করণ দেওয়া পর্যন্ত নমুনা।","documents":[{"title":"নমুনা: প্রাথমিক পরিবেশগত পরীক্ষা ও পরিবেশ ব্যবস্থাপনা পরিকল্পনা","description":"করিডোর বরাবর চিহ্নিত প্রভাব ও ব্যবস্থাপনার পদক্ষেপ।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"6.8 MB","date":"2019-03-31"},{"title":"নমুনা: পরিবেশগত ছাড়পত্র","description":"পরিবেশ অধিদপ্তর কর্তৃক প্রদত্ত, শর্তসহ।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2019-09-12"},{"title":"নমুনা: পরিবেশ পর্যবেক্ষণ প্রতিবেদন, জানুয়ারি–জুন ২০২৬","description":"মানদণ্ডের বিপরীতে বায়ু, শব্দ ও পানির ফলাফল এবং সংশোধনমূলক ব্যবস্থা।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.6 MB","date":"2026-07-31"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"环境文件","intro":"评估、许可与监测。DBEDC提供批准版本前为示例。","documents":[{"title":"示例：初步环境审查及环境管理计划","description":"沿线识别的影响及应对措施。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"6.8 MB","date":"2019-03-31"},{"title":"示例：环境许可证书","description":"由环境部签发，附条件。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2019-09-12"},{"title":"示例：环境监测报告（2026年1–6月）","description":"空气、噪声、水质结果对照标准及整改措施。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.6 MB","date":"2026-07-31"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to disclosures/reports
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures/reports');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'document-list' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Reports and accounts');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'document-list', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Reports and accounts","intro":"Sample files until DBEDC''s audited statements are approved for publication.","documents":[{"title":"Sample: Annual report 2025","description":"The year in construction and operations, governance, and the audited financial statements.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"3.5 MB","date":"2026-06-30"},{"title":"Sample: Audited financial statements 2025","description":"Balance sheet, income statement, cash flows and the auditor''s report.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.2 MB","date":"2026-06-30"},{"title":"Sample: Toll revenue and traffic, quarterly","description":"Vehicles by class and toll collected per plaza, each quarter since opening.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-07-15"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"প্রতিবেদন ও হিসাব","intro":"DBEDC-এর নিরীক্ষিত বিবরণী প্রকাশের অনুমোদন পাওয়া পর্যন্ত নমুনা।","documents":[{"title":"নমুনা: বার্ষিক প্রতিবেদন ২০২৫","description":"নির্মাণ ও পরিচালনার বছর, সুশাসন ও নিরীক্ষিত আর্থিক বিবরণী।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"3.5 MB","date":"2026-06-30"},{"title":"নমুনা: নিরীক্ষিত আর্থিক বিবরণী ২০২৫","description":"স্থিতিপত্র, আয় বিবরণী, নগদ প্রবাহ ও নিরীক্ষকের প্রতিবেদন।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.2 MB","date":"2026-06-30"},{"title":"নমুনা: ত্রৈমাসিক টোল আয় ও যানবাহন","description":"উদ্বোধনের পর থেকে প্রতি ত্রৈমাসিকে প্লাজাভিত্তিক যানবাহন ও টোল।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-07-15"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"报告与账目","intro":"DBEDC审计报表获准发布前为示例。","documents":[{"title":"示例：2025年年报","description":"建设与运营年度回顾、治理及审计财务报表。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"3.5 MB","date":"2026-06-30"},{"title":"示例：2025年审计财务报表","description":"资产负债表、损益表、现金流量表及审计报告。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"1.2 MB","date":"2026-06-30"},{"title":"示例：季度通行费收入与交通量","description":"通车以来各季度各收费站分车型车流量及通行费。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-07-15"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to disclosures/policies
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures/policies');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'document-list' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Policy documents');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'document-list', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Policy documents","intro":"Sample files until the board-approved policies are supplied.","documents":[{"title":"Sample: Anti-corruption and gifts policy","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-01-01"},{"title":"Sample: Whistle-blowing policy","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-01-01"},{"title":"Sample: Related-party transactions policy","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2025-01-01"},{"title":"Sample: Occupational health and safety policy","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2025-01-01"},{"title":"Sample: CCTV and personal data policy","description":"How camera images and personal data are used and kept.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-09-01"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"নীতিমালা","intro":"পরিচালনা পর্ষদ-অনুমোদিত নীতিমালা দেওয়া পর্যন্ত নমুনা।","documents":[{"title":"নমুনা: দুর্নীতিবিরোধী ও উপহার নীতি","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-01-01"},{"title":"নমুনা: তথ্য ফাঁসকারী সুরক্ষা নীতি","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-01-01"},{"title":"নমুনা: সংশ্লিষ্ট পক্ষ লেনদেন নীতি","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2025-01-01"},{"title":"নমুনা: পেশাগত স্বাস্থ্য ও নিরাপত্তা নীতি","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2025-01-01"},{"title":"নমুনা: সিসিটিভি ও ব্যক্তিগত তথ্য নীতি","description":"ক্যামেরার ছবি ও ব্যক্তিগত তথ্য কীভাবে ব্যবহৃত ও সংরক্ষিত হয়।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-09-01"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"政策文件","intro":"董事会批准的政策提供前为示例。","documents":[{"title":"示例：反腐败与礼品政策","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-01-01"},{"title":"示例：举报人保护政策","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-01-01"},{"title":"示例：关联交易政策","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2025-01-01"},{"title":"示例：职业健康与安全政策","description":"","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.3 MB","date":"2025-01-01"},{"title":"示例：监控与个人数据政策","description":"摄像画面与个人数据的使用与保存方式。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2026-09-01"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to disclosures/tariff
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures/tariff');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'document-list' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Notifications in force');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'document-list', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Notifications in force","intro":"Each toll figure on this site cites one of these. Sample notifications until DBEDC supplies the gazetted instruments.","documents":[{"title":"Sample notification: S.R.O. No. 000-Law/2025 — toll schedule, Vogra–Purbachal section","description":"Rates per vehicle class for the section open to traffic; effective 24 August 2025.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-08-20"},{"title":"Sample notification: toll exemptions","description":"Vehicle categories exempt from toll and the identification required at the plaza.","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2025-08-20"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"কার্যকর প্রজ্ঞাপন","intro":"এই সাইটের প্রতিটি টোল অঙ্ক এর একটিকে উদ্ধৃত করে। DBEDC গেজেটকৃত প্রজ্ঞাপন দেওয়া পর্যন্ত নমুনা।","documents":[{"title":"নমুনা প্রজ্ঞাপন: এস.আর.ও. নং ০০০-আইন/২০২৫ — ভোগড়া–পূর্বাচল অংশের টোল তালিকা","description":"চালু অংশের যানবাহন শ্রেণিভিত্তিক হার; ২৪ আগস্ট ২০২৫ থেকে কার্যকর।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-08-20"},{"title":"নমুনা প্রজ্ঞাপন: টোল অব্যাহতি","description":"টোলমুক্ত যানবাহনের শ্রেণি ও প্লাজায় প্রয়োজনীয় পরিচয়পত্র।","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2025-08-20"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"现行通告","intro":"本站每一通行费数字均引用其中之一。DBEDC提供公报文件前为示例。","documents":[{"title":"示例通告：S.R.O. 000-Law/2025——Vogra至Purbachal路段通行费表","description":"已通车路段各车型费率；2025年8月24日起生效。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.2 MB","date":"2025-08-20"},{"title":"示例通告：通行费豁免","description":"免收通行费的车辆类别及收费站所需证件。","file":"/downloads/sample-document.pdf","fileType":"PDF","fileSize":"0.1 MB","date":"2025-08-20"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to about/concession
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'about/concession');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'data-table' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Key facts');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'data-table', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Key facts","intro":"One place for the figures the rest of the site quotes. Values marked sample await DBEDC''s confirmation, with the source and date shown.","caption":"Key facts about the concession","columns":[{"label":"Fact","numeric":0},{"label":"Value","numeric":0},{"label":"Source","numeric":0},{"label":"As at","numeric":0}],"rows":[{"cells":["Project cost","Sample figure: US$ 358.8 million","BIFFL / lender disclosure","2026-09"]},{"cells":["Shareholding","Sample figure: SRBG 70%, SEL 30% (UDC as introducing partner)","Share register extract","2026-09"]},{"cells":["Concession term","Sample figure: 25 years from signing (December 2018), including construction","Concession agreement","2026-09"]},{"cells":["Grantor","Roads and Highways Department, Government of Bangladesh","Concession agreement","2026-09"]},{"cells":["Lenders","Sample: China Development Bank; Bangladesh Infrastructure Finance Fund Limited","Financing agreements","2026-09"]},{"cells":["Company registration","Sample figure: RJSC C-000000/2018","RJSC certificate","2026-09"]},{"cells":["Registered office","Sample: Level 8, Sample Tower, Gulshan Avenue, Dhaka 1212","RJSC certificate","2026-09"]}],"rowHeaderColumn":0,"note":"Values marked “Sample” are placeholders shown so the table is complete; each will be replaced by the confirmed figure and its source document."}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"মূল তথ্য","intro":"সাইটের বাকি অংশে উদ্ধৃত সংখ্যাগুলোর একক উৎস। নমুনা চিহ্নিত মানগুলো DBEDC-এর নিশ্চিতকরণের অপেক্ষায়; উৎস ও তারিখ দেখানো আছে।","caption":"কনসেশনের মূল তথ্য","columns":[{"label":"তথ্য","numeric":0},{"label":"মান","numeric":0},{"label":"উৎস","numeric":0},{"label":"তারিখ","numeric":0}],"rows":[{"cells":["প্রকল্প ব্যয়","নমুনা সংখ্যা: ৩৫.৮৮ কোটি মার্কিন ডলার","BIFFL / ঋণদাতার প্রকাশনা","২০২৬-০৯"]},{"cells":["শেয়ারহোল্ডিং","নমুনা সংখ্যা: SRBG ৭০%, SEL ৩০% (UDC পরিচয়কারী অংশীদার)","শেয়ার রেজিস্টার","২০২৬-০৯"]},{"cells":["কনসেশন মেয়াদ","নমুনা সংখ্যা: স্বাক্ষর (ডিসেম্বর ২০১৮) থেকে ২৫ বছর, নির্মাণসহ","কনসেশন চুক্তি","২০২৬-০৯"]},{"cells":["গ্রান্টর","সড়ক ও জনপথ অধিদপ্তর, বাংলাদেশ সরকার","কনসেশন চুক্তি","২০২৬-০৯"]},{"cells":["ঋণদাতা","নমুনা: চায়না ডেভেলপমেন্ট ব্যাংক; বাংলাদেশ ইনফ্রাস্ট্রাকচার ফাইন্যান্স ফান্ড লিমিটেড","অর্থায়ন চুক্তি","২০২৬-০৯"]},{"cells":["কোম্পানি নিবন্ধন","নমুনা সংখ্যা: RJSC C-000000/2018","RJSC সনদ","২০২৬-০৯"]},{"cells":["নিবন্ধিত কার্যালয়","নমুনা: লেভেল ৮, স্যাম্পল টাওয়ার, গুলশান অ্যাভিনিউ, ঢাকা ১২১২","RJSC সনদ","২০২৬-০৯"]}],"rowHeaderColumn":0,"note":"“নমুনা” চিহ্নিত মানগুলো সারণি সম্পূর্ণ রাখার জন্য দেখানো; প্রতিটি নিশ্চিত সংখ্যা ও উৎস নথি দিয়ে প্রতিস্থাপিত হবে।"}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"关键数据","intro":"本站其他页面引用数据的统一来源。标记为示例的数值待DBEDC确认；已注明来源与日期。","caption":"特许经营关键数据","columns":[{"label":"项目","numeric":0},{"label":"数值","numeric":0},{"label":"来源","numeric":0},{"label":"截至","numeric":0}],"rows":[{"cells":["项目造价","示例数值：3.588亿美元","BIFFL / 贷款方披露","2026-09"]},{"cells":["股权结构","示例数值：SRBG 70%，SEL 30%（UDC为引介方）","股东名册摘录","2026-09"]},{"cells":["特许期","示例数值：自签约（2018年12月）起25年，含建设期","特许经营协议","2026-09"]},{"cells":["授权方","孟加拉国政府公路局","特许经营协议","2026-09"]},{"cells":["贷款方","示例：国家开发银行；孟加拉国基础设施融资基金有限公司","融资协议","2026-09"]},{"cells":["公司注册","示例数值：RJSC C-000000/2018","RJSC证书","2026-09"]},{"cells":["注册办公地址","示例：达卡1212 古尔山大道 示例大厦8层","RJSC证书","2026-09"]}],"rowHeaderColumn":0,"note":"标记为“示例”的数值为占位，以使表格完整；每项将由确认数值及其来源文件替换。"}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- addition to about/recognition
SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'about/recognition');
SET @has = (SELECT COUNT(*) FROM `blocks` b JOIN `block_translations` t ON t.`block_id` = b.`id` AND t.`locale` = 'en' WHERE b.`page_id` = @p AND b.`type` = 'card-grid' AND JSON_UNQUOTE(JSON_EXTRACT(t.`data`, '$.heading')) = 'Awards');
SET @ok = (@p IS NOT NULL AND @has = 0);
SET @last = (SELECT `id` FROM `blocks` WHERE `page_id` = @p ORDER BY `sort_order` DESC, `id` DESC LIMIT 1);
SET @lastsort = (SELECT `sort_order` FROM `blocks` WHERE `id` = @last);
SET @endcta = (SELECT `type` = 'cta-band' FROM `blocks` WHERE `id` = @last);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `id` = @last AND @ok AND @endcta = 1;
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`) SELECT @p, 'card-grid', IF(@endcta = 1, @lastsort, COALESCE(@lastsort, 0) + 1), 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'en', '{"heading":"Awards","intro":"Sample entries until DBEDC confirms awards on record.","items":[{"meta":"Sample award · 2025","title":"Infrastructure Project of the Year","body":"Awarded by a national engineering body for the first PPP expressway section opened to traffic. Sample entry: awarding body and date to be confirmed."},{"meta":"Sample award · 2024","title":"Occupational safety recognition","body":"One million safe working hours on the construction sites. Sample entry."}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'bn', '{"heading":"পুরস্কার","intro":"DBEDC পুরস্কারের রেকর্ড নিশ্চিত করা পর্যন্ত নমুনা।","items":[{"meta":"নমুনা পুরস্কার · ২০২৫","title":"বছরের সেরা অবকাঠামো প্রকল্প","body":"যান চলাচলের জন্য খোলা প্রথম পিপিপি এক্সপ্রেসওয়ে অংশের জন্য জাতীয় প্রকৌশল সংস্থার পুরস্কার। নমুনা তথ্য: প্রদানকারী ও তারিখ নিশ্চিত করা হবে।"},{"meta":"নমুনা পুরস্কার · ২০২৪","title":"পেশাগত নিরাপত্তা স্বীকৃতি","body":"নির্মাণস্থলে দশ লক্ষ নিরাপদ কর্মঘণ্টা। নমুনা তথ্য।"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`) SELECT @b, 'zh', '{"heading":"奖项","intro":"DBEDC确认获奖记录前为示例。","items":[{"meta":"示例奖项 · 2025","title":"年度基础设施项目","body":"国家工程机构就首个通车的PPP快速路段颁发。示例信息：颁奖机构与日期待确认。"},{"meta":"示例奖项 · 2024","title":"职业安全表彰","body":"施工现场累计一百万安全工时。示例信息。"}]}', 'published' FROM DUAL WHERE @b IS NOT NULL;

-- ---------------------------------------------------------------- toll citations (sample)
-- The rate records for the open section cite a sample instrument, so no toll
-- figure renders without a citation. The number is a placeholder pattern
-- (000) that the real S.R.O. replaces; the date matches the opening.
UPDATE `toll_rates` SET `sro_number` = 'Sample: S.R.O. No. 000-Law/2025', `sro_date` = '2025-08-20', `sro_link` = '/downloads/sample-document.pdf'
 WHERE (`sro_number` IS NULL OR `sro_number` = '') AND `effective_from` <= '2025-08-24';

-- ---------------------------------------------------------------- company identity and control room (sample)
INSERT INTO `site_settings` (`setting_key`, `value`) VALUES
  ('contact.emergency_phone', '"+880 2 5555 0199"'),
  ('contact.phone', '"+880 2 5555 0100"'),
  ('contact.email', '"info@dhakabypass.com"'),
  ('contact.address', '{"en":"Sample: Level 8, Sample Tower, Gulshan Avenue, Dhaka 1212","bn":"নমুনা: লেভেল ৮, স্যাম্পল টাওয়ার, গুলশান অ্যাভিনিউ, ঢাকা ১২১২","zh":"示例：达卡1212 古尔山大道 示例大厦8层"}'),
  ('contact.hours', '{"en":"Sunday–Thursday, 9:00–17:00","bn":"রবিবার–বৃহস্পতিবার, ৯:০০–১৭:০০","zh":"周日至周四 9:00–17:00"}')
  ON DUPLICATE KEY UPDATE `value` = IF(TRIM(BOTH '"' FROM `value`) IN ('', '{}', '01610285004'), VALUES(`value`), `value`);

-- ---------------------------------------------------------------- sample media without people (UI audit UI-CONT-01)
-- The sample camera stills and panoramas showed workers, residents and a
-- ceremony beside text saying cameras show traffic, not people. Road-only
-- frames until real captures arrive.
UPDATE `cameras` SET `snapshot_url` = '/photo/20.webp' WHERE `is_sample` = 1 AND `snapshot_url` = '/photo/24.webp';
UPDATE `cameras` SET `snapshot_url` = '/photo/22.webp' WHERE `is_sample` = 1 AND `snapshot_url` = '/photo/25.webp';
UPDATE `cameras` SET `snapshot_url` = '/photo/23.webp' WHERE `is_sample` = 1 AND `snapshot_url` = '/photo/1.webp';
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.image', '/photo/20.webp')
 WHERE b.`type` = 'panorama' AND JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.image')) = '/photo/24.webp';

-- ---------------------------------------------------------------- video posters (UI audit UI-MEDIA-01)
-- The video tiles rendered as blank plates: the block will not fetch a
-- provider thumbnail (privacy, CSP), and no poster had been set. The site's
-- own corridor photographs stand in until DBEDC's footage arrives with frames.
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.poster', ELT(1 + MOD(b.`sort_order`, 4), '/photo/20.webp', '/photo/22.webp', '/photo/23.webp', '/bg-hero.webp'))
 WHERE b.`type` = 'video-embed' AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.poster')), '') = '';

INSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('39-sample-records');
