-- 45: second-level navigation (W8N.3; navigation audit NAV-IA-01..04).
--
-- GENERATED by scripts/content/gen_section_menus.py. Edit that, not this.
--
-- Three things, all of them navigation and none of them new prose:
--
--   1. The `travel` hub page. /travel was a 308 to /travel/status, so the first
--      item in the primary navigation had no address of its own: a reader who
--      clicked "Travel Info" landed on a page called "What's open" and a shared
--      link recorded the leaf rather than the section. The redirect rows are
--      removed and a real page takes the address.
--
--   2. A menu for each section — travel, about, project, disclosures, safety,
--      media. EVERY LABEL IS READ FROM THE PAGE ITSELF, in each language, so a
--      title changed in the admin changes its menu entry, and no Bangla or
--      Chinese is written here.
--
--   3. A `section-subnav` block at the top of each hub, which is what turns the
--      menus into second-level navigation a reader can see. Twelve pages were
--      reachable from no navigation at all before this.
--
-- Safe to import twice: every statement is guarded on what it creates.

SET NAMES utf8mb4;

-- ---- 1. the travel hub -----------------------------------------------------
-- The redirects that stood where the page should be. They were written when
-- the old `travel` page became `travel/status`; a page now takes that address,
-- and a redirect would shadow it.
DELETE FROM `redirects` WHERE `source` IN ('/en/travel', '/bn/travel', '/zh/travel')
  AND `destination` IN ('/en/travel/status', '/bn/travel/status', '/zh/travel/status');

INSERT INTO `pages` (`slug`, `status`, `nav_order`)
  SELECT 'travel', 'published', 5 FROM DUAL
   WHERE NOT EXISTS (SELECT 1 FROM (SELECT `id` FROM `pages` WHERE `slug` = 'travel') AS x);
SET @travel = (SELECT `id` FROM `pages` WHERE `slug` = 'travel');

INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `status`)
  SELECT @travel, 'en', 'Travel information', 'published' FROM DUAL
   WHERE @travel IS NOT NULL AND NOT EXISTS (
     SELECT 1 FROM (SELECT `page_id` FROM `page_translations`
                     WHERE `page_id` = @travel AND `locale` = 'en') AS x);
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `status`)
  SELECT @travel, 'bn', 'ভ্রমণ তথ্য', 'published' FROM DUAL
   WHERE @travel IS NOT NULL AND NOT EXISTS (
     SELECT 1 FROM (SELECT `page_id` FROM `page_translations`
                     WHERE `page_id` = @travel AND `locale` = 'bn') AS x);
INSERT INTO `page_translations` (`page_id`, `locale`, `title`, `status`)
  SELECT @travel, 'zh', '出行信息', 'published' FROM DUAL
   WHERE @travel IS NOT NULL AND NOT EXISTS (
     SELECT 1 FROM (SELECT `page_id` FROM `page_translations`
                     WHERE `page_id` = @travel AND `locale` = 'zh') AS x);

-- The hub's own page header, titled from the rows just written.
SET @ok = (@travel IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @travel AND `type` IN ('page-header', 'hero')) = 0);
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @travel, 'page-header', 0, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('eyebrow', '', 'heading', pt.`title`, 'lede', '', 'showUpdated', 'no'), 'published'
    FROM `page_translations` pt WHERE @b IS NOT NULL AND pt.`page_id` = @travel AND pt.`title` <> '';

-- ---- 2. the menus ----------------------------------------------------------

INSERT IGNORE INTO `menus` (`slug`) VALUES ('travel');
SET @m = (SELECT `id` FROM `menus` WHERE `slug` = 'travel');
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/status';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/status');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/status', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 10
    FROM `pages` p
   WHERE p.`slug` = 'travel/status' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/toll';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/toll');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/toll', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 20
    FROM `pages` p
   WHERE p.`slug` = 'travel/toll' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/payment';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/payment');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/payment', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 30
    FROM `pages` p
   WHERE p.`slug` = 'travel/payment' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/route';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/route');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/route', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 40
    FROM `pages` p
   WHERE p.`slug` = 'travel/route' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/map';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/map');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/map', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 50
    FROM `pages` p
   WHERE p.`slug` = 'travel/map' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/vehicle-classes';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/vehicle-classes');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/vehicle-classes', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 60
    FROM `pages` p
   WHERE p.`slug` = 'travel/vehicle-classes' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/rules';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/rules');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/rules', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 70
    FROM `pages` p
   WHERE p.`slug` = 'travel/rules' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/advisories';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/advisories');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/advisories', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 80
    FROM `pages` p
   WHERE p.`slug` = 'travel/advisories' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/cameras';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/cameras');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/cameras', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 90
    FROM `pages` p
   WHERE p.`slug` = 'travel/cameras' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/breakdown';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/breakdown');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/breakdown', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 100
    FROM `pages` p
   WHERE p.`slug` = 'travel/breakdown' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/lost-found';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/lost-found');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/lost-found', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 110
    FROM `pages` p
   WHERE p.`slug` = 'travel/lost-found' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/toll-dispute';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/toll-dispute');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/toll-dispute', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 120
    FROM `pages` p
   WHERE p.`slug` = 'travel/toll-dispute' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/facilities';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/facilities');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/facilities', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 130
    FROM `pages` p
   WHERE p.`slug` = 'travel/facilities' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/freight';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/freight');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/freight', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 140
    FROM `pages` p
   WHERE p.`slug` = 'travel/freight' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;

INSERT IGNORE INTO `menus` (`slug`) VALUES ('about');
SET @m = (SELECT `id` FROM `menus` WHERE `slug` = 'about');
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/about/concession';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'about/concession');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'about/concession', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 10
    FROM `pages` p
   WHERE p.`slug` = 'about/concession' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/about/governance';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'about/governance');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'about/governance', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 20
    FROM `pages` p
   WHERE p.`slug` = 'about/governance' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/about/organisation';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'about/organisation');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'about/organisation', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 30
    FROM `pages` p
   WHERE p.`slug` = 'about/organisation' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/about/integrity';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'about/integrity');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'about/integrity', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 40
    FROM `pages` p
   WHERE p.`slug` = 'about/integrity' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/about/recognition';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'about/recognition');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'about/recognition', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 50
    FROM `pages` p
   WHERE p.`slug` = 'about/recognition' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/about/careers';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'about/careers');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'about/careers', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 60
    FROM `pages` p
   WHERE p.`slug` = 'about/careers' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;

INSERT IGNORE INTO `menus` (`slug`) VALUES ('project');
SET @m = (SELECT `id` FROM `menus` WHERE `slug` = 'project');
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/project/standards';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'project/standards');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'project/standards', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 10
    FROM `pages` p
   WHERE p.`slug` = 'project/standards' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/project/structures';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'project/structures');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'project/structures', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 20
    FROM `pages` p
   WHERE p.`slug` = 'project/structures' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/project/virtual-tour';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'project/virtual-tour');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'project/virtual-tour', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 30
    FROM `pages` p
   WHERE p.`slug` = 'project/virtual-tour' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;

INSERT IGNORE INTO `menus` (`slug`) VALUES ('disclosures');
SET @m = (SELECT `id` FROM `menus` WHERE `slug` = 'disclosures');
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/citizen-charter';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/citizen-charter');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/citizen-charter', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 10
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/citizen-charter' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/right-to-information';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/right-to-information');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/right-to-information', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 20
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/right-to-information' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/tariff';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/tariff');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/tariff', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 30
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/tariff' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/policies';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/policies');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/policies', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 40
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/policies' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/reports';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/reports');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/reports', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 50
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/reports' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/land-acquisition';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/land-acquisition');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/land-acquisition', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 60
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/land-acquisition' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/environment';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/environment');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/environment', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 70
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/environment' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/disclosures/consultations';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'disclosures/consultations');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'disclosures/consultations', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 80
    FROM `pages` p
   WHERE p.`slug` = 'disclosures/consultations' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/procurement';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'procurement');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'procurement', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 90
    FROM `pages` p
   WHERE p.`slug` = 'procurement' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;

INSERT IGNORE INTO `menus` (`slug`) VALUES ('safety');
SET @m = (SELECT `id` FROM `menus` WHERE `slug` = 'safety');
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/safety/education';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'safety/education');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'safety/education', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 10
    FROM `pages` p
   WHERE p.`slug` = 'safety/education' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/rules';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/rules');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/rules', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 20
    FROM `pages` p
   WHERE p.`slug` = 'travel/rules' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/advisories';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/advisories');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/advisories', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 30
    FROM `pages` p
   WHERE p.`slug` = 'travel/advisories' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/travel/breakdown';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'travel/breakdown');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'travel/breakdown', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 40
    FROM `pages` p
   WHERE p.`slug` = 'travel/breakdown' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;

INSERT IGNORE INTO `menus` (`slug`) VALUES ('media');
SET @m = (SELECT `id` FROM `menus` WHERE `slug` = 'media');
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/press-releases';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'press-releases');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'press-releases', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 10
    FROM `pages` p
   WHERE p.`slug` = 'press-releases' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/news';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'news');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'news', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 20
    FROM `pages` p
   WHERE p.`slug` = 'news' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/gallery';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'gallery');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'gallery', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 30
    FROM `pages` p
   WHERE p.`slug` = 'gallery' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/gallery/videos';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'gallery/videos');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'gallery/videos', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 40
    FROM `pages` p
   WHERE p.`slug` = 'gallery/videos' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/downloads';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'downloads');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'downloads', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 50
    FROM `pages` p
   WHERE p.`slug` = 'downloads' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;
DELETE FROM `menu_items` WHERE `menu_id` = @m AND `href` = '/contact';
SET @n = (SELECT COUNT(*) FROM `menu_items` WHERE `menu_id` = @m AND `href` = 'contact');
INSERT INTO `menu_items` (`menu_id`, `href`, `labels`, `sort_order`)
  SELECT @m, 'contact', JSON_OBJECT(
      'en', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'en'), ''),
      'bn', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'bn'), ''),
      'zh', COALESCE((SELECT `title` FROM `page_translations` WHERE `page_id` = p.`id` AND `locale` = 'zh'), '')
    ), 60
    FROM `pages` p
   WHERE p.`slug` = 'contact' AND p.`status` = 'published' AND @m IS NOT NULL AND @n = 0;

-- ---- 3. the sub-navigation blocks -----------------------------------------
-- At the top of each hub, above whatever the page already says. Existing blocks
-- move down one place; the guard means that happens only on the first import.

SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'travel');
SET @ok = (@p IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @p AND `type` = 'section-subnav') = 0);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `page_id` = @p AND @ok AND `type` <> 'page-header' AND `type` <> 'hero';
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @p, 'section-subnav', 1, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('menu', 'travel', 'label', pt.`title`), 'published'
    FROM `page_translations` pt
   WHERE @b IS NOT NULL AND pt.`page_id` = @p AND pt.`title` <> '';

SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'about');
SET @ok = (@p IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @p AND `type` = 'section-subnav') = 0);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `page_id` = @p AND @ok AND `type` <> 'page-header' AND `type` <> 'hero';
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @p, 'section-subnav', 1, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('menu', 'about', 'label', pt.`title`), 'published'
    FROM `page_translations` pt
   WHERE @b IS NOT NULL AND pt.`page_id` = @p AND pt.`title` <> '';

SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'project');
SET @ok = (@p IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @p AND `type` = 'section-subnav') = 0);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `page_id` = @p AND @ok AND `type` <> 'page-header' AND `type` <> 'hero';
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @p, 'section-subnav', 1, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('menu', 'project', 'label', pt.`title`), 'published'
    FROM `page_translations` pt
   WHERE @b IS NOT NULL AND pt.`page_id` = @p AND pt.`title` <> '';

SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'disclosures');
SET @ok = (@p IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @p AND `type` = 'section-subnav') = 0);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `page_id` = @p AND @ok AND `type` <> 'page-header' AND `type` <> 'hero';
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @p, 'section-subnav', 1, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('menu', 'disclosures', 'label', pt.`title`), 'published'
    FROM `page_translations` pt
   WHERE @b IS NOT NULL AND pt.`page_id` = @p AND pt.`title` <> '';

SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'safety');
SET @ok = (@p IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @p AND `type` = 'section-subnav') = 0);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `page_id` = @p AND @ok AND `type` <> 'page-header' AND `type` <> 'hero';
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @p, 'section-subnav', 1, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('menu', 'safety', 'label', pt.`title`), 'published'
    FROM `page_translations` pt
   WHERE @b IS NOT NULL AND pt.`page_id` = @p AND pt.`title` <> '';

SET @p = (SELECT `id` FROM `pages` WHERE `slug` = 'media');
SET @ok = (@p IS NOT NULL AND (SELECT COUNT(*) FROM `blocks` WHERE `page_id` = @p AND `type` = 'section-subnav') = 0);
UPDATE `blocks` SET `sort_order` = `sort_order` + 1 WHERE `page_id` = @p AND @ok AND `type` <> 'page-header' AND `type` <> 'hero';
INSERT INTO `blocks` (`page_id`, `type`, `sort_order`, `status`)
  SELECT @p, 'section-subnav', 1, 'published' FROM DUAL WHERE @ok;
SET @b = IF(@ok, LAST_INSERT_ID(), NULL);
INSERT INTO `block_translations` (`block_id`, `locale`, `data`, `status`)
  SELECT @b, pt.`locale`, JSON_OBJECT('menu', 'media', 'label', pt.`title`), 'published'
    FROM `page_translations` pt
   WHERE @b IS NOT NULL AND pt.`page_id` = @p AND pt.`title` <> '';

-- A sub-navigation announced as "Travel Info" on the About page is the block's
-- default label showing through. Name each one after its own section, in each
-- language, from the page's title — and only where the operator has not set a
-- label of their own.
UPDATE `block_translations` bt
  JOIN `blocks` b ON b.`id` = bt.`block_id` AND b.`type` = 'section-subnav'
  JOIN `page_translations` pt ON pt.`page_id` = b.`page_id` AND pt.`locale` = bt.`locale`
   SET bt.`data` = JSON_SET(bt.`data`, '$.label', pt.`title`)
 WHERE COALESCE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.label')), '') = ''
   AND pt.`title` <> '';

INSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('45-section-menus');
