-- 52: trust fixes from the human-quality audit (2026-09-17).
--
-- GENERATED by scripts/content/gen_audit_fixes.py. Edit that, not this.
--
--   C7  the sample control-room number (+880 2 5555 0199) is no longer
--       published: the setting is cleared, the sample directory entry loses
--       the number, and the safety and rules pages say "call 999".
--   C1  the home page no longer says the project figures are withheld while
--       About shows them.
--   C11 the rules page no longer sends three-wheelers to service roads that
--       its own table closes to them.
--   C3  one following distance: three seconds, as the education page says.
--   C9  the privacy notice names the traffic provider the code uses, and
--       lists road-alert sign-ups.
--   C10 the accessibility statement stops saying Chinese has no font.
--   T3  the Bangla home page loses a "two hours" claim the English never made.
--   T4  "US$৪১২ মি." (read as metres) becomes "৪১২ মিলিয়ন ডলার".
--
-- Every statement matches the exact text it replaces, so it is safe to
-- import twice and never overwrites an editor's later wording.

SET NAMES utf8mb4;

-- C7 --------------------------------------------------------------------
UPDATE `site_settings` SET `value` = '""'
 WHERE `setting_key` = 'contact.emergency_phone' AND LOCATE('5555 0199', CAST(`value` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"phone":"+880 2 5555 0199"', '"phone":""')
 WHERE LOCATE('"phone":"+880 2 5555 0199"', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"phone": "+880 2 5555 0199"', '"phone": ""')
 WHERE LOCATE('"phone": "+880 2 5555 0199"', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'In an emergency, call the DBEDC emergency line or the national emergency service — both numbers are at the foot of every page — and follow the instructions of the roadside staff. Ambulance, towing and recovery are arranged through the DBEDC emergency line.', 'In an emergency, call 999 and follow the instructions of the roadside staff.'))
 WHERE p.`slug` = 'safety' AND bt.`locale` = 'en'
   AND LOCATE('In an emergency, call the DBEDC emergency line or the national emergency service — both numbers are at the foot of every page — and follow the instructions of the roadside staff. Ambulance, towing and recovery are arranged through the DBEDC emergency line.', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'জরুরি অবস্থায় DBEDC জরুরি নম্বরে অথবা জাতীয় জরুরি সেবায় কল করুন — দুটি নম্বরই প্রতিটি পাতার নিচে দেওয়া আছে — এবং সড়ক কর্মীদের নির্দেশনা মেনে চলুন। অ্যাম্বুলেন্স, টোয়িং ও উদ্ধার সেবা DBEDC জরুরি নম্বরের মাধ্যমে ব্যবস্থা করা হয়।', 'জরুরি অবস্থায় ৯৯৯-এ কল করুন এবং সড়ক কর্মীদের নির্দেশনা মেনে চলুন।'))
 WHERE p.`slug` = 'safety' AND bt.`locale` = 'bn'
   AND LOCATE('জরুরি অবস্থায় DBEDC জরুরি নম্বরে অথবা জাতীয় জরুরি সেবায় কল করুন — দুটি নম্বরই প্রতিটি পাতার নিচে দেওয়া আছে — এবং সড়ক কর্মীদের নির্দেশনা মেনে চলুন। অ্যাম্বুলেন্স, টোয়িং ও উদ্ধার সেবা DBEDC জরুরি নম্বরের মাধ্যমে ব্যবস্থা করা হয়।', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '遇到紧急情况，请拨打 DBEDC 紧急电话或国家紧急服务电话（两个号码均列于每页底部），并听从路侧工作人员的指示。救护车、拖车与救援服务通过 DBEDC 紧急电话安排。', '遇到紧急情况，请拨打 999，并听从路侧工作人员的指示。'))
 WHERE p.`slug` = 'safety' AND bt.`locale` = 'zh'
   AND LOCATE('遇到紧急情况，请拨打 DBEDC 紧急电话或国家紧急服务电话（两个号码均列于每页底部），并听从路侧工作人员的指示。救护车、拖车与救援服务通过 DBEDC 紧急电话安排。', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'Call the DBEDC emergency line shown at the foot of every page, or use the nearest emergency call point. In a medical emergency call 999.', 'Call 999, or use the nearest emergency call point.'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'en'
   AND LOCATE('Call the DBEDC emergency line shown at the foot of every page, or use the nearest emergency call point. In a medical emergency call 999.', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'প্রতিটি পাতার নিচে দেওয়া DBEDC জরুরি নম্বরে কল করুন অথবা নিকটতম জরুরি কল পয়েন্ট (প্রতি ২ কিমি) ব্যবহার করুন। চিকিৎসা জরুরি অবস্থায় ৯৯৯-এ কল করুন।', '৯৯৯-এ কল করুন অথবা নিকটতম জরুরি কল পয়েন্ট (প্রতি ২ কিমি) ব্যবহার করুন।'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'bn'
   AND LOCATE('প্রতিটি পাতার নিচে দেওয়া DBEDC জরুরি নম্বরে কল করুন অথবা নিকটতম জরুরি কল পয়েন্ট (প্রতি ২ কিমি) ব্যবহার করুন। চিকিৎসা জরুরি অবস্থায় ৯৯৯-এ কল করুন।', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '拨打每页底部所示的 DBEDC 紧急电话，或使用最近的紧急呼叫点（每 2 公里一处）。医疗紧急情况请拨 999。', '拨打 999，或使用最近的紧急呼叫点（每 2 公里一处）。'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'zh'
   AND LOCATE('拨打每页底部所示的 DBEDC 紧急电话，或使用最近的紧急呼叫点（每 2 公里一处）。医疗紧急情况请拨 999。', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;

-- C1: the withheld-figures paragraph on the home page, in every language.
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REGEXP_REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<p class="db-provisional-inline">[^<]*</p>', ''))
 WHERE p.`slug` = 'home' AND b.`type` = 'media-prose' AND bt.`locale` = 'en'
   AND LOCATE('db-provisional-inline', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REGEXP_REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<p class="db-provisional-inline">[^<]*</p>', ''))
 WHERE p.`slug` = 'home' AND b.`type` = 'media-prose' AND bt.`locale` = 'bn'
   AND LOCATE('db-provisional-inline', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REGEXP_REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<p class="db-provisional-inline">[^<]*</p>', ''))
 WHERE p.`slug` = 'home' AND b.`type` = 'media-prose' AND bt.`locale` = 'zh'
   AND LOCATE('db-provisional-inline', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;

-- C11: service roads are for motorcycles, not three-wheelers.
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'The service roads running beside the tolled carriageways carry this traffic and connect to the same places. They are the correct route, not a diversion — the corridor was built with them for exactly this purpose.', 'Motorcycles may use the service roads beside the toll carriageways, which connect to the same places. Three-wheelers, rickshaws and non-motorised vehicles may not use the service roads either, and should use the local road network.'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'en'
   AND LOCATE('The service roads running beside the tolled carriageways carry this traffic and connect to the same places. They are the correct route, not a diversion — the corridor was built with them for exactly this purpose.', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'টোল ক্যারেজওয়ের পাশ দিয়ে চলা সার্ভিস রোডগুলি এই যান চলাচল বহন করে এবং একই গন্তব্যে পৌঁছায়। এগুলি বিকল্প বা ঘুরপথ নয়, এগুলিই সঠিক পথ — করিডোরটি ঠিক এই উদ্দেশ্যেই সার্ভিস রোডসহ নির্মিত।', 'টোল রোডের পাশের সার্ভিস রোড দিয়ে মোটরসাইকেল চলতে পারবে; এই রোড একই জায়গাগুলোতে যায়। থ্রি-হুইলার, রিকশা ও অযান্ত্রিক যান সার্ভিস রোডেও চলতে পারবে না — এগুলোকে স্থানীয় রাস্তা ব্যবহার করতে হবে।'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'bn'
   AND LOCATE('টোল ক্যারেজওয়ের পাশ দিয়ে চলা সার্ভিস রোডগুলি এই যান চলাচল বহন করে এবং একই গন্তব্যে পৌঁছায়। এগুলি বিকল্প বা ঘুরপথ নয়, এগুলিই সঠিক পথ — করিডোরটি ঠিক এই উদ্দেশ্যেই সার্ভিস রোডসহ নির্মিত।', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '收费行车道两侧的辅路承载此类交通，并通往相同目的地。它们不是绕行路线，而是正确路线——本走廊正是为此而配建辅路。', '摩托车可以走收费车道两侧的辅路，辅路通往相同的地点。三轮车、人力车和非机动车同样不得使用辅路，应走当地道路。'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'zh'
   AND LOCATE('收费行车道两侧的辅路承载此类交通，并通往相同目的地。它们不是绕行路线，而是正确路线——本走廊正是为此而配建辅路。', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;

-- C3: one following distance across the site.
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'keep a gap of at least two seconds', 'keep a gap of at least three seconds'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'en'
   AND LOCATE('keep a gap of at least two seconds', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'অন্তত দুই সেকেন্ডের দূরত্ব', 'অন্তত তিন সেকেন্ডের দূরত্ব'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'bn'
   AND LOCATE('অন্তত দুই সেকেন্ডের দূরত্ব', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '保持至少两秒的车距', '保持至少三秒的车距'))
 WHERE p.`slug` = 'travel/rules' AND bt.`locale` = 'zh'
   AND LOCATE('保持至少两秒的车距', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;

-- C9: the traffic provider is Google's Routes API; road-alert sign-ups are listed.
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'road-condition data on the map is fetched by our server from TomTom; nothing about you is sent to TomTom.', 'our server asks Google (Routes API) for journey times on each section of the corridor; nothing about you is sent with those requests.'))
 WHERE p.`slug` = 'privacy' AND bt.`locale` = 'en'
   AND LOCATE('road-condition data on the map is fetched by our server from TomTom; nothing about you is sent to TomTom.', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'মানচিত্রের সড়ক অবস্থার তথ্য আমাদের সার্ভার TomTom থেকে আনে; আপনার সম্পর্কে কিছুই TomTom-কে পাঠানো হয় না।', 'আমাদের সার্ভার করিডোরের প্রতিটি অংশের যাত্রার সময় Google (Routes API) থেকে জেনে নেয়; এসব অনুরোধের সঙ্গে আপনার সম্পর্কে কিছুই পাঠানো হয় না।'))
 WHERE p.`slug` = 'privacy' AND bt.`locale` = 'bn'
   AND LOCATE('মানচিত্রের সড়ক অবস্থার তথ্য আমাদের সার্ভার TomTom থেকে আনে; আপনার সম্পর্কে কিছুই TomTom-কে পাঠানো হয় না।', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '地图上的路况数据由我们的服务器从 TomTom 获取；不会向 TomTom 发送任何关于您的信息。', '我们的服务器向 Google（Routes API）查询走廊各路段的行程时间；这些请求不包含任何关于您的信息。'))
 WHERE p.`slug` = 'privacy' AND bt.`locale` = 'zh'
   AND LOCATE('地图上的路况数据由我们的服务器从 TomTom 获取；不会向 TomTom 发送任何关于您的信息。', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<li>Email sign-ups — the address only: until you unsubscribe or ask for removal.</li>', '<li>Email sign-ups — the address only: until you unsubscribe or ask for removal.</li><li>Road-alert sign-ups — your mobile number and the channel you chose (SMS or WhatsApp): until you unsubscribe.</li>'))
 WHERE p.`slug` = 'privacy' AND bt.`locale` = 'en'
   AND LOCATE('<li>Email sign-ups — the address only: until you unsubscribe or ask for removal.</li>', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<li>ইমেইল সাবস্ক্রিপশন — শুধু ঠিকানা: আপনি বাদ দিতে না বলা পর্যন্ত।</li>', '<li>ইমেইল সাবস্ক্রিপশন — শুধু ঠিকানা: আপনি বাদ দিতে না বলা পর্যন্ত।</li><li>রোড অ্যালার্ট সাবস্ক্রিপশন — আপনার মোবাইল নম্বর ও বেছে নেওয়া মাধ্যম (SMS বা WhatsApp): আনসাবস্ক্রাইব না করা পর্যন্ত।</li>'))
 WHERE p.`slug` = 'privacy' AND bt.`locale` = 'bn'
   AND LOCATE('<li>ইমেইল সাবস্ক্রিপশন — শুধু ঠিকানা: আপনি বাদ দিতে না বলা পর্যন্ত।</li>', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<li>邮件订阅——仅邮箱地址：直至您退订或要求删除。</li>', '<li>邮件订阅——仅邮箱地址：直至您退订或要求删除。</li><li>道路提醒订阅——您的手机号码及所选渠道（短信或 WhatsApp）：直至您退订。</li>'))
 WHERE p.`slug` = 'privacy' AND bt.`locale` = 'zh'
   AND LOCATE('<li>邮件订阅——仅邮箱地址：直至您退订或要求删除。</li>', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;

-- C10: Chinese pages do load a font (self-hosted Noto Sans SC).
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<p><strong>Chinese pages have no supplied font.</strong> The site ships Latin and Bengali web fonts but no Chinese one, so a reader on a device without a Chinese font installed may see empty boxes instead of characters.</p>', '<p><strong>Chinese text loads in parts.</strong> Chinese pages use a self-hosted Noto Sans SC font that downloads in pieces, so on a slow connection some characters may first appear in your device’s own font.</p>'))
 WHERE p.`slug` = 'accessibility' AND bt.`locale` = 'en'
   AND LOCATE('<p><strong>Chinese pages have no supplied font.</strong> The site ships Latin and Bengali web fonts but no Chinese one, so a reader on a device without a Chinese font installed may see empty boxes instead of characters.</p>', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<p><strong>চীনা পৃষ্ঠার জন্য কোনও ফন্ট সরবরাহ করা হয় না।</strong> সাইটটি ল্যাটিন ও বাংলা ওয়েব ফন্ট সরবরাহ করে, চীনা নয় — তাই যে ডিভাইসে চীনা ফন্ট ইনস্টল করা নেই সেখানে অক্ষরের বদলে খালি বাক্স দেখা যেতে পারে।</p>', '<p><strong>চীনা লেখা ধাপে ধাপে লোড হয়।</strong> চীনা পেজে সাইটের নিজস্ব Noto Sans SC ফন্ট টুকরো টুকরো ডাউনলোড হয়, তাই ধীর ইন্টারনেটে কিছু অক্ষর প্রথমে আপনার ডিভাইসের নিজের ফন্টে দেখা যেতে পারে।</p>'))
 WHERE p.`slug` = 'accessibility' AND bt.`locale` = 'bn'
   AND LOCATE('<p><strong>চীনা পৃষ্ঠার জন্য কোনও ফন্ট সরবরাহ করা হয় না।</strong> সাইটটি ল্যাটিন ও বাংলা ওয়েব ফন্ট সরবরাহ করে, চীনা নয় — তাই যে ডিভাইসে চীনা ফন্ট ইনস্টল করা নেই সেখানে অক্ষরের বদলে খালি বাক্স দেখা যেতে পারে।</p>', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), '<p><strong>中文页面未附带字体。</strong>本站提供拉丁文与孟加拉文网页字体，但未提供中文字体，因此未安装中文字体的设备可能显示空白方框而非文字。</p>', '<p><strong>中文字体分段加载。</strong>中文页面使用本站自托管的 Noto Sans SC 字体，按需分段下载；网络较慢时，部分文字可能先以设备自带字体显示。</p>'))
 WHERE p.`slug` = 'accessibility' AND bt.`locale` = 'zh'
   AND LOCATE('<p><strong>中文页面未附带字体。</strong>本站提供拉丁文与孟加拉文网页字体，但未提供中文字体，因此未安装中文字体的设备可能显示空白方框而非文字。</p>', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;

-- T3: the Bangla home page says what the English says.
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = JSON_SET(bt.`data`, '$.body', REPLACE(JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body')), 'এবং এ কারণেই শহরের ভেতর দিয়ে যে যাত্রায় দুই ঘণ্টা লাগে, সম্পূর্ণ করিডোর খুলে গেলে তা তার সামান্য সময়েই শেষ হওয়ার কথা।', 'এবং সে কারণেই পুরো করিডোর খুলে গেলে যে যাত্রা এখন শহরের ভেতর দিয়ে যায়, তা শহরকে পুরোপুরি এড়িয়ে যাবে।'))
 WHERE p.`slug` = 'home' AND bt.`locale` = 'bn'
   AND LOCATE('এবং এ কারণেই শহরের ভেতর দিয়ে যে যাত্রায় দুই ঘণ্টা লাগে, সম্পূর্ণ করিডোর খুলে গেলে তা তার সামান্য সময়েই শেষ হওয়ার কথা।', JSON_UNQUOTE(JSON_EXTRACT(bt.`data`, '$.body'))) > 0;

-- T4: "মি." reads as metres.
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"unit":"মি."', '"unit":"মিলিয়ন ডলার"')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('"unit":"মি."', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"value":"US$৪১২"', '"value":"৪১২"')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('"value":"US$৪১২"', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"unit": "মি."', '"unit": "মিলিয়ন ডলার"')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('"unit": "মি."', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"value": "US$৪১২"', '"value": "৪১২"')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('"value": "US$৪১২"', CAST(bt.`data` AS CHAR)) > 0;

INSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('52-audit-trust-fixes');
