-- 53: everyday Bangla (human-quality audit, section 2b).
--
-- GENERATED by scripts/content/gen_audit_fixes.py. Edit that, not this.
--
-- The Bangla a road user in Dhaka reads on signs, apps and news sites uses
-- the English word where that is what people say: ম্যাপ, not মানচিত্র;
-- আপডেট, not হালনাগাদ; পেজ, not পাতা. Statutory terms stay formal
-- (তথ্য অধিকার, নাগরিক সনদ, টোল বিজ্ঞপ্তি…), and the tariff notification
-- page keeps "যানবাহনের শ্রেণি", the wording of the gazette. Longer forms are
-- replaced before shorter ones, so suffixes come out right (পাতায় → পেজে).
-- Safe to import twice.

SET NAMES utf8mb4;
-- Blocks
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'মানচিত্রের', 'ম্যাপের')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('মানচিত্রের', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'মানচিত্রে', 'ম্যাপে')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('মানচিত্রে', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'মানচিত্র', 'ম্যাপ')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('মানচিত্র', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'হালনাগাদ', 'আপডেট')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('হালনাগাদ', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পৃষ্ঠস্তর', 'কার্পেটিং')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পৃষ্ঠস্তর', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'বহির্গমন পথ', 'এক্সিট')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('বহির্গমন পথ', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'বহির্গমন', 'এক্সিট')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('বহির্গমন', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'আলোকচিত্র', 'ছবি')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('আলোকচিত্র', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পৃষ্ঠার', 'পেজের')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পৃষ্ঠার', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পৃষ্ঠায়', 'পেজে')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পৃষ্ঠায়', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পৃষ্ঠাটি', 'পেজটি')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পৃষ্ঠাটি', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পৃষ্ঠা', 'পেজ')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পৃষ্ঠা', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতাগুলো', 'পেজগুলো')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতাগুলো', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতাগুলি', 'পেজগুলো')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতাগুলি', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতাতেই', 'পেজেই')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতাতেই', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতাতেও', 'পেজেও')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতাতেও', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতাপ্রতি', 'পেজপ্রতি')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতাপ্রতি', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতায়', 'পেজে')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতায়', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতার', 'পেজের')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতার', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতাটি', 'পেজটি')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতাটি', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'পাতা', 'পেজ')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('পাতা', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'প্রবেশ, প্রস্থান', 'এন্ট্রি, এক্সিট')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('প্রবেশ, প্রস্থান', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'প্রবেশ ও প্রস্থানের', 'এন্ট্রি ও এক্সিটের')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('প্রবেশ ও প্রস্থানের', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'প্রবেশ ও প্রস্থান', 'এন্ট্রি ও এক্সিট')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('প্রবেশ ও প্রস্থান', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'প্রস্থানের', 'এক্সিটের')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('প্রস্থানের', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'প্রস্থানে', 'এক্সিটে')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('প্রস্থানে', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'প্রস্থান', 'এক্সিট')
 WHERE bt.`locale` = 'bn'
   AND LOCATE('প্রস্থান', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'যানবাহনের শ্রেণির', 'গাড়ির ধরনের')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` NOT IN ('disclosures/tariff')
   AND LOCATE('যানবাহনের শ্রেণির', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'যানবাহন শ্রেণির', 'গাড়ির ধরনের')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` NOT IN ('disclosures/tariff')
   AND LOCATE('যানবাহন শ্রেণির', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'যানবাহনের শ্রেণি', 'গাড়ির ধরন')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` NOT IN ('disclosures/tariff')
   AND LOCATE('যানবাহনের শ্রেণি', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'যানবাহন শ্রেণি', 'গাড়ির ধরন')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` NOT IN ('disclosures/tariff')
   AND LOCATE('যানবাহন শ্রেণি', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'আপনার শ্রেণির', 'আপনার গাড়ির ধরনের')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` NOT IN ('disclosures/tariff')
   AND LOCATE('আপনার শ্রেণির', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'সরাসরি দেখুন', 'লাইভ দেখুন')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` IN ('travel/cameras')
   AND LOCATE('সরাসরি দেখুন', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'সরাসরি ভিডিও', 'লাইভ ভিডিও')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` IN ('travel/cameras')
   AND LOCATE('সরাসরি ভিডিও', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"heading":"অনুসন্ধান"', '"heading":"সার্চ"')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` IN ('search')
   AND LOCATE('"heading":"অনুসন্ধান"', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), '"heading": "অনুসন্ধান"', '"heading": "সার্চ"')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` IN ('search')
   AND LOCATE('"heading": "অনুসন্ধান"', CAST(bt.`data` AS CHAR)) > 0;
UPDATE `block_translations` bt JOIN `blocks` b ON b.`id` = bt.`block_id` JOIN `pages` p ON p.`id` = b.`page_id`
   SET bt.`data` = REPLACE(CAST(bt.`data` AS CHAR), 'অভিযোগ ও অনুসন্ধান', 'অভিযোগ ও সার্চ')
 WHERE bt.`locale` = 'bn'
   AND p.`slug` IN ('accessibility')
   AND LOCATE('অভিযোগ ও অনুসন্ধান', CAST(bt.`data` AS CHAR)) > 0;

-- Page titles and descriptions
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'মানচিত্রের', 'ম্যাপের') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্রের', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'মানচিত্রের', 'ম্যাপের') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্রের', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'মানচিত্রের', 'ম্যাপের') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্রের', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'মানচিত্রে', 'ম্যাপে') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্রে', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'মানচিত্রে', 'ম্যাপে') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্রে', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'মানচিত্রে', 'ম্যাপে') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্রে', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'মানচিত্র', 'ম্যাপ') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্র', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'মানচিত্র', 'ম্যাপ') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্র', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'মানচিত্র', 'ম্যাপ') WHERE pt.`locale` = 'bn' AND LOCATE('মানচিত্র', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'হালনাগাদ', 'আপডেট') WHERE pt.`locale` = 'bn' AND LOCATE('হালনাগাদ', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'হালনাগাদ', 'আপডেট') WHERE pt.`locale` = 'bn' AND LOCATE('হালনাগাদ', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'হালনাগাদ', 'আপডেট') WHERE pt.`locale` = 'bn' AND LOCATE('হালনাগাদ', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পৃষ্ঠস্তর', 'কার্পেটিং') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠস্তর', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পৃষ্ঠস্তর', 'কার্পেটিং') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠস্তর', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পৃষ্ঠস্তর', 'কার্পেটিং') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠস্তর', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'বহির্গমন পথ', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('বহির্গমন পথ', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'বহির্গমন পথ', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('বহির্গমন পথ', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'বহির্গমন পথ', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('বহির্গমন পথ', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'বহির্গমন', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('বহির্গমন', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'বহির্গমন', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('বহির্গমন', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'বহির্গমন', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('বহির্গমন', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'আলোকচিত্র', 'ছবি') WHERE pt.`locale` = 'bn' AND LOCATE('আলোকচিত্র', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'আলোকচিত্র', 'ছবি') WHERE pt.`locale` = 'bn' AND LOCATE('আলোকচিত্র', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'আলোকচিত্র', 'ছবি') WHERE pt.`locale` = 'bn' AND LOCATE('আলোকচিত্র', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পৃষ্ঠার', 'পেজের') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠার', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পৃষ্ঠার', 'পেজের') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠার', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পৃষ্ঠার', 'পেজের') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠার', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পৃষ্ঠায়', 'পেজে') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠায়', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পৃষ্ঠায়', 'পেজে') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠায়', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পৃষ্ঠায়', 'পেজে') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠায়', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পৃষ্ঠাটি', 'পেজটি') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠাটি', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পৃষ্ঠাটি', 'পেজটি') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠাটি', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পৃষ্ঠাটি', 'পেজটি') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠাটি', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পৃষ্ঠা', 'পেজ') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠা', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পৃষ্ঠা', 'পেজ') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠা', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পৃষ্ঠা', 'পেজ') WHERE pt.`locale` = 'bn' AND LOCATE('পৃষ্ঠা', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতাগুলো', 'পেজগুলো') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাগুলো', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতাগুলো', 'পেজগুলো') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাগুলো', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতাগুলো', 'পেজগুলো') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাগুলো', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতাগুলি', 'পেজগুলো') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাগুলি', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতাগুলি', 'পেজগুলো') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাগুলি', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতাগুলি', 'পেজগুলো') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাগুলি', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতাতেই', 'পেজেই') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাতেই', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতাতেই', 'পেজেই') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাতেই', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতাতেই', 'পেজেই') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাতেই', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতাতেও', 'পেজেও') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাতেও', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতাতেও', 'পেজেও') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাতেও', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতাতেও', 'পেজেও') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাতেও', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতাপ্রতি', 'পেজপ্রতি') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাপ্রতি', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতাপ্রতি', 'পেজপ্রতি') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাপ্রতি', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতাপ্রতি', 'পেজপ্রতি') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাপ্রতি', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতায়', 'পেজে') WHERE pt.`locale` = 'bn' AND LOCATE('পাতায়', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতায়', 'পেজে') WHERE pt.`locale` = 'bn' AND LOCATE('পাতায়', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতায়', 'পেজে') WHERE pt.`locale` = 'bn' AND LOCATE('পাতায়', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতার', 'পেজের') WHERE pt.`locale` = 'bn' AND LOCATE('পাতার', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতার', 'পেজের') WHERE pt.`locale` = 'bn' AND LOCATE('পাতার', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতার', 'পেজের') WHERE pt.`locale` = 'bn' AND LOCATE('পাতার', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতাটি', 'পেজটি') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাটি', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতাটি', 'পেজটি') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাটি', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতাটি', 'পেজটি') WHERE pt.`locale` = 'bn' AND LOCATE('পাতাটি', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'পাতা', 'পেজ') WHERE pt.`locale` = 'bn' AND LOCATE('পাতা', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'পাতা', 'পেজ') WHERE pt.`locale` = 'bn' AND LOCATE('পাতা', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'পাতা', 'পেজ') WHERE pt.`locale` = 'bn' AND LOCATE('পাতা', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'প্রবেশ, প্রস্থান', 'এন্ট্রি, এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ, প্রস্থান', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'প্রবেশ, প্রস্থান', 'এন্ট্রি, এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ, প্রস্থান', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'প্রবেশ, প্রস্থান', 'এন্ট্রি, এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ, প্রস্থান', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'প্রবেশ ও প্রস্থানের', 'এন্ট্রি ও এক্সিটের') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ ও প্রস্থানের', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'প্রবেশ ও প্রস্থানের', 'এন্ট্রি ও এক্সিটের') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ ও প্রস্থানের', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'প্রবেশ ও প্রস্থানের', 'এন্ট্রি ও এক্সিটের') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ ও প্রস্থানের', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'প্রবেশ ও প্রস্থান', 'এন্ট্রি ও এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ ও প্রস্থান', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'প্রবেশ ও প্রস্থান', 'এন্ট্রি ও এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ ও প্রস্থান', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'প্রবেশ ও প্রস্থান', 'এন্ট্রি ও এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রবেশ ও প্রস্থান', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'প্রস্থানের', 'এক্সিটের') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থানের', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'প্রস্থানের', 'এক্সিটের') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থানের', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'প্রস্থানের', 'এক্সিটের') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থানের', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'প্রস্থানে', 'এক্সিটে') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থানে', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'প্রস্থানে', 'এক্সিটে') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থানে', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'প্রস্থানে', 'এক্সিটে') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থানে', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'প্রস্থান', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থান', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'প্রস্থান', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থান', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'প্রস্থান', 'এক্সিট') WHERE pt.`locale` = 'bn' AND LOCATE('প্রস্থান', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'যানবাহনের শ্রেণির', 'গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহনের শ্রেণির', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'যানবাহনের শ্রেণির', 'গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহনের শ্রেণির', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'যানবাহনের শ্রেণির', 'গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহনের শ্রেণির', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'যানবাহন শ্রেণির', 'গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহন শ্রেণির', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'যানবাহন শ্রেণির', 'গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহন শ্রেণির', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'যানবাহন শ্রেণির', 'গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহন শ্রেণির', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'যানবাহনের শ্রেণি', 'গাড়ির ধরন') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহনের শ্রেণি', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'যানবাহনের শ্রেণি', 'গাড়ির ধরন') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহনের শ্রেণি', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'যানবাহনের শ্রেণি', 'গাড়ির ধরন') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহনের শ্রেণি', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'যানবাহন শ্রেণি', 'গাড়ির ধরন') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহন শ্রেণি', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'যানবাহন শ্রেণি', 'গাড়ির ধরন') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহন শ্রেণি', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'যানবাহন শ্রেণি', 'গাড়ির ধরন') WHERE pt.`locale` = 'bn' AND LOCATE('যানবাহন শ্রেণি', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'আপনার শ্রেণির', 'আপনার গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('আপনার শ্রেণির', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'আপনার শ্রেণির', 'আপনার গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('আপনার শ্রেণির', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'আপনার শ্রেণির', 'আপনার গাড়ির ধরনের') WHERE pt.`locale` = 'bn' AND LOCATE('আপনার শ্রেণির', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'সরাসরি দৃশ্য', 'লাইভ দৃশ্য') WHERE pt.`locale` = 'bn' AND p.`slug` IN ('travel/cameras') AND LOCATE('সরাসরি দৃশ্য', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'সরাসরি দৃশ্য', 'লাইভ দৃশ্য') WHERE pt.`locale` = 'bn' AND p.`slug` IN ('travel/cameras') AND LOCATE('সরাসরি দৃশ্য', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'সরাসরি দৃশ্য', 'লাইভ দৃশ্য') WHERE pt.`locale` = 'bn' AND p.`slug` IN ('travel/cameras') AND LOCATE('সরাসরি দৃশ্য', pt.`seo_description`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`title` = REPLACE(pt.`title`, 'অনুসন্ধান', 'সার্চ') WHERE pt.`locale` = 'bn' AND p.`slug` IN ('search') AND LOCATE('অনুসন্ধান', pt.`title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_title` = REPLACE(pt.`seo_title`, 'অনুসন্ধান', 'সার্চ') WHERE pt.`locale` = 'bn' AND p.`slug` IN ('search') AND LOCATE('অনুসন্ধান', pt.`seo_title`) > 0;
UPDATE `page_translations` pt JOIN `pages` p ON p.`id` = pt.`page_id` SET pt.`seo_description` = REPLACE(pt.`seo_description`, 'অনুসন্ধান', 'সার্চ') WHERE pt.`locale` = 'bn' AND p.`slug` IN ('search') AND LOCATE('অনুসন্ধান', pt.`seo_description`) > 0;

-- Menu labels (they are copies of the page titles)
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'মানচিত্রের', 'ম্যাপের') WHERE LOCATE('মানচিত্রের', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'মানচিত্রে', 'ম্যাপে') WHERE LOCATE('মানচিত্রে', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'মানচিত্র', 'ম্যাপ') WHERE LOCATE('মানচিত্র', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'হালনাগাদ', 'আপডেট') WHERE LOCATE('হালনাগাদ', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পৃষ্ঠস্তর', 'কার্পেটিং') WHERE LOCATE('পৃষ্ঠস্তর', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'বহির্গমন পথ', 'এক্সিট') WHERE LOCATE('বহির্গমন পথ', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'বহির্গমন', 'এক্সিট') WHERE LOCATE('বহির্গমন', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'আলোকচিত্র', 'ছবি') WHERE LOCATE('আলোকচিত্র', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পৃষ্ঠার', 'পেজের') WHERE LOCATE('পৃষ্ঠার', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পৃষ্ঠায়', 'পেজে') WHERE LOCATE('পৃষ্ঠায়', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পৃষ্ঠাটি', 'পেজটি') WHERE LOCATE('পৃষ্ঠাটি', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পৃষ্ঠা', 'পেজ') WHERE LOCATE('পৃষ্ঠা', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতাগুলো', 'পেজগুলো') WHERE LOCATE('পাতাগুলো', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতাগুলি', 'পেজগুলো') WHERE LOCATE('পাতাগুলি', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতাতেই', 'পেজেই') WHERE LOCATE('পাতাতেই', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতাতেও', 'পেজেও') WHERE LOCATE('পাতাতেও', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতাপ্রতি', 'পেজপ্রতি') WHERE LOCATE('পাতাপ্রতি', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতায়', 'পেজে') WHERE LOCATE('পাতায়', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতার', 'পেজের') WHERE LOCATE('পাতার', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতাটি', 'পেজটি') WHERE LOCATE('পাতাটি', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'পাতা', 'পেজ') WHERE LOCATE('পাতা', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'প্রবেশ, প্রস্থান', 'এন্ট্রি, এক্সিট') WHERE LOCATE('প্রবেশ, প্রস্থান', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'প্রবেশ ও প্রস্থানের', 'এন্ট্রি ও এক্সিটের') WHERE LOCATE('প্রবেশ ও প্রস্থানের', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'প্রবেশ ও প্রস্থান', 'এন্ট্রি ও এক্সিট') WHERE LOCATE('প্রবেশ ও প্রস্থান', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'প্রস্থানের', 'এক্সিটের') WHERE LOCATE('প্রস্থানের', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'প্রস্থানে', 'এক্সিটে') WHERE LOCATE('প্রস্থানে', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'প্রস্থান', 'এক্সিট') WHERE LOCATE('প্রস্থান', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'যানবাহনের শ্রেণির', 'গাড়ির ধরনের') WHERE LOCATE('যানবাহনের শ্রেণির', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'যানবাহন শ্রেণির', 'গাড়ির ধরনের') WHERE LOCATE('যানবাহন শ্রেণির', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'যানবাহনের শ্রেণি', 'গাড়ির ধরন') WHERE LOCATE('যানবাহনের শ্রেণি', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'যানবাহন শ্রেণি', 'গাড়ির ধরন') WHERE LOCATE('যানবাহন শ্রেণি', CAST(`labels` AS CHAR)) > 0;
UPDATE `menu_items` SET `labels` = REPLACE(CAST(`labels` AS CHAR), 'আপনার শ্রেণির', 'আপনার গাড়ির ধরনের') WHERE LOCATE('আপনার শ্রেণির', CAST(`labels` AS CHAR)) > 0;

INSERT IGNORE INTO `schema_migrations` (`name`) VALUES ('53-everyday-bangla');
